// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accessgrant.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations
SET status = 'accepted',
    updated_at = now()
WHERE id = $1
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at > now())
RETURNING id, workspace_id, invitee_email, invitee_phone, role_id, scope_type, scope_id, expires_at, invited_by, status, created_at, updated_at, template_code
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InviteeEmail,
		&i.InviteePhone,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateCode,
	)
	return i, err
}

const addAccessGrantPermissions = `-- name: AddAccessGrantPermissions :execrows
INSERT INTO access_grant_permissions (access_grant_id, permission_id)
SELECT $1, p.id
FROM permissions p
WHERE p.code = ANY($2::text[])
ON CONFLICT DO NOTHING
`

type AddAccessGrantPermissionsParams struct {
	AccessGrantID uuid.UUID `json:"access_grant_id"`
	Column2       []string  `json:"column_2"`
}

func (q *Queries) AddAccessGrantPermissions(ctx context.Context, arg AddAccessGrantPermissionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, addAccessGrantPermissions, arg.AccessGrantID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addInvitationPermissions = `-- name: AddInvitationPermissions :execrows
INSERT INTO invitation_permissions (invitation_id, permission_id)
SELECT $1, p.id
FROM permissions p
WHERE p.code = ANY($2::text[])
ON CONFLICT DO NOTHING
`

type AddInvitationPermissionsParams struct {
	InvitationID uuid.UUID `json:"invitation_id"`
	Column2      []string  `json:"column_2"`
}

func (q *Queries) AddInvitationPermissions(ctx context.Context, arg AddInvitationPermissionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, addInvitationPermissions, arg.InvitationID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const copyInvitationPermissionsToAccessGrant = `-- name: CopyInvitationPermissionsToAccessGrant :execrows
INSERT INTO access_grant_permissions (access_grant_id, permission_id)
SELECT $2, ip.permission_id
FROM invitation_permissions ip
WHERE ip.invitation_id = $1
ON CONFLICT DO NOTHING
`

type CopyInvitationPermissionsToAccessGrantParams struct {
	InvitationID  uuid.UUID `json:"invitation_id"`
	AccessGrantID uuid.UUID `json:"access_grant_id"`
}

func (q *Queries) CopyInvitationPermissionsToAccessGrant(ctx context.Context, arg CopyInvitationPermissionsToAccessGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, copyInvitationPermissionsToAccessGrant, arg.InvitationID, arg.AccessGrantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAccessGrant = `-- name: CreateAccessGrant :one
INSERT INTO access_grants (
    workspace_id,
    subject_type,
    subject_id,
    role_id,
    scope_type,
    scope_id,
    expires_at,
    allow_reshare,
    allow_api_access,
    created_by,
    template_code
)
VALUES ($1, 'user', $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workspace_id, subject_type, subject_id, role_id, scope_type, scope_id, expires_at, allow_reshare, allow_api_access, created_by, status, created_at, updated_at, template_code
`

type CreateAccessGrantParams struct {
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	SubjectID      uuid.UUID          `json:"subject_id"`
	RoleID         uuid.UUID          `json:"role_id"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        uuid.UUID          `json:"scope_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	AllowReshare   bool               `json:"allow_reshare"`
	AllowApiAccess bool               `json:"allow_api_access"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	TemplateCode   string             `json:"template_code"`
}

func (q *Queries) CreateAccessGrant(ctx context.Context, arg CreateAccessGrantParams) (AccessGrant, error) {
	row := q.db.QueryRow(ctx, createAccessGrant,
		arg.WorkspaceID,
		arg.SubjectID,
		arg.RoleID,
		arg.ScopeType,
		arg.ScopeID,
		arg.ExpiresAt,
		arg.AllowReshare,
		arg.AllowApiAccess,
		arg.CreatedBy,
		arg.TemplateCode,
	)
	var i AccessGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.AllowReshare,
		&i.AllowApiAccess,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateCode,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
    workspace_id,
    invitee_email,
    invitee_phone,
    role_id,
    scope_type,
    scope_id,
    expires_at,
    invited_by,
    template_code
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, invitee_email, invitee_phone, role_id, scope_type, scope_id, expires_at, invited_by, status, created_at, updated_at, template_code
`

type CreateInvitationParams struct {
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	InviteeEmail *string            `json:"invitee_email"`
	InviteePhone *string            `json:"invitee_phone"`
	RoleID       uuid.UUID          `json:"role_id"`
	ScopeType    string             `json:"scope_type"`
	ScopeID      uuid.UUID          `json:"scope_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	InvitedBy    uuid.UUID          `json:"invited_by"`
	TemplateCode string             `json:"template_code"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.WorkspaceID,
		arg.InviteeEmail,
		arg.InviteePhone,
		arg.RoleID,
		arg.ScopeType,
		arg.ScopeID,
		arg.ExpiresAt,
		arg.InvitedBy,
		arg.TemplateCode,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InviteeEmail,
		&i.InviteePhone,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateCode,
	)
	return i, err
}

const deleteAccessGrantPermissions = `-- name: DeleteAccessGrantPermissions :exec
DELETE FROM access_grant_permissions
WHERE access_grant_id = $1
`

func (q *Queries) DeleteAccessGrantPermissions(ctx context.Context, accessGrantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccessGrantPermissions, accessGrantID)
	return err
}

const deleteInvitationPermissions = `-- name: DeleteInvitationPermissions :exec
DELETE FROM invitation_permissions
WHERE invitation_id = $1
`

func (q *Queries) DeleteInvitationPermissions(ctx context.Context, invitationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitationPermissions, invitationID)
	return err
}

const expireAccessGrants = `-- name: ExpireAccessGrants :execrows
UPDATE access_grants
SET status = 'expired',
    updated_at = now()
WHERE status = 'active'
  AND expires_at IS NOT NULL
  AND expires_at <= now()
`

func (q *Queries) ExpireAccessGrants(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireAccessGrants)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireInvitations = `-- name: ExpireInvitations :execrows
UPDATE invitations
SET status = 'expired',
    updated_at = now()
WHERE status = 'pending'
  AND expires_at IS NOT NULL
  AND expires_at <= now()
`

func (q *Queries) ExpireInvitations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireInvitations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccessGrant = `-- name: GetAccessGrant :one
SELECT
    ag.id,
    ag.workspace_id,
    ag.subject_type,
    ag.subject_id,
    ag.role_id,
    ag.template_code AS role_code,
    COALESCE(tr.name, '自定义权限') AS role_name,
    ag.template_code,
    COALESCE(tr.name, '自定义权限') AS template_name,
    ARRAY(
        SELECT p.code
        FROM access_grant_permissions agp
        JOIN permissions p ON p.id = agp.permission_id
        WHERE agp.access_grant_id = ag.id
        ORDER BY p.resource_type, p.action, p.code
    )::text[] AS permission_codes,
    ag.scope_type,
    ag.scope_id,
    ag.expires_at,
    ag.allow_reshare,
    ag.allow_api_access,
    ag.created_by,
    ag.status,
    ag.created_at,
    ag.updated_at
FROM access_grants ag
LEFT JOIN roles tr ON tr.workspace_id IS NULL AND tr.code = ag.template_code
WHERE ag.id = $1
`

type GetAccessGrantRow struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       uuid.UUID          `json:"subject_id"`
	RoleID          uuid.UUID          `json:"role_id"`
	RoleCode        string             `json:"role_code"`
	RoleName        string             `json:"role_name"`
	TemplateCode    string             `json:"template_code"`
	TemplateName    string             `json:"template_name"`
	PermissionCodes []string           `json:"permission_codes"`
	ScopeType       string             `json:"scope_type"`
	ScopeID         uuid.UUID          `json:"scope_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AllowReshare    bool               `json:"allow_reshare"`
	AllowApiAccess  bool               `json:"allow_api_access"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAccessGrant(ctx context.Context, id uuid.UUID) (GetAccessGrantRow, error) {
	row := q.db.QueryRow(ctx, getAccessGrant, id)
	var i GetAccessGrantRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.RoleID,
		&i.RoleCode,
		&i.RoleName,
		&i.TemplateCode,
		&i.TemplateName,
		&i.PermissionCodes,
		&i.ScopeType,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.AllowReshare,
		&i.AllowApiAccess,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessGrantPermissionRole = `-- name: GetAccessGrantPermissionRole :one
SELECT ag.template_code
FROM access_grants ag
JOIN access_grant_permissions agp ON agp.access_grant_id = ag.id
JOIN permissions p ON p.id = agp.permission_id
WHERE ag.subject_type = 'user'
  AND ag.subject_id = $1
  AND ag.workspace_id = $2
  AND ag.status = 'active'
  AND (ag.expires_at IS NULL OR ag.expires_at > now())
  AND p.code = $3
  AND (
    ag.scope_type = 'workspace'
    OR (ag.scope_type = $4 AND ag.scope_id = $5)
    OR (ag.scope_type = 'project' AND $6::uuid IS NOT NULL AND ag.scope_id = $6::uuid)
    OR (ag.scope_type = 'site' AND $7::uuid IS NOT NULL AND ag.scope_id = $7::uuid)
    OR (ag.scope_type = 'device' AND $8::uuid IS NOT NULL AND ag.scope_id = $8::uuid)
    OR (ag.scope_type = 'dataset' AND $9::uuid IS NOT NULL AND ag.scope_id = $9::uuid)
  )
ORDER BY
  CASE WHEN ag.template_code = 'service_engineer' THEN 0 ELSE 1 END,
  ag.created_at DESC,
  ag.id DESC
LIMIT 1
`

type GetAccessGrantPermissionRoleParams struct {
	SubjectID   uuid.UUID `json:"subject_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Code        string    `json:"code"`
	ScopeType   string    `json:"scope_type"`
	ScopeID     uuid.UUID `json:"scope_id"`
	ProjectID   uuid.UUID `json:"project_id"`
	SiteID      uuid.UUID `json:"site_id"`
	DeviceID    uuid.UUID `json:"device_id"`
	DatasetID   uuid.UUID `json:"dataset_id"`
}

func (q *Queries) GetAccessGrantPermissionRole(ctx context.Context, arg GetAccessGrantPermissionRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getAccessGrantPermissionRole,
		arg.SubjectID,
		arg.WorkspaceID,
		arg.Code,
		arg.ScopeType,
		arg.ScopeID,
		arg.ProjectID,
		arg.SiteID,
		arg.DeviceID,
		arg.DatasetID,
	)
	var template_code string
	err := row.Scan(&template_code)
	return template_code, err
}

const getInvitation = `-- name: GetInvitation :one
SELECT
    i.id,
    i.workspace_id,
    i.invitee_email,
    i.invitee_phone,
    i.role_id,
    i.template_code AS role_code,
    COALESCE(tr.name, '自定义权限') AS role_name,
    i.template_code,
    COALESCE(tr.name, '自定义权限') AS template_name,
    ARRAY(
        SELECT p.code
        FROM invitation_permissions ip
        JOIN permissions p ON p.id = ip.permission_id
        WHERE ip.invitation_id = i.id
        ORDER BY p.resource_type, p.action, p.code
    )::text[] AS permission_codes,
    i.scope_type,
    i.scope_id,
    i.expires_at,
    i.invited_by,
    i.status,
    i.created_at,
    i.updated_at
FROM invitations i
LEFT JOIN roles tr ON tr.workspace_id IS NULL AND tr.code = i.template_code
WHERE i.id = $1
`

type GetInvitationRow struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	InviteeEmail    *string            `json:"invitee_email"`
	InviteePhone    *string            `json:"invitee_phone"`
	RoleID          uuid.UUID          `json:"role_id"`
	RoleCode        string             `json:"role_code"`
	RoleName        string             `json:"role_name"`
	TemplateCode    string             `json:"template_code"`
	TemplateName    string             `json:"template_name"`
	PermissionCodes []string           `json:"permission_codes"`
	ScopeType       string             `json:"scope_type"`
	ScopeID         uuid.UUID          `json:"scope_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	InvitedBy       uuid.UUID          `json:"invited_by"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetInvitation(ctx context.Context, id uuid.UUID) (GetInvitationRow, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i GetInvitationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InviteeEmail,
		&i.InviteePhone,
		&i.RoleID,
		&i.RoleCode,
		&i.RoleName,
		&i.TemplateCode,
		&i.TemplateName,
		&i.PermissionCodes,
		&i.ScopeType,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccessGrantsByWorkspace = `-- name: ListAccessGrantsByWorkspace :many
SELECT
    ag.id,
    ag.workspace_id,
    ag.subject_type,
    ag.subject_id,
    u.name AS subject_name,
    u.phone AS subject_phone,
    u.email AS subject_email,
    ag.role_id,
    ag.template_code AS role_code,
    COALESCE(tr.name, '自定义权限') AS role_name,
    ag.template_code,
    COALESCE(tr.name, '自定义权限') AS template_name,
    ARRAY(
        SELECT p.code
        FROM access_grant_permissions agp
        JOIN permissions p ON p.id = agp.permission_id
        WHERE agp.access_grant_id = ag.id
        ORDER BY p.resource_type, p.action, p.code
    )::text[] AS permission_codes,
    ag.scope_type,
    ag.scope_id,
    ag.expires_at,
    ag.allow_reshare,
    ag.allow_api_access,
    ag.created_by,
    ag.status,
    ag.created_at,
    ag.updated_at
FROM access_grants ag
LEFT JOIN roles tr ON tr.workspace_id IS NULL AND tr.code = ag.template_code
JOIN users u ON u.id = ag.subject_id
WHERE ag.workspace_id = $1
ORDER BY ag.created_at DESC, ag.id DESC
`

type ListAccessGrantsByWorkspaceRow struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       uuid.UUID          `json:"subject_id"`
	SubjectName     string             `json:"subject_name"`
	SubjectPhone    *string            `json:"subject_phone"`
	SubjectEmail    *string            `json:"subject_email"`
	RoleID          uuid.UUID          `json:"role_id"`
	RoleCode        string             `json:"role_code"`
	RoleName        string             `json:"role_name"`
	TemplateCode    string             `json:"template_code"`
	TemplateName    string             `json:"template_name"`
	PermissionCodes []string           `json:"permission_codes"`
	ScopeType       string             `json:"scope_type"`
	ScopeID         uuid.UUID          `json:"scope_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AllowReshare    bool               `json:"allow_reshare"`
	AllowApiAccess  bool               `json:"allow_api_access"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAccessGrantsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListAccessGrantsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listAccessGrantsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessGrantsByWorkspaceRow{}
	for rows.Next() {
		var i ListAccessGrantsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectPhone,
			&i.SubjectEmail,
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
			&i.TemplateCode,
			&i.TemplateName,
			&i.PermissionCodes,
			&i.ScopeType,
			&i.ScopeID,
			&i.ExpiresAt,
			&i.AllowReshare,
			&i.AllowApiAccess,
			&i.CreatedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessGrantsForUser = `-- name: ListAccessGrantsForUser :many
SELECT
    ag.id,
    ag.workspace_id,
    ag.subject_type,
    ag.subject_id,
    w.name AS workspace_name,
    ag.role_id,
    ag.template_code AS role_code,
    COALESCE(tr.name, '自定义权限') AS role_name,
    ag.template_code,
    COALESCE(tr.name, '自定义权限') AS template_name,
    ARRAY(
        SELECT p.code
        FROM access_grant_permissions agp
        JOIN permissions p ON p.id = agp.permission_id
        WHERE agp.access_grant_id = ag.id
        ORDER BY p.resource_type, p.action, p.code
    )::text[] AS permission_codes,
    ag.scope_type,
    ag.scope_id,
    ag.expires_at,
    ag.allow_reshare,
    ag.allow_api_access,
    ag.created_by,
    ag.status,
    ag.created_at,
    ag.updated_at
FROM access_grants ag
LEFT JOIN roles tr ON tr.workspace_id IS NULL AND tr.code = ag.template_code
JOIN workspaces w ON w.id = ag.workspace_id
WHERE ag.subject_type = 'user'
  AND ag.subject_id = $1
  AND ag.status = 'active'
  AND (ag.expires_at IS NULL OR ag.expires_at > now())
ORDER BY ag.created_at DESC, ag.id DESC
`

type ListAccessGrantsForUserRow struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       uuid.UUID          `json:"subject_id"`
	WorkspaceName   string             `json:"workspace_name"`
	RoleID          uuid.UUID          `json:"role_id"`
	RoleCode        string             `json:"role_code"`
	RoleName        string             `json:"role_name"`
	TemplateCode    string             `json:"template_code"`
	TemplateName    string             `json:"template_name"`
	PermissionCodes []string           `json:"permission_codes"`
	ScopeType       string             `json:"scope_type"`
	ScopeID         uuid.UUID          `json:"scope_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AllowReshare    bool               `json:"allow_reshare"`
	AllowApiAccess  bool               `json:"allow_api_access"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAccessGrantsForUser(ctx context.Context, subjectID uuid.UUID) ([]ListAccessGrantsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAccessGrantsForUser, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessGrantsForUserRow{}
	for rows.Next() {
		var i ListAccessGrantsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubjectType,
			&i.SubjectID,
			&i.WorkspaceName,
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
			&i.TemplateCode,
			&i.TemplateName,
			&i.PermissionCodes,
			&i.ScopeType,
			&i.ScopeID,
			&i.ExpiresAt,
			&i.AllowReshare,
			&i.AllowApiAccess,
			&i.CreatedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitationsByWorkspace = `-- name: ListInvitationsByWorkspace :many
SELECT
    i.id,
    i.workspace_id,
    i.invitee_email,
    i.invitee_phone,
    i.role_id,
    i.template_code AS role_code,
    COALESCE(tr.name, '自定义权限') AS role_name,
    i.template_code,
    COALESCE(tr.name, '自定义权限') AS template_name,
    ARRAY(
        SELECT p.code
        FROM invitation_permissions ip
        JOIN permissions p ON p.id = ip.permission_id
        WHERE ip.invitation_id = i.id
        ORDER BY p.resource_type, p.action, p.code
    )::text[] AS permission_codes,
    i.scope_type,
    i.scope_id,
    i.expires_at,
    i.invited_by,
    i.status,
    i.created_at,
    i.updated_at
FROM invitations i
LEFT JOIN roles tr ON tr.workspace_id IS NULL AND tr.code = i.template_code
WHERE i.workspace_id = $1
ORDER BY i.created_at DESC, i.id DESC
`

type ListInvitationsByWorkspaceRow struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	InviteeEmail    *string            `json:"invitee_email"`
	InviteePhone    *string            `json:"invitee_phone"`
	RoleID          uuid.UUID          `json:"role_id"`
	RoleCode        string             `json:"role_code"`
	RoleName        string             `json:"role_name"`
	TemplateCode    string             `json:"template_code"`
	TemplateName    string             `json:"template_name"`
	PermissionCodes []string           `json:"permission_codes"`
	ScopeType       string             `json:"scope_type"`
	ScopeID         uuid.UUID          `json:"scope_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	InvitedBy       uuid.UUID          `json:"invited_by"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListInvitationsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListInvitationsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listInvitationsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsByWorkspaceRow{}
	for rows.Next() {
		var i ListInvitationsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InviteeEmail,
			&i.InviteePhone,
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
			&i.TemplateCode,
			&i.TemplateName,
			&i.PermissionCodes,
			&i.ScopeType,
			&i.ScopeID,
			&i.ExpiresAt,
			&i.InvitedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsForIdentity = `-- name: ListPendingInvitationsForIdentity :many
SELECT
    i.id,
    i.workspace_id,
    i.invitee_email,
    i.invitee_phone,
    i.role_id,
    i.template_code AS role_code,
    COALESCE(tr.name, '自定义权限') AS role_name,
    i.template_code,
    COALESCE(tr.name, '自定义权限') AS template_name,
    ARRAY(
        SELECT p.code
        FROM invitation_permissions ip
        JOIN permissions p ON p.id = ip.permission_id
        WHERE ip.invitation_id = i.id
        ORDER BY p.resource_type, p.action, p.code
    )::text[] AS permission_codes,
    i.scope_type,
    i.scope_id,
    i.expires_at,
    i.invited_by,
    i.status,
    i.created_at,
    i.updated_at
FROM invitations i
LEFT JOIN roles tr ON tr.workspace_id IS NULL AND tr.code = i.template_code
WHERE i.status = 'pending'
  AND (i.expires_at IS NULL OR i.expires_at > now())
  AND (
    ($1::text IS NOT NULL AND i.invitee_email = $1::text)
    OR
    ($2::text IS NOT NULL AND i.invitee_phone = $2::text)
  )
ORDER BY i.created_at DESC, i.id DESC
`

type ListPendingInvitationsForIdentityParams struct {
	InviteeEmail string `json:"invitee_email"`
	InviteePhone string `json:"invitee_phone"`
}

type ListPendingInvitationsForIdentityRow struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	InviteeEmail    *string            `json:"invitee_email"`
	InviteePhone    *string            `json:"invitee_phone"`
	RoleID          uuid.UUID          `json:"role_id"`
	RoleCode        string             `json:"role_code"`
	RoleName        string             `json:"role_name"`
	TemplateCode    string             `json:"template_code"`
	TemplateName    string             `json:"template_name"`
	PermissionCodes []string           `json:"permission_codes"`
	ScopeType       string             `json:"scope_type"`
	ScopeID         uuid.UUID          `json:"scope_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	InvitedBy       uuid.UUID          `json:"invited_by"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPendingInvitationsForIdentity(ctx context.Context, arg ListPendingInvitationsForIdentityParams) ([]ListPendingInvitationsForIdentityRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsForIdentity, arg.InviteeEmail, arg.InviteePhone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsForIdentityRow{}
	for rows.Next() {
		var i ListPendingInvitationsForIdentityRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InviteeEmail,
			&i.InviteePhone,
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
			&i.TemplateCode,
			&i.TemplateName,
			&i.PermissionCodes,
			&i.ScopeType,
			&i.ScopeID,
			&i.ExpiresAt,
			&i.InvitedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessGrant = `-- name: RevokeAccessGrant :one
UPDATE access_grants
SET status = 'revoked',
    updated_at = now()
WHERE id = $1
  AND status = 'active'
RETURNING id, workspace_id, subject_type, subject_id, role_id, scope_type, scope_id, expires_at, allow_reshare, allow_api_access, created_by, status, created_at, updated_at, template_code
`

func (q *Queries) RevokeAccessGrant(ctx context.Context, id uuid.UUID) (AccessGrant, error) {
	row := q.db.QueryRow(ctx, revokeAccessGrant, id)
	var i AccessGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.AllowReshare,
		&i.AllowApiAccess,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateCode,
	)
	return i, err
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE invitations
SET status = 'revoked',
    updated_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, workspace_id, invitee_email, invitee_phone, role_id, scope_type, scope_id, expires_at, invited_by, status, created_at, updated_at, template_code
`

func (q *Queries) RevokeInvitation(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InviteeEmail,
		&i.InviteePhone,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateCode,
	)
	return i, err
}
