// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app_metadata.sql

package sqlc

import (
	"context"
)

const getAppMetadata = `-- name: GetAppMetadata :one
SELECT key, value, created_at, updated_at
FROM app_metadata
WHERE key = $1
`

func (q *Queries) GetAppMetadata(ctx context.Context, key string) (AppMetadatum, error) {
	row := q.db.QueryRow(ctx, getAppMetadata, key)
	var i AppMetadatum
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppMetadata = `-- name: ListAppMetadata :many
SELECT key, value, created_at, updated_at
FROM app_metadata
ORDER BY key
`

func (q *Queries) ListAppMetadata(ctx context.Context) ([]AppMetadatum, error) {
	rows, err := q.db.Query(ctx, listAppMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppMetadatum{}
	for rows.Next() {
		var i AppMetadatum
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppMetadata = `-- name: UpsertAppMetadata :one
INSERT INTO app_metadata (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = now()
RETURNING key, value, created_at, updated_at
`

type UpsertAppMetadataParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertAppMetadata(ctx context.Context, arg UpsertAppMetadataParams) (AppMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertAppMetadata, arg.Key, arg.Value)
	var i AppMetadatum
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
