// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    workspace_id,
    actor_type,
    actor_id,
    action,
    resource_type,
    resource_id,
    result,
    reason,
    ip,
    user_agent,
    request_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, actor_type, actor_id, action, resource_type, resource_id, result, reason, ip, user_agent, request_id, created_at, actor_admin_id
`

type CreateAuditLogParams struct {
	WorkspaceID  *uuid.UUID `json:"workspace_id"`
	ActorType    string     `json:"actor_type"`
	ActorID      *uuid.UUID `json:"actor_id"`
	Action       string     `json:"action"`
	ResourceType string     `json:"resource_type"`
	ResourceID   *uuid.UUID `json:"resource_id"`
	Result       string     `json:"result"`
	Reason       *string    `json:"reason"`
	Ip           *string    `json:"ip"`
	UserAgent    *string    `json:"user_agent"`
	RequestID    *string    `json:"request_id"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.WorkspaceID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Result,
		arg.Reason,
		arg.Ip,
		arg.UserAgent,
		arg.RequestID,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Result,
		&i.Reason,
		&i.Ip,
		&i.UserAgent,
		&i.RequestID,
		&i.CreatedAt,
		&i.ActorAdminID,
	)
	return i, err
}

const listAuditLogsByWorkspace = `-- name: ListAuditLogsByWorkspace :many
SELECT id, workspace_id, actor_type, actor_id, action, resource_type, resource_id, result, reason, ip, user_agent, request_id, created_at, actor_admin_id
FROM audit_logs
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAuditLogsByWorkspaceParams struct {
	WorkspaceID *uuid.UUID `json:"workspace_id"`
	Limit       int32      `json:"limit"`
}

func (q *Queries) ListAuditLogsByWorkspace(ctx context.Context, arg ListAuditLogsByWorkspaceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Result,
			&i.Reason,
			&i.Ip,
			&i.UserAgent,
			&i.RequestID,
			&i.CreatedAt,
			&i.ActorAdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
