// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserCredential = `-- name: CreateUserCredential :one
INSERT INTO user_credentials (user_id, password_hash)
VALUES ($1, $2)
RETURNING user_id, password_hash, password_updated_at, failed_attempts, locked_until, created_at, updated_at
`

type CreateUserCredentialParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) (UserCredential, error) {
	row := q.db.QueryRow(ctx, createUserCredential, arg.UserID, arg.PasswordHash)
	var i UserCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActiveUserByIdentifier = `-- name: FindActiveUserByIdentifier :one
SELECT id, name, phone, email, status, created_at, updated_at, phone_verified_at, email_verified_at, last_login_at
FROM users
WHERE status = 'active'
  AND (phone = $1 OR email = $1)
`

func (q *Queries) FindActiveUserByIdentifier(ctx context.Context, identifier *string) (User, error) {
	row := q.db.QueryRow(ctx, findActiveUserByIdentifier, identifier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneVerifiedAt,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const findActiveUserByPhoneForAuth = `-- name: FindActiveUserByPhoneForAuth :one
SELECT id, name, phone, email, status, created_at, updated_at, phone_verified_at, email_verified_at, last_login_at
FROM users
WHERE status = 'active'
  AND phone = $1
`

func (q *Queries) FindActiveUserByPhoneForAuth(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, findActiveUserByPhoneForAuth, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneVerifiedAt,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserCredential = `-- name: GetUserCredential :one
SELECT user_id, password_hash, password_updated_at, failed_attempts, locked_until, created_at, updated_at
FROM user_credentials
WHERE user_id = $1
`

func (q *Queries) GetUserCredential(ctx context.Context, userID uuid.UUID) (UserCredential, error) {
	row := q.db.QueryRow(ctx, getUserCredential, userID)
	var i UserCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetUserCredentialFailure = `-- name: ResetUserCredentialFailure :one
UPDATE user_credentials
SET failed_attempts = 0,
    locked_until = NULL,
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, password_hash, password_updated_at, failed_attempts, locked_until, created_at, updated_at
`

func (q *Queries) ResetUserCredentialFailure(ctx context.Context, userID uuid.UUID) (UserCredential, error) {
	row := q.db.QueryRow(ctx, resetUserCredentialFailure, userID)
	var i UserCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserCredentialFailure = `-- name: UpdateUserCredentialFailure :one
UPDATE user_credentials
SET failed_attempts = $2,
    locked_until = $3,
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, password_hash, password_updated_at, failed_attempts, locked_until, created_at, updated_at
`

type UpdateUserCredentialFailureParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) UpdateUserCredentialFailure(ctx context.Context, arg UpdateUserCredentialFailureParams) (UserCredential, error) {
	row := q.db.QueryRow(ctx, updateUserCredentialFailure, arg.UserID, arg.FailedAttempts, arg.LockedUntil)
	var i UserCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :one
UPDATE users
SET last_login_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, name, phone, email, status, created_at, updated_at, phone_verified_at, email_verified_at, last_login_at
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLastLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneVerifiedAt,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUserPhoneVerifiedAndLogin = `-- name: UpdateUserPhoneVerifiedAndLogin :one
UPDATE users
SET phone_verified_at = COALESCE(phone_verified_at, now()),
    last_login_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, name, phone, email, status, created_at, updated_at, phone_verified_at, email_verified_at, last_login_at
`

func (q *Queries) UpdateUserPhoneVerifiedAndLogin(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPhoneVerifiedAndLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneVerifiedAt,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
	)
	return i, err
}
