// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: camera.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCameraDevice = `-- name: CreateCameraDevice :one
INSERT INTO devices (
    product_id,
    name,
    status,
    activated_at,
    lifecycle_status,
    lifecycle_updated_at,
    device_type
)
VALUES ($1, $2, 'active', now(), 'online', now(), 'camera')
RETURNING id, product_id, serial_no, name, status, activated_at, created_at, updated_at, lifecycle_status, lifecycle_updated_at, device_type
`

type CreateCameraDeviceParams struct {
	ProductID *string `json:"product_id"`
	Name      string  `json:"name"`
}

func (q *Queries) CreateCameraDevice(ctx context.Context, arg CreateCameraDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createCameraDevice, arg.ProductID, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SerialNo,
		&i.Name,
		&i.Status,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.LifecycleUpdatedAt,
		&i.DeviceType,
	)
	return i, err
}

const getCameraBindingByDevice = `-- name: GetCameraBindingByDevice :one
SELECT id, device_id, provider, device_serial, channel_no, default_quality, is_encrypted, validate_code_secret_ref, status, created_at, updated_at
FROM camera_bindings
WHERE device_id = $1
`

func (q *Queries) GetCameraBindingByDevice(ctx context.Context, deviceID uuid.UUID) (CameraBinding, error) {
	row := q.db.QueryRow(ctx, getCameraBindingByDevice, deviceID)
	var i CameraBinding
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Provider,
		&i.DeviceSerial,
		&i.ChannelNo,
		&i.DefaultQuality,
		&i.IsEncrypted,
		&i.ValidateCodeSecretRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCameraBindingsByDevices = `-- name: ListCameraBindingsByDevices :many
SELECT id, device_id, provider, device_serial, channel_no, default_quality, is_encrypted, validate_code_secret_ref, status, created_at, updated_at
FROM camera_bindings
WHERE device_id = ANY($1::uuid[])
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCameraBindingsByDevices(ctx context.Context, dollar_1 []uuid.UUID) ([]CameraBinding, error) {
	rows, err := q.db.Query(ctx, listCameraBindingsByDevices, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraBinding{}
	for rows.Next() {
		var i CameraBinding
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Provider,
			&i.DeviceSerial,
			&i.ChannelNo,
			&i.DefaultQuality,
			&i.IsEncrypted,
			&i.ValidateCodeSecretRef,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCameraBindingStatus = `-- name: UpdateCameraBindingStatus :one
UPDATE camera_bindings
SET status = $2,
    updated_at = now()
WHERE device_id = $1
RETURNING id, device_id, provider, device_serial, channel_no, default_quality, is_encrypted, validate_code_secret_ref, status, created_at, updated_at
`

type UpdateCameraBindingStatusParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateCameraBindingStatus(ctx context.Context, arg UpdateCameraBindingStatusParams) (CameraBinding, error) {
	row := q.db.QueryRow(ctx, updateCameraBindingStatus, arg.DeviceID, arg.Status)
	var i CameraBinding
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Provider,
		&i.DeviceSerial,
		&i.ChannelNo,
		&i.DefaultQuality,
		&i.IsEncrypted,
		&i.ValidateCodeSecretRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCameraBinding = `-- name: UpsertCameraBinding :one
INSERT INTO camera_bindings (
    device_id,
    provider,
    device_serial,
    channel_no,
    default_quality,
    is_encrypted,
    validate_code_secret_ref,
    status
)
VALUES ($1, 'ezviz', $2, $3, $4, $5, $6, $7)
ON CONFLICT (device_id)
DO UPDATE SET
    device_serial = EXCLUDED.device_serial,
    channel_no = EXCLUDED.channel_no,
    default_quality = EXCLUDED.default_quality,
    is_encrypted = EXCLUDED.is_encrypted,
    validate_code_secret_ref = EXCLUDED.validate_code_secret_ref,
    status = EXCLUDED.status,
    updated_at = now()
RETURNING id, device_id, provider, device_serial, channel_no, default_quality, is_encrypted, validate_code_secret_ref, status, created_at, updated_at
`

type UpsertCameraBindingParams struct {
	DeviceID              uuid.UUID `json:"device_id"`
	DeviceSerial          string    `json:"device_serial"`
	ChannelNo             int32     `json:"channel_no"`
	DefaultQuality        string    `json:"default_quality"`
	IsEncrypted           bool      `json:"is_encrypted"`
	ValidateCodeSecretRef *string   `json:"validate_code_secret_ref"`
	Status                string    `json:"status"`
}

func (q *Queries) UpsertCameraBinding(ctx context.Context, arg UpsertCameraBindingParams) (CameraBinding, error) {
	row := q.db.QueryRow(ctx, upsertCameraBinding,
		arg.DeviceID,
		arg.DeviceSerial,
		arg.ChannelNo,
		arg.DefaultQuality,
		arg.IsEncrypted,
		arg.ValidateCodeSecretRef,
		arg.Status,
	)
	var i CameraBinding
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Provider,
		&i.DeviceSerial,
		&i.ChannelNo,
		&i.DefaultQuality,
		&i.IsEncrypted,
		&i.ValidateCodeSecretRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
