// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: carbon.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteCarbonRuntimeMetadata = `-- name: DeleteCarbonRuntimeMetadata :exec
DELETE FROM device_metadata
WHERE device_id = $1 AND key = ANY($2::text[])
`

type DeleteCarbonRuntimeMetadataParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	Column2  []string  `json:"column_2"`
}

func (q *Queries) DeleteCarbonRuntimeMetadata(ctx context.Context, arg DeleteCarbonRuntimeMetadataParams) error {
	_, err := q.db.Exec(ctx, deleteCarbonRuntimeMetadata, arg.DeviceID, arg.Column2)
	return err
}

const upsertCarbonMetadata = `-- name: UpsertCarbonMetadata :exec
INSERT INTO device_metadata (device_id, key, name, value_type, value_json, unit, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5::jsonb, $6, $7, $7)
ON CONFLICT (device_id, key) DO UPDATE SET
    name = EXCLUDED.name,
    value_type = EXCLUDED.value_type,
    value_json = EXCLUDED.value_json,
    unit = EXCLUDED.unit,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
`

type UpsertCarbonMetadataParams struct {
	DeviceID  uuid.UUID `json:"device_id"`
	Key       string    `json:"key"`
	Name      string    `json:"name"`
	ValueType string    `json:"value_type"`
	Column5   []byte    `json:"column_5"`
	Unit      *string   `json:"unit"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) UpsertCarbonMetadata(ctx context.Context, arg UpsertCarbonMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertCarbonMetadata,
		arg.DeviceID,
		arg.Key,
		arg.Name,
		arg.ValueType,
		arg.Column5,
		arg.Unit,
		arg.CreatedBy,
	)
	return err
}

const upsertCarbonNodeMetadata = `-- name: UpsertCarbonNodeMetadata :exec
INSERT INTO device_metadata (device_id, key, name, value_type, value_json, unit, created_by, updated_by)
VALUES ($1, 'carbon_nodes_count', 'Carbon 节点数', 'number', $2::jsonb, NULL, $3, $3)
ON CONFLICT (device_id, key) DO UPDATE SET
    value_json = EXCLUDED.value_json,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
`

type UpsertCarbonNodeMetadataParams struct {
	DeviceID  uuid.UUID `json:"device_id"`
	Column2   []byte    `json:"column_2"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) UpsertCarbonNodeMetadata(ctx context.Context, arg UpsertCarbonNodeMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertCarbonNodeMetadata, arg.DeviceID, arg.Column2, arg.CreatedBy)
	return err
}
