// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: datasource.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDataSource = `-- name: CreateDataSource :one
INSERT INTO data_sources (name, type, dsn_secret_ref, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, type, dsn_secret_ref, status, created_by, created_at, updated_at
`

type CreateDataSourceParams struct {
	Name         string    `json:"name"`
	Type         string    `json:"type"`
	DsnSecretRef string    `json:"dsn_secret_ref"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateDataSource(ctx context.Context, arg CreateDataSourceParams) (DataSource, error) {
	row := q.db.QueryRow(ctx, createDataSource,
		arg.Name,
		arg.Type,
		arg.DsnSecretRef,
		arg.CreatedBy,
	)
	var i DataSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.DsnSecretRef,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDataStreamBinding = `-- name: CreateDataStreamBinding :one
INSERT INTO data_stream_bindings (
    data_stream_id,
    data_source_id,
    adapter_code,
    database_name,
    schema_name,
    table_name,
    device_key_field,
    device_key_value,
    time_field,
    value_field,
    payload_type,
    adapter_config_json,
    created_by,
    created_by_type
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, data_stream_id, data_source_id, adapter_code, database_name, schema_name, table_name, device_key_field, device_key_value, time_field, value_field, payload_type, adapter_config_json, status, created_by, created_at, updated_at
`

type CreateDataStreamBindingParams struct {
	DataStreamID      uuid.UUID `json:"data_stream_id"`
	DataSourceID      uuid.UUID `json:"data_source_id"`
	AdapterCode       string    `json:"adapter_code"`
	DatabaseName      *string   `json:"database_name"`
	SchemaName        *string   `json:"schema_name"`
	TableName         *string   `json:"table_name"`
	DeviceKeyField    *string   `json:"device_key_field"`
	DeviceKeyValue    *string   `json:"device_key_value"`
	TimeField         *string   `json:"time_field"`
	ValueField        *string   `json:"value_field"`
	PayloadType       string    `json:"payload_type"`
	AdapterConfigJson []byte    `json:"adapter_config_json"`
	CreatedBy         uuid.UUID `json:"created_by"`
	CreatedByType     string    `json:"created_by_type"`
}

type CreateDataStreamBindingRow struct {
	ID                uuid.UUID          `json:"id"`
	DataStreamID      uuid.UUID          `json:"data_stream_id"`
	DataSourceID      uuid.UUID          `json:"data_source_id"`
	AdapterCode       string             `json:"adapter_code"`
	DatabaseName      *string            `json:"database_name"`
	SchemaName        *string            `json:"schema_name"`
	TableName         *string            `json:"table_name"`
	DeviceKeyField    *string            `json:"device_key_field"`
	DeviceKeyValue    *string            `json:"device_key_value"`
	TimeField         *string            `json:"time_field"`
	ValueField        *string            `json:"value_field"`
	PayloadType       string             `json:"payload_type"`
	AdapterConfigJson []byte             `json:"adapter_config_json"`
	Status            string             `json:"status"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDataStreamBinding(ctx context.Context, arg CreateDataStreamBindingParams) (CreateDataStreamBindingRow, error) {
	row := q.db.QueryRow(ctx, createDataStreamBinding,
		arg.DataStreamID,
		arg.DataSourceID,
		arg.AdapterCode,
		arg.DatabaseName,
		arg.SchemaName,
		arg.TableName,
		arg.DeviceKeyField,
		arg.DeviceKeyValue,
		arg.TimeField,
		arg.ValueField,
		arg.PayloadType,
		arg.AdapterConfigJson,
		arg.CreatedBy,
		arg.CreatedByType,
	)
	var i CreateDataStreamBindingRow
	err := row.Scan(
		&i.ID,
		&i.DataStreamID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.DatabaseName,
		&i.SchemaName,
		&i.TableName,
		&i.DeviceKeyField,
		&i.DeviceKeyValue,
		&i.TimeField,
		&i.ValueField,
		&i.PayloadType,
		&i.AdapterConfigJson,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableMissingTHCPNDataStreamBindings = `-- name: DisableMissingTHCPNDataStreamBindings :many
UPDATE data_stream_bindings AS dsb
SET status = 'disabled',
    updated_at = now()
FROM data_streams AS ds
WHERE ds.id = dsb.data_stream_id
  AND ds.device_id = $1
  AND dsb.data_source_id = $2
  AND dsb.adapter_code = 'thcpn_legacy_mysql'
  AND dsb.status = 'active'
  AND (dsb.adapter_config_json->>'external_device_id')::bigint = $3::bigint
  AND NOT (ds.code = ANY($4::text[]))
RETURNING dsb.id, dsb.data_stream_id, dsb.data_source_id, dsb.adapter_code, dsb.database_name, dsb.schema_name, dsb.table_name, dsb.device_key_field, dsb.device_key_value, dsb.time_field, dsb.value_field, dsb.payload_type, dsb.adapter_config_json, dsb.status, dsb.created_by, dsb.created_at, dsb.updated_at
`

type DisableMissingTHCPNDataStreamBindingsParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	DataSourceID     uuid.UUID `json:"data_source_id"`
	ExternalDeviceID int64     `json:"external_device_id"`
	ActiveCodes      []string  `json:"active_codes"`
}

type DisableMissingTHCPNDataStreamBindingsRow struct {
	ID                uuid.UUID          `json:"id"`
	DataStreamID      uuid.UUID          `json:"data_stream_id"`
	DataSourceID      uuid.UUID          `json:"data_source_id"`
	AdapterCode       string             `json:"adapter_code"`
	DatabaseName      *string            `json:"database_name"`
	SchemaName        *string            `json:"schema_name"`
	TableName         *string            `json:"table_name"`
	DeviceKeyField    *string            `json:"device_key_field"`
	DeviceKeyValue    *string            `json:"device_key_value"`
	TimeField         *string            `json:"time_field"`
	ValueField        *string            `json:"value_field"`
	PayloadType       string             `json:"payload_type"`
	AdapterConfigJson []byte             `json:"adapter_config_json"`
	Status            string             `json:"status"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DisableMissingTHCPNDataStreamBindings(ctx context.Context, arg DisableMissingTHCPNDataStreamBindingsParams) ([]DisableMissingTHCPNDataStreamBindingsRow, error) {
	rows, err := q.db.Query(ctx, disableMissingTHCPNDataStreamBindings,
		arg.DeviceID,
		arg.DataSourceID,
		arg.ExternalDeviceID,
		arg.ActiveCodes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DisableMissingTHCPNDataStreamBindingsRow{}
	for rows.Next() {
		var i DisableMissingTHCPNDataStreamBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.DataStreamID,
			&i.DataSourceID,
			&i.AdapterCode,
			&i.DatabaseName,
			&i.SchemaName,
			&i.TableName,
			&i.DeviceKeyField,
			&i.DeviceKeyValue,
			&i.TimeField,
			&i.ValueField,
			&i.PayloadType,
			&i.AdapterConfigJson,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveDataStreamBinding = `-- name: GetActiveDataStreamBinding :one
SELECT id, data_stream_id, data_source_id, adapter_code, database_name, schema_name, table_name, device_key_field, device_key_value, time_field, value_field, payload_type, adapter_config_json, status, created_by, created_at, updated_at
FROM data_stream_bindings
WHERE data_stream_id = $1
  AND status = 'active'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetActiveDataStreamBindingRow struct {
	ID                uuid.UUID          `json:"id"`
	DataStreamID      uuid.UUID          `json:"data_stream_id"`
	DataSourceID      uuid.UUID          `json:"data_source_id"`
	AdapterCode       string             `json:"adapter_code"`
	DatabaseName      *string            `json:"database_name"`
	SchemaName        *string            `json:"schema_name"`
	TableName         *string            `json:"table_name"`
	DeviceKeyField    *string            `json:"device_key_field"`
	DeviceKeyValue    *string            `json:"device_key_value"`
	TimeField         *string            `json:"time_field"`
	ValueField        *string            `json:"value_field"`
	PayloadType       string             `json:"payload_type"`
	AdapterConfigJson []byte             `json:"adapter_config_json"`
	Status            string             `json:"status"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveDataStreamBinding(ctx context.Context, dataStreamID uuid.UUID) (GetActiveDataStreamBindingRow, error) {
	row := q.db.QueryRow(ctx, getActiveDataStreamBinding, dataStreamID)
	var i GetActiveDataStreamBindingRow
	err := row.Scan(
		&i.ID,
		&i.DataStreamID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.DatabaseName,
		&i.SchemaName,
		&i.TableName,
		&i.DeviceKeyField,
		&i.DeviceKeyValue,
		&i.TimeField,
		&i.ValueField,
		&i.PayloadType,
		&i.AdapterConfigJson,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataSource = `-- name: GetDataSource :one
SELECT id, name, type, dsn_secret_ref, status, created_by, created_at, updated_at
FROM data_sources
WHERE id = $1
`

func (q *Queries) GetDataSource(ctx context.Context, id uuid.UUID) (DataSource, error) {
	row := q.db.QueryRow(ctx, getDataSource, id)
	var i DataSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.DsnSecretRef,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataStreamBinding = `-- name: GetDataStreamBinding :one
SELECT id, data_stream_id, data_source_id, adapter_code, database_name, schema_name, table_name, device_key_field, device_key_value, time_field, value_field, payload_type, adapter_config_json, status, created_by, created_at, updated_at
FROM data_stream_bindings
WHERE id = $1
`

type GetDataStreamBindingRow struct {
	ID                uuid.UUID          `json:"id"`
	DataStreamID      uuid.UUID          `json:"data_stream_id"`
	DataSourceID      uuid.UUID          `json:"data_source_id"`
	AdapterCode       string             `json:"adapter_code"`
	DatabaseName      *string            `json:"database_name"`
	SchemaName        *string            `json:"schema_name"`
	TableName         *string            `json:"table_name"`
	DeviceKeyField    *string            `json:"device_key_field"`
	DeviceKeyValue    *string            `json:"device_key_value"`
	TimeField         *string            `json:"time_field"`
	ValueField        *string            `json:"value_field"`
	PayloadType       string             `json:"payload_type"`
	AdapterConfigJson []byte             `json:"adapter_config_json"`
	Status            string             `json:"status"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDataStreamBinding(ctx context.Context, id uuid.UUID) (GetDataStreamBindingRow, error) {
	row := q.db.QueryRow(ctx, getDataStreamBinding, id)
	var i GetDataStreamBindingRow
	err := row.Scan(
		&i.ID,
		&i.DataStreamID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.DatabaseName,
		&i.SchemaName,
		&i.TableName,
		&i.DeviceKeyField,
		&i.DeviceKeyValue,
		&i.TimeField,
		&i.ValueField,
		&i.PayloadType,
		&i.AdapterConfigJson,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDataSources = `-- name: ListDataSources :many
SELECT id, name, type, dsn_secret_ref, status, created_by, created_at, updated_at
FROM data_sources
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDataSources(ctx context.Context) ([]DataSource, error) {
	rows, err := q.db.Query(ctx, listDataSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataSource{}
	for rows.Next() {
		var i DataSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.DsnSecretRef,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataStreamBindingsByDataStream = `-- name: ListDataStreamBindingsByDataStream :many
SELECT id, data_stream_id, data_source_id, adapter_code, database_name, schema_name, table_name, device_key_field, device_key_value, time_field, value_field, payload_type, adapter_config_json, status, created_by, created_at, updated_at
FROM data_stream_bindings
WHERE data_stream_id = $1
ORDER BY created_at DESC, id DESC
`

type ListDataStreamBindingsByDataStreamRow struct {
	ID                uuid.UUID          `json:"id"`
	DataStreamID      uuid.UUID          `json:"data_stream_id"`
	DataSourceID      uuid.UUID          `json:"data_source_id"`
	AdapterCode       string             `json:"adapter_code"`
	DatabaseName      *string            `json:"database_name"`
	SchemaName        *string            `json:"schema_name"`
	TableName         *string            `json:"table_name"`
	DeviceKeyField    *string            `json:"device_key_field"`
	DeviceKeyValue    *string            `json:"device_key_value"`
	TimeField         *string            `json:"time_field"`
	ValueField        *string            `json:"value_field"`
	PayloadType       string             `json:"payload_type"`
	AdapterConfigJson []byte             `json:"adapter_config_json"`
	Status            string             `json:"status"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDataStreamBindingsByDataStream(ctx context.Context, dataStreamID uuid.UUID) ([]ListDataStreamBindingsByDataStreamRow, error) {
	rows, err := q.db.Query(ctx, listDataStreamBindingsByDataStream, dataStreamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDataStreamBindingsByDataStreamRow{}
	for rows.Next() {
		var i ListDataStreamBindingsByDataStreamRow
		if err := rows.Scan(
			&i.ID,
			&i.DataStreamID,
			&i.DataSourceID,
			&i.AdapterCode,
			&i.DatabaseName,
			&i.SchemaName,
			&i.TableName,
			&i.DeviceKeyField,
			&i.DeviceKeyValue,
			&i.TimeField,
			&i.ValueField,
			&i.PayloadType,
			&i.AdapterConfigJson,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataSource = `-- name: UpdateDataSource :one
UPDATE data_sources
SET name = $2,
    type = $3,
    dsn_secret_ref = $4,
    status = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, type, dsn_secret_ref, status, created_by, created_at, updated_at
`

type UpdateDataSourceParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Type         string    `json:"type"`
	DsnSecretRef string    `json:"dsn_secret_ref"`
	Status       string    `json:"status"`
}

func (q *Queries) UpdateDataSource(ctx context.Context, arg UpdateDataSourceParams) (DataSource, error) {
	row := q.db.QueryRow(ctx, updateDataSource,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.DsnSecretRef,
		arg.Status,
	)
	var i DataSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.DsnSecretRef,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDataStreamBinding = `-- name: UpdateDataStreamBinding :one
UPDATE data_stream_bindings
SET data_source_id = $2,
    adapter_code = $3,
    database_name = $4,
    schema_name = $5,
    table_name = $6,
    device_key_field = $7,
    device_key_value = $8,
    time_field = $9,
    value_field = $10,
    payload_type = $11,
    adapter_config_json = $12,
    status = $13,
    updated_at = now()
WHERE id = $1
RETURNING id, data_stream_id, data_source_id, adapter_code, database_name, schema_name, table_name, device_key_field, device_key_value, time_field, value_field, payload_type, adapter_config_json, status, created_by, created_at, updated_at
`

type UpdateDataStreamBindingParams struct {
	ID                uuid.UUID `json:"id"`
	DataSourceID      uuid.UUID `json:"data_source_id"`
	AdapterCode       string    `json:"adapter_code"`
	DatabaseName      *string   `json:"database_name"`
	SchemaName        *string   `json:"schema_name"`
	TableName         *string   `json:"table_name"`
	DeviceKeyField    *string   `json:"device_key_field"`
	DeviceKeyValue    *string   `json:"device_key_value"`
	TimeField         *string   `json:"time_field"`
	ValueField        *string   `json:"value_field"`
	PayloadType       string    `json:"payload_type"`
	AdapterConfigJson []byte    `json:"adapter_config_json"`
	Status            string    `json:"status"`
}

type UpdateDataStreamBindingRow struct {
	ID                uuid.UUID          `json:"id"`
	DataStreamID      uuid.UUID          `json:"data_stream_id"`
	DataSourceID      uuid.UUID          `json:"data_source_id"`
	AdapterCode       string             `json:"adapter_code"`
	DatabaseName      *string            `json:"database_name"`
	SchemaName        *string            `json:"schema_name"`
	TableName         *string            `json:"table_name"`
	DeviceKeyField    *string            `json:"device_key_field"`
	DeviceKeyValue    *string            `json:"device_key_value"`
	TimeField         *string            `json:"time_field"`
	ValueField        *string            `json:"value_field"`
	PayloadType       string             `json:"payload_type"`
	AdapterConfigJson []byte             `json:"adapter_config_json"`
	Status            string             `json:"status"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateDataStreamBinding(ctx context.Context, arg UpdateDataStreamBindingParams) (UpdateDataStreamBindingRow, error) {
	row := q.db.QueryRow(ctx, updateDataStreamBinding,
		arg.ID,
		arg.DataSourceID,
		arg.AdapterCode,
		arg.DatabaseName,
		arg.SchemaName,
		arg.TableName,
		arg.DeviceKeyField,
		arg.DeviceKeyValue,
		arg.TimeField,
		arg.ValueField,
		arg.PayloadType,
		arg.AdapterConfigJson,
		arg.Status,
	)
	var i UpdateDataStreamBindingRow
	err := row.Scan(
		&i.ID,
		&i.DataStreamID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.DatabaseName,
		&i.SchemaName,
		&i.TableName,
		&i.DeviceKeyField,
		&i.DeviceKeyValue,
		&i.TimeField,
		&i.ValueField,
		&i.PayloadType,
		&i.AdapterConfigJson,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
