// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: datastream.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDataStream = `-- name: CreateDataStream :one
INSERT INTO data_streams (device_id, code, name, type, unit, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, device_id, code, name, type, unit, status, created_by, created_at, updated_at
`

type CreateDataStreamParams struct {
	DeviceID  uuid.UUID `json:"device_id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Unit      *string   `json:"unit"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateDataStream(ctx context.Context, arg CreateDataStreamParams) (DataStream, error) {
	row := q.db.QueryRow(ctx, createDataStream,
		arg.DeviceID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Unit,
		arg.CreatedBy,
	)
	var i DataStream
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Unit,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableMissingTHCPNDataStreams = `-- name: DisableMissingTHCPNDataStreams :many
UPDATE data_streams AS ds
SET status = 'disabled',
    updated_at = now()
WHERE ds.device_id = $1
  AND ds.status = 'active'
  AND NOT (ds.code = ANY($2::text[]))
  AND EXISTS (
      SELECT 1
      FROM data_stream_bindings AS dsb
      WHERE dsb.data_stream_id = ds.id
        AND dsb.data_source_id = $3
        AND dsb.adapter_code = 'thcpn_legacy_mysql'
        AND dsb.status = 'active'
        AND (dsb.adapter_config_json->>'external_device_id')::bigint = $4::bigint
  )
RETURNING ds.id, ds.device_id, ds.code, ds.name, ds.type, ds.unit, ds.status, ds.created_by, ds.created_at, ds.updated_at
`

type DisableMissingTHCPNDataStreamsParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	ActiveCodes      []string  `json:"active_codes"`
	DataSourceID     uuid.UUID `json:"data_source_id"`
	ExternalDeviceID int64     `json:"external_device_id"`
}

func (q *Queries) DisableMissingTHCPNDataStreams(ctx context.Context, arg DisableMissingTHCPNDataStreamsParams) ([]DataStream, error) {
	rows, err := q.db.Query(ctx, disableMissingTHCPNDataStreams,
		arg.DeviceID,
		arg.ActiveCodes,
		arg.DataSourceID,
		arg.ExternalDeviceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataStream{}
	for rows.Next() {
		var i DataStream
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Unit,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataStream = `-- name: GetDataStream :one
SELECT id, device_id, code, name, type, unit, status, created_by, created_at, updated_at
FROM data_streams
WHERE id = $1
`

func (q *Queries) GetDataStream(ctx context.Context, id uuid.UUID) (DataStream, error) {
	row := q.db.QueryRow(ctx, getDataStream, id)
	var i DataStream
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Unit,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDataStreamsByDevice = `-- name: ListDataStreamsByDevice :many
SELECT id, device_id, code, name, type, unit, status, created_by, created_at, updated_at
FROM data_streams
WHERE device_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDataStreamsByDevice(ctx context.Context, deviceID uuid.UUID) ([]DataStream, error) {
	rows, err := q.db.Query(ctx, listDataStreamsByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataStream{}
	for rows.Next() {
		var i DataStream
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Unit,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataStream = `-- name: UpdateDataStream :one
UPDATE data_streams
SET code = $2,
    name = $3,
    type = $4,
    unit = $5,
    status = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, device_id, code, name, type, unit, status, created_by, created_at, updated_at
`

type UpdateDataStreamParams struct {
	ID     uuid.UUID `json:"id"`
	Code   string    `json:"code"`
	Name   string    `json:"name"`
	Type   string    `json:"type"`
	Unit   *string   `json:"unit"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDataStream(ctx context.Context, arg UpdateDataStreamParams) (DataStream, error) {
	row := q.db.QueryRow(ctx, updateDataStream,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Unit,
		arg.Status,
	)
	var i DataStream
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Unit,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDataStreamFromSync = `-- name: UpsertDataStreamFromSync :one
INSERT INTO data_streams (device_id, code, name, type, unit, status, created_by)
VALUES ($1, $2, $3, $4, $5, 'active', $6)
ON CONFLICT (device_id, code)
DO UPDATE SET
    name = EXCLUDED.name,
    type = EXCLUDED.type,
    unit = EXCLUDED.unit,
    status = CASE
        WHEN data_streams.status = 'archived' THEN data_streams.status
        ELSE 'active'
    END,
    updated_at = now()
RETURNING id, device_id, code, name, type, unit, status, created_by, created_at, updated_at
`

type UpsertDataStreamFromSyncParams struct {
	DeviceID  uuid.UUID `json:"device_id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Unit      *string   `json:"unit"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) UpsertDataStreamFromSync(ctx context.Context, arg UpsertDataStreamFromSyncParams) (DataStream, error) {
	row := q.db.QueryRow(ctx, upsertDataStreamFromSync,
		arg.DeviceID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Unit,
		arg.CreatedBy,
	)
	var i DataStream
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Unit,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
