// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDeviceCapability = `-- name: AddDeviceCapability :one
INSERT INTO device_capabilities (device_id, capability_code)
VALUES ($1, $2)
ON CONFLICT (device_id, capability_code) DO NOTHING
RETURNING id, device_id, capability_code, created_at
`

type AddDeviceCapabilityParams struct {
	DeviceID       uuid.UUID `json:"device_id"`
	CapabilityCode string    `json:"capability_code"`
}

func (q *Queries) AddDeviceCapability(ctx context.Context, arg AddDeviceCapabilityParams) (DeviceCapability, error) {
	row := q.db.QueryRow(ctx, addDeviceCapability, arg.DeviceID, arg.CapabilityCode)
	var i DeviceCapability
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CapabilityCode,
		&i.CreatedAt,
	)
	return i, err
}

const closeActiveDeviceAssignment = `-- name: CloseActiveDeviceAssignment :one
UPDATE device_assignments
SET status = $2,
    unassigned_at = now(),
    updated_at = now()
WHERE device_id = $1
  AND status = 'active'
RETURNING id, device_id, workspace_id, project_id, site_id, status, assigned_by, assigned_at, unassigned_at, created_at, updated_at, assigned_by_type
`

type CloseActiveDeviceAssignmentParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	Status   string    `json:"status"`
}

func (q *Queries) CloseActiveDeviceAssignment(ctx context.Context, arg CloseActiveDeviceAssignmentParams) (DeviceAssignment, error) {
	row := q.db.QueryRow(ctx, closeActiveDeviceAssignment, arg.DeviceID, arg.Status)
	var i DeviceAssignment
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.SiteID,
		&i.Status,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.UnassignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedByType,
	)
	return i, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    product_id,
    name,
    status,
    activated_at
)
VALUES ($1, $2, 'active', now())
RETURNING id, product_id, serial_no, name, status, activated_at, created_at, updated_at, lifecycle_status, lifecycle_updated_at, device_type
`

type CreateDeviceParams struct {
	ProductID *string `json:"product_id"`
	Name      string  `json:"name"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.ProductID, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SerialNo,
		&i.Name,
		&i.Status,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.LifecycleUpdatedAt,
		&i.DeviceType,
	)
	return i, err
}

const createDeviceAssignment = `-- name: CreateDeviceAssignment :one
INSERT INTO device_assignments (
    device_id,
    workspace_id,
    project_id,
    site_id,
    assigned_by,
    assigned_by_type
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, device_id, workspace_id, project_id, site_id, status, assigned_by, assigned_at, unassigned_at, created_at, updated_at, assigned_by_type
`

type CreateDeviceAssignmentParams struct {
	DeviceID       uuid.UUID  `json:"device_id"`
	WorkspaceID    uuid.UUID  `json:"workspace_id"`
	ProjectID      *uuid.UUID `json:"project_id"`
	SiteID         *uuid.UUID `json:"site_id"`
	AssignedBy     *uuid.UUID `json:"assigned_by"`
	AssignedByType string     `json:"assigned_by_type"`
}

func (q *Queries) CreateDeviceAssignment(ctx context.Context, arg CreateDeviceAssignmentParams) (DeviceAssignment, error) {
	row := q.db.QueryRow(ctx, createDeviceAssignment,
		arg.DeviceID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.SiteID,
		arg.AssignedBy,
		arg.AssignedByType,
	)
	var i DeviceAssignment
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.SiteID,
		&i.Status,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.UnassignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedByType,
	)
	return i, err
}

const createDeviceLifecycleEvent = `-- name: CreateDeviceLifecycleEvent :one
INSERT INTO device_lifecycle_events (
    device_id,
    from_status,
    to_status,
    occurred_at,
    note,
    actor_user_id
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, device_id, from_status, to_status, occurred_at, note, actor_user_id, created_at
`

type CreateDeviceLifecycleEventParams struct {
	DeviceID    uuid.UUID          `json:"device_id"`
	FromStatus  *string            `json:"from_status"`
	ToStatus    string             `json:"to_status"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Note        *string            `json:"note"`
	ActorUserID *uuid.UUID         `json:"actor_user_id"`
}

func (q *Queries) CreateDeviceLifecycleEvent(ctx context.Context, arg CreateDeviceLifecycleEventParams) (DeviceLifecycleEvent, error) {
	row := q.db.QueryRow(ctx, createDeviceLifecycleEvent,
		arg.DeviceID,
		arg.FromStatus,
		arg.ToStatus,
		arg.OccurredAt,
		arg.Note,
		arg.ActorUserID,
	)
	var i DeviceLifecycleEvent
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FromStatus,
		&i.ToStatus,
		&i.OccurredAt,
		&i.Note,
		&i.ActorUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createDeviceOperation = `-- name: CreateDeviceOperation :one
INSERT INTO device_operations (
    workspace_id,
    device_id,
    operation_type,
    request_json,
    requested_by
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, device_id, operation_type, status, request_json, requested_by, created_at, updated_at
`

type CreateDeviceOperationParams struct {
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	DeviceID      uuid.UUID `json:"device_id"`
	OperationType string    `json:"operation_type"`
	RequestJson   []byte    `json:"request_json"`
	RequestedBy   uuid.UUID `json:"requested_by"`
}

func (q *Queries) CreateDeviceOperation(ctx context.Context, arg CreateDeviceOperationParams) (DeviceOperation, error) {
	row := q.db.QueryRow(ctx, createDeviceOperation,
		arg.WorkspaceID,
		arg.DeviceID,
		arg.OperationType,
		arg.RequestJson,
		arg.RequestedBy,
	)
	var i DeviceOperation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DeviceID,
		&i.OperationType,
		&i.Status,
		&i.RequestJson,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceCapabilities = `-- name: DeleteDeviceCapabilities :exec
DELETE FROM device_capabilities
WHERE device_id = $1
`

func (q *Queries) DeleteDeviceCapabilities(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeviceCapabilities, deviceID)
	return err
}

const getActiveDeviceAssignment = `-- name: GetActiveDeviceAssignment :one
WITH target AS (
    SELECT d.id FROM devices d WHERE d.id = $1
),
resolved AS (
    SELECT COALESCE(dr.parent_device_id, target.id) AS device_id
    FROM target
    LEFT JOIN device_relations dr
      ON dr.child_device_id = target.id
     AND dr.relation_type = 'gateway_node'
     AND dr.status = 'active'
)
SELECT da.id, da.device_id, da.workspace_id, da.project_id, da.site_id, da.status, da.assigned_by, da.assigned_at, da.unassigned_at, da.created_at, da.updated_at, da.assigned_by_type
FROM resolved
JOIN device_assignments da ON da.device_id = resolved.device_id
WHERE da.status = 'active'
ORDER BY assigned_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetActiveDeviceAssignment(ctx context.Context, id uuid.UUID) (DeviceAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveDeviceAssignment, id)
	var i DeviceAssignment
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.SiteID,
		&i.Status,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.UnassignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedByType,
	)
	return i, err
}

const getActiveDeviceAssignmentByDataStream = `-- name: GetActiveDeviceAssignmentByDataStream :one
(
SELECT da.id, da.device_id, da.workspace_id, da.project_id, da.site_id, da.status, da.assigned_by, da.assigned_at, da.unassigned_at, da.created_at, da.updated_at, da.assigned_by_type
FROM device_assignments AS da
JOIN data_streams AS ds ON ds.device_id = da.device_id
WHERE ds.id = $1
  AND da.status = 'active'
)
UNION ALL
(
SELECT da.id, da.device_id, da.workspace_id, da.project_id, da.site_id, da.status, da.assigned_by, da.assigned_at, da.unassigned_at, da.created_at, da.updated_at, da.assigned_by_type
FROM data_streams ds
JOIN device_relations dr
  ON dr.child_device_id = ds.device_id
 AND dr.relation_type = 'gateway_node'
 AND dr.status = 'active'
JOIN device_assignments da
  ON da.device_id = dr.parent_device_id
 AND da.status = 'active'
WHERE ds.id = $1
)
ORDER BY assigned_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetActiveDeviceAssignmentByDataStream(ctx context.Context, id uuid.UUID) (DeviceAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveDeviceAssignmentByDataStream, id)
	var i DeviceAssignment
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.SiteID,
		&i.Status,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.UnassignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedByType,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, product_id, serial_no, name, status, activated_at, created_at, updated_at, lifecycle_status, lifecycle_updated_at, device_type
FROM devices
WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SerialNo,
		&i.Name,
		&i.Status,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.LifecycleUpdatedAt,
		&i.DeviceType,
	)
	return i, err
}

const getDeviceWithActiveAssignment = `-- name: GetDeviceWithActiveAssignment :one
SELECT
    d.id,
    d.product_id,
    d.serial_no,
    d.name,
    d.status,
    d.activated_at,
    d.lifecycle_status,
    d.lifecycle_updated_at,
    d.device_type,
    d.created_at,
    d.updated_at,
    da.id AS assignment_id,
    da.workspace_id,
    da.project_id,
    da.site_id,
    da.assigned_by,
    da.assigned_at
FROM devices AS d
JOIN device_assignments AS da
  ON da.device_id = CASE
      WHEN d.device_type = 'gateway_node' THEN (
          SELECT dr.parent_device_id
          FROM device_relations dr
          WHERE dr.child_device_id = d.id
            AND dr.relation_type = 'gateway_node'
            AND dr.status = 'active'
          ORDER BY dr.synced_at DESC, dr.id DESC
          LIMIT 1
      )
      ELSE d.id
  END
 AND da.status = 'active'
WHERE d.id = $1
`

type GetDeviceWithActiveAssignmentRow struct {
	ID                 uuid.UUID          `json:"id"`
	ProductID          *string            `json:"product_id"`
	SerialNo           string             `json:"serial_no"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	LifecycleStatus    string             `json:"lifecycle_status"`
	LifecycleUpdatedAt pgtype.Timestamptz `json:"lifecycle_updated_at"`
	DeviceType         string             `json:"device_type"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	AssignmentID       uuid.UUID          `json:"assignment_id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	ProjectID          *uuid.UUID         `json:"project_id"`
	SiteID             *uuid.UUID         `json:"site_id"`
	AssignedBy         *uuid.UUID         `json:"assigned_by"`
	AssignedAt         pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) GetDeviceWithActiveAssignment(ctx context.Context, id uuid.UUID) (GetDeviceWithActiveAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getDeviceWithActiveAssignment, id)
	var i GetDeviceWithActiveAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SerialNo,
		&i.Name,
		&i.Status,
		&i.ActivatedAt,
		&i.LifecycleStatus,
		&i.LifecycleUpdatedAt,
		&i.DeviceType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.SiteID,
		&i.AssignedBy,
		&i.AssignedAt,
	)
	return i, err
}

const listDeviceCapabilities = `-- name: ListDeviceCapabilities :many
SELECT capability_code
FROM device_capabilities
WHERE device_id = $1
ORDER BY capability_code ASC
`

func (q *Queries) ListDeviceCapabilities(ctx context.Context, deviceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDeviceCapabilities, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var capability_code string
		if err := rows.Scan(&capability_code); err != nil {
			return nil, err
		}
		items = append(items, capability_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceLifecycleEvents = `-- name: ListDeviceLifecycleEvents :many
SELECT id, device_id, from_status, to_status, occurred_at, note, actor_user_id, created_at
FROM device_lifecycle_events
WHERE device_id = $1
ORDER BY occurred_at DESC, id DESC
`

func (q *Queries) ListDeviceLifecycleEvents(ctx context.Context, deviceID uuid.UUID) ([]DeviceLifecycleEvent, error) {
	rows, err := q.db.Query(ctx, listDeviceLifecycleEvents, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceLifecycleEvent{}
	for rows.Next() {
		var i DeviceLifecycleEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.FromStatus,
			&i.ToStatus,
			&i.OccurredAt,
			&i.Note,
			&i.ActorUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceOperationsByDevice = `-- name: ListDeviceOperationsByDevice :many
SELECT id, workspace_id, device_id, operation_type, status, request_json, requested_by, created_at, updated_at
FROM device_operations
WHERE device_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDeviceOperationsByDevice(ctx context.Context, deviceID uuid.UUID) ([]DeviceOperation, error) {
	rows, err := q.db.Query(ctx, listDeviceOperationsByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceOperation{}
	for rows.Next() {
		var i DeviceOperation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DeviceID,
			&i.OperationType,
			&i.Status,
			&i.RequestJson,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByProject = `-- name: ListDevicesByProject :many
SELECT
    d.id,
    d.product_id,
    d.serial_no,
    d.name,
    d.status,
    d.activated_at,
    d.lifecycle_status,
    d.lifecycle_updated_at,
    d.device_type,
    d.created_at,
    d.updated_at,
    da.id AS assignment_id,
    da.workspace_id,
    da.project_id,
    da.site_id,
    da.assigned_by,
    da.assigned_at,
    d.device_type AS topology_role,
    (
        SELECT count(*)::bigint
        FROM device_relations AS child_rel
        WHERE child_rel.parent_device_id = d.id
          AND child_rel.relation_type = 'gateway_node'
          AND child_rel.status = 'active'
    ) AS child_count
FROM devices AS d
JOIN device_assignments AS da ON da.device_id = d.id AND da.status = 'active'
WHERE da.workspace_id = $1
  AND da.project_id = $2
ORDER BY da.assigned_at DESC, d.created_at DESC, d.id DESC
`

type ListDevicesByProjectParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ProjectID   *uuid.UUID `json:"project_id"`
}

type ListDevicesByProjectRow struct {
	ID                 uuid.UUID          `json:"id"`
	ProductID          *string            `json:"product_id"`
	SerialNo           string             `json:"serial_no"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	LifecycleStatus    string             `json:"lifecycle_status"`
	LifecycleUpdatedAt pgtype.Timestamptz `json:"lifecycle_updated_at"`
	DeviceType         string             `json:"device_type"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	AssignmentID       uuid.UUID          `json:"assignment_id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	ProjectID          *uuid.UUID         `json:"project_id"`
	SiteID             *uuid.UUID         `json:"site_id"`
	AssignedBy         *uuid.UUID         `json:"assigned_by"`
	AssignedAt         pgtype.Timestamptz `json:"assigned_at"`
	TopologyRole       string             `json:"topology_role"`
	ChildCount         int64              `json:"child_count"`
}

func (q *Queries) ListDevicesByProject(ctx context.Context, arg ListDevicesByProjectParams) ([]ListDevicesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDevicesByProject, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesByProjectRow{}
	for rows.Next() {
		var i ListDevicesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SerialNo,
			&i.Name,
			&i.Status,
			&i.ActivatedAt,
			&i.LifecycleStatus,
			&i.LifecycleUpdatedAt,
			&i.DeviceType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignmentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.SiteID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.TopologyRole,
			&i.ChildCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesBySite = `-- name: ListDevicesBySite :many
SELECT
    d.id,
    d.product_id,
    d.serial_no,
    d.name,
    d.status,
    d.activated_at,
    d.lifecycle_status,
    d.lifecycle_updated_at,
    d.device_type,
    d.created_at,
    d.updated_at,
    da.id AS assignment_id,
    da.workspace_id,
    da.project_id,
    da.site_id,
    da.assigned_by,
    da.assigned_at,
    d.device_type AS topology_role,
    (
        SELECT count(*)::bigint
        FROM device_relations AS child_rel
        WHERE child_rel.parent_device_id = d.id
          AND child_rel.relation_type = 'gateway_node'
          AND child_rel.status = 'active'
    ) AS child_count
FROM devices AS d
JOIN device_assignments AS da ON da.device_id = d.id AND da.status = 'active'
WHERE da.workspace_id = $1
  AND da.site_id = $2
ORDER BY da.assigned_at DESC, d.created_at DESC, d.id DESC
`

type ListDevicesBySiteParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	SiteID      *uuid.UUID `json:"site_id"`
}

type ListDevicesBySiteRow struct {
	ID                 uuid.UUID          `json:"id"`
	ProductID          *string            `json:"product_id"`
	SerialNo           string             `json:"serial_no"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	LifecycleStatus    string             `json:"lifecycle_status"`
	LifecycleUpdatedAt pgtype.Timestamptz `json:"lifecycle_updated_at"`
	DeviceType         string             `json:"device_type"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	AssignmentID       uuid.UUID          `json:"assignment_id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	ProjectID          *uuid.UUID         `json:"project_id"`
	SiteID             *uuid.UUID         `json:"site_id"`
	AssignedBy         *uuid.UUID         `json:"assigned_by"`
	AssignedAt         pgtype.Timestamptz `json:"assigned_at"`
	TopologyRole       string             `json:"topology_role"`
	ChildCount         int64              `json:"child_count"`
}

func (q *Queries) ListDevicesBySite(ctx context.Context, arg ListDevicesBySiteParams) ([]ListDevicesBySiteRow, error) {
	rows, err := q.db.Query(ctx, listDevicesBySite, arg.WorkspaceID, arg.SiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesBySiteRow{}
	for rows.Next() {
		var i ListDevicesBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SerialNo,
			&i.Name,
			&i.Status,
			&i.ActivatedAt,
			&i.LifecycleStatus,
			&i.LifecycleUpdatedAt,
			&i.DeviceType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignmentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.SiteID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.TopologyRole,
			&i.ChildCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByWorkspace = `-- name: ListDevicesByWorkspace :many
SELECT
    d.id,
    d.product_id,
    d.serial_no,
    d.name,
    d.status,
    d.activated_at,
    d.lifecycle_status,
    d.lifecycle_updated_at,
    d.device_type,
    d.created_at,
    d.updated_at,
    da.id AS assignment_id,
    da.workspace_id,
    da.project_id,
    da.site_id,
    da.assigned_by,
    da.assigned_at,
    d.device_type AS topology_role,
    (
        SELECT count(*)::bigint
        FROM device_relations AS child_rel
        WHERE child_rel.parent_device_id = d.id
          AND child_rel.relation_type = 'gateway_node'
          AND child_rel.status = 'active'
    ) AS child_count
FROM devices AS d
JOIN device_assignments AS da ON da.device_id = d.id AND da.status = 'active'
WHERE da.workspace_id = $1
ORDER BY da.assigned_at DESC, d.created_at DESC, d.id DESC
`

type ListDevicesByWorkspaceRow struct {
	ID                 uuid.UUID          `json:"id"`
	ProductID          *string            `json:"product_id"`
	SerialNo           string             `json:"serial_no"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	LifecycleStatus    string             `json:"lifecycle_status"`
	LifecycleUpdatedAt pgtype.Timestamptz `json:"lifecycle_updated_at"`
	DeviceType         string             `json:"device_type"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	AssignmentID       uuid.UUID          `json:"assignment_id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	ProjectID          *uuid.UUID         `json:"project_id"`
	SiteID             *uuid.UUID         `json:"site_id"`
	AssignedBy         *uuid.UUID         `json:"assigned_by"`
	AssignedAt         pgtype.Timestamptz `json:"assigned_at"`
	TopologyRole       string             `json:"topology_role"`
	ChildCount         int64              `json:"child_count"`
}

func (q *Queries) ListDevicesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListDevicesByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listDevicesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesByWorkspaceRow{}
	for rows.Next() {
		var i ListDevicesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SerialNo,
			&i.Name,
			&i.Status,
			&i.ActivatedAt,
			&i.LifecycleStatus,
			&i.LifecycleUpdatedAt,
			&i.DeviceType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignmentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.SiteID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.TopologyRole,
			&i.ChildCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemDeviceAssets = `-- name: ListSystemDeviceAssets :many
SELECT
    d.id,
    d.product_id,
    d.serial_no,
    d.name,
    d.status,
    d.activated_at,
    d.lifecycle_status,
    d.lifecycle_updated_at,
    d.created_at,
    d.updated_at,
    da.id AS assignment_id,
    da.workspace_id,
    da.project_id,
    da.site_id,
    da.assigned_by,
    da.assigned_at,
    d.device_type AS topology_role,
    (
        SELECT count(*)::bigint
        FROM device_relations AS child_rel
        WHERE child_rel.parent_device_id = d.id
          AND child_rel.relation_type = 'gateway_node'
          AND child_rel.status = 'active'
    ) AS child_count
FROM devices AS d
LEFT JOIN device_assignments AS da ON da.device_id = d.id AND da.status = 'active'
ORDER BY d.created_at DESC, d.id DESC
`

type ListSystemDeviceAssetsRow struct {
	ID                 uuid.UUID          `json:"id"`
	ProductID          *string            `json:"product_id"`
	SerialNo           string             `json:"serial_no"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	LifecycleStatus    string             `json:"lifecycle_status"`
	LifecycleUpdatedAt pgtype.Timestamptz `json:"lifecycle_updated_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	AssignmentID       *uuid.UUID         `json:"assignment_id"`
	WorkspaceID        *uuid.UUID         `json:"workspace_id"`
	ProjectID          *uuid.UUID         `json:"project_id"`
	SiteID             *uuid.UUID         `json:"site_id"`
	AssignedBy         *uuid.UUID         `json:"assigned_by"`
	AssignedAt         pgtype.Timestamptz `json:"assigned_at"`
	TopologyRole       string             `json:"topology_role"`
	ChildCount         int64              `json:"child_count"`
}

func (q *Queries) ListSystemDeviceAssets(ctx context.Context) ([]ListSystemDeviceAssetsRow, error) {
	rows, err := q.db.Query(ctx, listSystemDeviceAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSystemDeviceAssetsRow{}
	for rows.Next() {
		var i ListSystemDeviceAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SerialNo,
			&i.Name,
			&i.Status,
			&i.ActivatedAt,
			&i.LifecycleStatus,
			&i.LifecycleUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignmentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.SiteID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.TopologyRole,
			&i.ChildCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET product_id = $2,
    name = $3,
    status = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, serial_no, name, status, activated_at, created_at, updated_at, lifecycle_status, lifecycle_updated_at, device_type
`

type UpdateDeviceParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID *string   `json:"product_id"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Status,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SerialNo,
		&i.Name,
		&i.Status,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.LifecycleUpdatedAt,
		&i.DeviceType,
	)
	return i, err
}

const updateDeviceAssignment = `-- name: UpdateDeviceAssignment :one
UPDATE device_assignments
SET project_id = $2,
    site_id = $3,
    updated_at = now()
WHERE id = $1
  AND status = 'active'
RETURNING id, device_id, workspace_id, project_id, site_id, status, assigned_by, assigned_at, unassigned_at, created_at, updated_at, assigned_by_type
`

type UpdateDeviceAssignmentParams struct {
	ID        uuid.UUID  `json:"id"`
	ProjectID *uuid.UUID `json:"project_id"`
	SiteID    *uuid.UUID `json:"site_id"`
}

func (q *Queries) UpdateDeviceAssignment(ctx context.Context, arg UpdateDeviceAssignmentParams) (DeviceAssignment, error) {
	row := q.db.QueryRow(ctx, updateDeviceAssignment, arg.ID, arg.ProjectID, arg.SiteID)
	var i DeviceAssignment
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.SiteID,
		&i.Status,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.UnassignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedByType,
	)
	return i, err
}

const updateDeviceLifecycle = `-- name: UpdateDeviceLifecycle :one
UPDATE devices
SET lifecycle_status = $2,
    lifecycle_updated_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, serial_no, name, status, activated_at, created_at, updated_at, lifecycle_status, lifecycle_updated_at, device_type
`

type UpdateDeviceLifecycleParams struct {
	ID                 uuid.UUID          `json:"id"`
	LifecycleStatus    string             `json:"lifecycle_status"`
	LifecycleUpdatedAt pgtype.Timestamptz `json:"lifecycle_updated_at"`
}

func (q *Queries) UpdateDeviceLifecycle(ctx context.Context, arg UpdateDeviceLifecycleParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceLifecycle, arg.ID, arg.LifecycleStatus, arg.LifecycleUpdatedAt)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SerialNo,
		&i.Name,
		&i.Status,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.LifecycleUpdatedAt,
		&i.DeviceType,
	)
	return i, err
}

const updateDeviceType = `-- name: UpdateDeviceType :one
UPDATE devices
SET device_type = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, serial_no, name, status, activated_at, created_at, updated_at, lifecycle_status, lifecycle_updated_at, device_type
`

type UpdateDeviceTypeParams struct {
	ID         uuid.UUID `json:"id"`
	DeviceType string    `json:"device_type"`
}

func (q *Queries) UpdateDeviceType(ctx context.Context, arg UpdateDeviceTypeParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceType, arg.ID, arg.DeviceType)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SerialNo,
		&i.Name,
		&i.Status,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.LifecycleUpdatedAt,
		&i.DeviceType,
	)
	return i, err
}
