// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addDeviceCapability = `-- name: AddDeviceCapability :one
INSERT INTO device_capabilities (device_id, capability_code)
VALUES ($1, $2)
ON CONFLICT (device_id, capability_code) DO NOTHING
RETURNING id, device_id, capability_code, created_at
`

type AddDeviceCapabilityParams struct {
	DeviceID       uuid.UUID `json:"device_id"`
	CapabilityCode string    `json:"capability_code"`
}

func (q *Queries) AddDeviceCapability(ctx context.Context, arg AddDeviceCapabilityParams) (DeviceCapability, error) {
	row := q.db.QueryRow(ctx, addDeviceCapability, arg.DeviceID, arg.CapabilityCode)
	var i DeviceCapability
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CapabilityCode,
		&i.CreatedAt,
	)
	return i, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    workspace_id,
    project_id,
    site_id,
    product_id,
    serial_no,
    name,
    status,
    activated_at,
    bound_by
)
VALUES ($1, $2, $3, $4, $5, $6, 'active', now(), $7)
RETURNING id, workspace_id, project_id, site_id, product_id, serial_no, name, status, activated_at, bound_by, created_at, updated_at
`

type CreateDeviceParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ProjectID   *uuid.UUID `json:"project_id"`
	SiteID      *uuid.UUID `json:"site_id"`
	ProductID   *string    `json:"product_id"`
	SerialNo    string     `json:"serial_no"`
	Name        string     `json:"name"`
	BoundBy     *uuid.UUID `json:"bound_by"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.SiteID,
		arg.ProductID,
		arg.SerialNo,
		arg.Name,
		arg.BoundBy,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.SiteID,
		&i.ProductID,
		&i.SerialNo,
		&i.Name,
		&i.Status,
		&i.ActivatedAt,
		&i.BoundBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeviceOperation = `-- name: CreateDeviceOperation :one
INSERT INTO device_operations (
    workspace_id,
    device_id,
    operation_type,
    request_json,
    requested_by
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, device_id, operation_type, status, request_json, requested_by, created_at, updated_at
`

type CreateDeviceOperationParams struct {
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	DeviceID      uuid.UUID `json:"device_id"`
	OperationType string    `json:"operation_type"`
	RequestJson   []byte    `json:"request_json"`
	RequestedBy   uuid.UUID `json:"requested_by"`
}

func (q *Queries) CreateDeviceOperation(ctx context.Context, arg CreateDeviceOperationParams) (DeviceOperation, error) {
	row := q.db.QueryRow(ctx, createDeviceOperation,
		arg.WorkspaceID,
		arg.DeviceID,
		arg.OperationType,
		arg.RequestJson,
		arg.RequestedBy,
	)
	var i DeviceOperation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DeviceID,
		&i.OperationType,
		&i.Status,
		&i.RequestJson,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceCapabilities = `-- name: DeleteDeviceCapabilities :exec
DELETE FROM device_capabilities
WHERE device_id = $1
`

func (q *Queries) DeleteDeviceCapabilities(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeviceCapabilities, deviceID)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, workspace_id, project_id, site_id, product_id, serial_no, name, status, activated_at, bound_by, created_at, updated_at
FROM devices
WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.SiteID,
		&i.ProductID,
		&i.SerialNo,
		&i.Name,
		&i.Status,
		&i.ActivatedAt,
		&i.BoundBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceCapabilities = `-- name: ListDeviceCapabilities :many
SELECT capability_code
FROM device_capabilities
WHERE device_id = $1
ORDER BY capability_code ASC
`

func (q *Queries) ListDeviceCapabilities(ctx context.Context, deviceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDeviceCapabilities, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var capability_code string
		if err := rows.Scan(&capability_code); err != nil {
			return nil, err
		}
		items = append(items, capability_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceOperationsByDevice = `-- name: ListDeviceOperationsByDevice :many
SELECT id, workspace_id, device_id, operation_type, status, request_json, requested_by, created_at, updated_at
FROM device_operations
WHERE device_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDeviceOperationsByDevice(ctx context.Context, deviceID uuid.UUID) ([]DeviceOperation, error) {
	rows, err := q.db.Query(ctx, listDeviceOperationsByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceOperation{}
	for rows.Next() {
		var i DeviceOperation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DeviceID,
			&i.OperationType,
			&i.Status,
			&i.RequestJson,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByProject = `-- name: ListDevicesByProject :many
SELECT id, workspace_id, project_id, site_id, product_id, serial_no, name, status, activated_at, bound_by, created_at, updated_at
FROM devices
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDevicesByProject(ctx context.Context, projectID *uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.SiteID,
			&i.ProductID,
			&i.SerialNo,
			&i.Name,
			&i.Status,
			&i.ActivatedAt,
			&i.BoundBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesBySite = `-- name: ListDevicesBySite :many
SELECT id, workspace_id, project_id, site_id, product_id, serial_no, name, status, activated_at, bound_by, created_at, updated_at
FROM devices
WHERE site_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDevicesBySite(ctx context.Context, siteID *uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.SiteID,
			&i.ProductID,
			&i.SerialNo,
			&i.Name,
			&i.Status,
			&i.ActivatedAt,
			&i.BoundBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByWorkspace = `-- name: ListDevicesByWorkspace :many
SELECT id, workspace_id, project_id, site_id, product_id, serial_no, name, status, activated_at, bound_by, created_at, updated_at
FROM devices
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDevicesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.SiteID,
			&i.ProductID,
			&i.SerialNo,
			&i.Name,
			&i.Status,
			&i.ActivatedAt,
			&i.BoundBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET project_id = $2,
    site_id = $3,
    product_id = $4,
    serial_no = $5,
    name = $6,
    status = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, project_id, site_id, product_id, serial_no, name, status, activated_at, bound_by, created_at, updated_at
`

type UpdateDeviceParams struct {
	ID        uuid.UUID  `json:"id"`
	ProjectID *uuid.UUID `json:"project_id"`
	SiteID    *uuid.UUID `json:"site_id"`
	ProductID *string    `json:"product_id"`
	SerialNo  string     `json:"serial_no"`
	Name      string     `json:"name"`
	Status    string     `json:"status"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.ProjectID,
		arg.SiteID,
		arg.ProductID,
		arg.SerialNo,
		arg.Name,
		arg.Status,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.SiteID,
		&i.ProductID,
		&i.SerialNo,
		&i.Name,
		&i.Status,
		&i.ActivatedAt,
		&i.BoundBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
