// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_source.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveTHCPNDeviceSourceRefByDevice = `-- name: GetActiveTHCPNDeviceSourceRefByDevice :one
SELECT id, device_id, data_source_id, adapter_code, external_key::bigint AS external_device_id, status, synced_at, created_at, updated_at
FROM device_source_refs
WHERE device_id = $1
  AND adapter_code = 'thcpn_legacy_mysql'
  AND status = 'active'
`

type GetActiveTHCPNDeviceSourceRefByDeviceRow struct {
	ID               uuid.UUID          `json:"id"`
	DeviceID         uuid.UUID          `json:"device_id"`
	DataSourceID     uuid.UUID          `json:"data_source_id"`
	AdapterCode      string             `json:"adapter_code"`
	ExternalDeviceID int64              `json:"external_device_id"`
	Status           string             `json:"status"`
	SyncedAt         pgtype.Timestamptz `json:"synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveTHCPNDeviceSourceRefByDevice(ctx context.Context, deviceID uuid.UUID) (GetActiveTHCPNDeviceSourceRefByDeviceRow, error) {
	row := q.db.QueryRow(ctx, getActiveTHCPNDeviceSourceRefByDevice, deviceID)
	var i GetActiveTHCPNDeviceSourceRefByDeviceRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.Status,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceConfigSnapshotByExternalConfig = `-- name: GetDeviceConfigSnapshotByExternalConfig :one
SELECT id, device_id, data_source_id, adapter_code, external_device_id, external_config_id, version, data_json, image_json, control_json, source_created_at, source_updated_at, synced_at, created_at
FROM device_config_snapshots
WHERE data_source_id = $1
  AND adapter_code = $2
  AND external_config_id = $3
`

type GetDeviceConfigSnapshotByExternalConfigParams struct {
	DataSourceID     uuid.UUID `json:"data_source_id"`
	AdapterCode      string    `json:"adapter_code"`
	ExternalConfigID int64     `json:"external_config_id"`
}

func (q *Queries) GetDeviceConfigSnapshotByExternalConfig(ctx context.Context, arg GetDeviceConfigSnapshotByExternalConfigParams) (DeviceConfigSnapshot, error) {
	row := q.db.QueryRow(ctx, getDeviceConfigSnapshotByExternalConfig, arg.DataSourceID, arg.AdapterCode, arg.ExternalConfigID)
	var i DeviceConfigSnapshot
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.ExternalConfigID,
		&i.Version,
		&i.DataJson,
		&i.ImageJson,
		&i.ControlJson,
		&i.SourceCreatedAt,
		&i.SourceUpdatedAt,
		&i.SyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestDeviceConfigSnapshotByDevice = `-- name: GetLatestDeviceConfigSnapshotByDevice :one
SELECT id, device_id, data_source_id, adapter_code, external_device_id, external_config_id, version, data_json, image_json, control_json, source_created_at, source_updated_at, synced_at, created_at
FROM device_config_snapshots
WHERE device_id = $1
ORDER BY synced_at DESC, external_config_id DESC
LIMIT 1
`

func (q *Queries) GetLatestDeviceConfigSnapshotByDevice(ctx context.Context, deviceID uuid.UUID) (DeviceConfigSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestDeviceConfigSnapshotByDevice, deviceID)
	var i DeviceConfigSnapshot
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.ExternalConfigID,
		&i.Version,
		&i.DataJson,
		&i.ImageJson,
		&i.ControlJson,
		&i.SourceCreatedAt,
		&i.SourceUpdatedAt,
		&i.SyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNumericDeviceSourceRefByDevice = `-- name: GetNumericDeviceSourceRefByDevice :one
SELECT id, device_id, data_source_id, adapter_code, external_key::bigint AS external_device_id, status, synced_at, created_at, updated_at
FROM device_source_refs
WHERE device_id = $1
  AND adapter_code IN ('thcpn_legacy_mysql', 'thcpn_legacy_camera', 'carbon_sink_mysql')
  AND status = 'active'
`

type GetNumericDeviceSourceRefByDeviceRow struct {
	ID               uuid.UUID          `json:"id"`
	DeviceID         uuid.UUID          `json:"device_id"`
	DataSourceID     uuid.UUID          `json:"data_source_id"`
	AdapterCode      string             `json:"adapter_code"`
	ExternalDeviceID int64              `json:"external_device_id"`
	Status           string             `json:"status"`
	SyncedAt         pgtype.Timestamptz `json:"synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNumericDeviceSourceRefByDevice(ctx context.Context, deviceID uuid.UUID) (GetNumericDeviceSourceRefByDeviceRow, error) {
	row := q.db.QueryRow(ctx, getNumericDeviceSourceRefByDevice, deviceID)
	var i GetNumericDeviceSourceRefByDeviceRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.Status,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNumericDeviceSourceRefByExternal = `-- name: GetNumericDeviceSourceRefByExternal :one
SELECT id, device_id, data_source_id, adapter_code, external_key::bigint AS external_device_id, status, synced_at, created_at, updated_at
FROM device_source_refs
WHERE data_source_id = $1
  AND adapter_code = $2
  AND external_key = $3::bigint::text
`

type GetNumericDeviceSourceRefByExternalParams struct {
	DataSourceID     uuid.UUID `json:"data_source_id"`
	AdapterCode      string    `json:"adapter_code"`
	ExternalDeviceID int64     `json:"external_device_id"`
}

type GetNumericDeviceSourceRefByExternalRow struct {
	ID               uuid.UUID          `json:"id"`
	DeviceID         uuid.UUID          `json:"device_id"`
	DataSourceID     uuid.UUID          `json:"data_source_id"`
	AdapterCode      string             `json:"adapter_code"`
	ExternalDeviceID int64              `json:"external_device_id"`
	Status           string             `json:"status"`
	SyncedAt         pgtype.Timestamptz `json:"synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNumericDeviceSourceRefByExternal(ctx context.Context, arg GetNumericDeviceSourceRefByExternalParams) (GetNumericDeviceSourceRefByExternalRow, error) {
	row := q.db.QueryRow(ctx, getNumericDeviceSourceRefByExternal, arg.DataSourceID, arg.AdapterCode, arg.ExternalDeviceID)
	var i GetNumericDeviceSourceRefByExternalRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.Status,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceConfigSnapshotsByDevice = `-- name: ListDeviceConfigSnapshotsByDevice :many
SELECT id, device_id, data_source_id, adapter_code, external_device_id, external_config_id, version, data_json, image_json, control_json, source_created_at, source_updated_at, synced_at, created_at
FROM device_config_snapshots
WHERE device_id = $1
ORDER BY synced_at DESC, external_config_id DESC
`

func (q *Queries) ListDeviceConfigSnapshotsByDevice(ctx context.Context, deviceID uuid.UUID) ([]DeviceConfigSnapshot, error) {
	rows, err := q.db.Query(ctx, listDeviceConfigSnapshotsByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceConfigSnapshot{}
	for rows.Next() {
		var i DeviceConfigSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.DataSourceID,
			&i.AdapterCode,
			&i.ExternalDeviceID,
			&i.ExternalConfigID,
			&i.Version,
			&i.DataJson,
			&i.ImageJson,
			&i.ControlJson,
			&i.SourceCreatedAt,
			&i.SourceUpdatedAt,
			&i.SyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceConfigSnapshot = `-- name: UpsertDeviceConfigSnapshot :one
INSERT INTO device_config_snapshots (
    device_id,
    data_source_id,
    adapter_code,
    external_device_id,
    external_config_id,
    version,
    data_json,
    image_json,
    control_json,
    source_created_at,
    source_updated_at,
    synced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
ON CONFLICT (data_source_id, adapter_code, external_config_id)
DO UPDATE SET
    device_id = EXCLUDED.device_id,
    external_device_id = EXCLUDED.external_device_id,
    version = EXCLUDED.version,
    data_json = EXCLUDED.data_json,
    image_json = EXCLUDED.image_json,
    control_json = EXCLUDED.control_json,
    source_created_at = EXCLUDED.source_created_at,
    source_updated_at = EXCLUDED.source_updated_at,
    synced_at = now()
RETURNING id, device_id, data_source_id, adapter_code, external_device_id, external_config_id, version, data_json, image_json, control_json, source_created_at, source_updated_at, synced_at, created_at
`

type UpsertDeviceConfigSnapshotParams struct {
	DeviceID         uuid.UUID          `json:"device_id"`
	DataSourceID     uuid.UUID          `json:"data_source_id"`
	AdapterCode      string             `json:"adapter_code"`
	ExternalDeviceID int64              `json:"external_device_id"`
	ExternalConfigID int64              `json:"external_config_id"`
	Version          *string            `json:"version"`
	DataJson         []byte             `json:"data_json"`
	ImageJson        []byte             `json:"image_json"`
	ControlJson      []byte             `json:"control_json"`
	SourceCreatedAt  pgtype.Timestamptz `json:"source_created_at"`
	SourceUpdatedAt  pgtype.Timestamptz `json:"source_updated_at"`
}

func (q *Queries) UpsertDeviceConfigSnapshot(ctx context.Context, arg UpsertDeviceConfigSnapshotParams) (DeviceConfigSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertDeviceConfigSnapshot,
		arg.DeviceID,
		arg.DataSourceID,
		arg.AdapterCode,
		arg.ExternalDeviceID,
		arg.ExternalConfigID,
		arg.Version,
		arg.DataJson,
		arg.ImageJson,
		arg.ControlJson,
		arg.SourceCreatedAt,
		arg.SourceUpdatedAt,
	)
	var i DeviceConfigSnapshot
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.ExternalConfigID,
		&i.Version,
		&i.DataJson,
		&i.ImageJson,
		&i.ControlJson,
		&i.SourceCreatedAt,
		&i.SourceUpdatedAt,
		&i.SyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertNumericDeviceSourceRef = `-- name: UpsertNumericDeviceSourceRef :one
INSERT INTO device_source_refs (
    device_id,
    data_source_id,
    adapter_code,
    external_key,
    status,
    synced_at
)
VALUES ($1, $2, $3, $4::bigint::text, 'active', now())
ON CONFLICT (data_source_id, adapter_code, external_key)
DO UPDATE SET
    device_id = EXCLUDED.device_id,
    status = 'active',
    synced_at = now(),
    updated_at = now()
RETURNING id, device_id, data_source_id, adapter_code, external_key::bigint AS external_device_id, status, synced_at, created_at, updated_at
`

type UpsertNumericDeviceSourceRefParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	DataSourceID     uuid.UUID `json:"data_source_id"`
	AdapterCode      string    `json:"adapter_code"`
	ExternalDeviceID int64     `json:"external_device_id"`
}

type UpsertNumericDeviceSourceRefRow struct {
	ID               uuid.UUID          `json:"id"`
	DeviceID         uuid.UUID          `json:"device_id"`
	DataSourceID     uuid.UUID          `json:"data_source_id"`
	AdapterCode      string             `json:"adapter_code"`
	ExternalDeviceID int64              `json:"external_device_id"`
	Status           string             `json:"status"`
	SyncedAt         pgtype.Timestamptz `json:"synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertNumericDeviceSourceRef(ctx context.Context, arg UpsertNumericDeviceSourceRefParams) (UpsertNumericDeviceSourceRefRow, error) {
	row := q.db.QueryRow(ctx, upsertNumericDeviceSourceRef,
		arg.DeviceID,
		arg.DataSourceID,
		arg.AdapterCode,
		arg.ExternalDeviceID,
	)
	var i UpsertNumericDeviceSourceRefRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.Status,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
