// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_capability_definition.sql

package sqlc

import (
	"context"
)

const createDeviceCapabilityDefinition = `-- name: CreateDeviceCapabilityDefinition :one
INSERT INTO device_capability_definitions (code, name, status, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING code, name, status, sort_order, created_at, updated_at
`

type CreateDeviceCapabilityDefinitionParams struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	Status    string `json:"status"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateDeviceCapabilityDefinition(ctx context.Context, arg CreateDeviceCapabilityDefinitionParams) (DeviceCapabilityDefinition, error) {
	row := q.db.QueryRow(ctx, createDeviceCapabilityDefinition,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.SortOrder,
	)
	var i DeviceCapabilityDefinition
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceCapabilityDefinitions = `-- name: ListDeviceCapabilityDefinitions :many
SELECT code, name, status, sort_order, created_at, updated_at
FROM device_capability_definitions
ORDER BY sort_order ASC, code ASC
`

func (q *Queries) ListDeviceCapabilityDefinitions(ctx context.Context) ([]DeviceCapabilityDefinition, error) {
	rows, err := q.db.Query(ctx, listDeviceCapabilityDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceCapabilityDefinition{}
	for rows.Next() {
		var i DeviceCapabilityDefinition
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceCapabilityDefinitionsByCodes = `-- name: ListDeviceCapabilityDefinitionsByCodes :many
SELECT code, name, status, sort_order, created_at, updated_at
FROM device_capability_definitions
WHERE code = ANY($1::text[])
ORDER BY sort_order ASC, code ASC
`

func (q *Queries) ListDeviceCapabilityDefinitionsByCodes(ctx context.Context, codes []string) ([]DeviceCapabilityDefinition, error) {
	rows, err := q.db.Query(ctx, listDeviceCapabilityDefinitionsByCodes, codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceCapabilityDefinition{}
	for rows.Next() {
		var i DeviceCapabilityDefinition
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceCapabilityDefinition = `-- name: UpdateDeviceCapabilityDefinition :one
UPDATE device_capability_definitions
SET name = $2,
    status = $3,
    sort_order = $4,
    updated_at = now()
WHERE code = $1
RETURNING code, name, status, sort_order, created_at, updated_at
`

type UpdateDeviceCapabilityDefinitionParams struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	Status    string `json:"status"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) UpdateDeviceCapabilityDefinition(ctx context.Context, arg UpdateDeviceCapabilityDefinitionParams) (DeviceCapabilityDefinition, error) {
	row := q.db.QueryRow(ctx, updateDeviceCapabilityDefinition,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.SortOrder,
	)
	var i DeviceCapabilityDefinition
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
