// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_source.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDeviceConfigSnapshotByExternalConfig = `-- name: GetDeviceConfigSnapshotByExternalConfig :one
SELECT id, device_id, data_source_id, adapter_code, external_device_id, external_config_id, version, data_json, image_json, control_json, source_created_at, source_updated_at, synced_at, created_at
FROM device_config_snapshots
WHERE data_source_id = $1
  AND adapter_code = $2
  AND external_config_id = $3
`

type GetDeviceConfigSnapshotByExternalConfigParams struct {
	DataSourceID     uuid.UUID `json:"data_source_id"`
	AdapterCode      string    `json:"adapter_code"`
	ExternalConfigID int64     `json:"external_config_id"`
}

func (q *Queries) GetDeviceConfigSnapshotByExternalConfig(ctx context.Context, arg GetDeviceConfigSnapshotByExternalConfigParams) (DeviceConfigSnapshot, error) {
	row := q.db.QueryRow(ctx, getDeviceConfigSnapshotByExternalConfig, arg.DataSourceID, arg.AdapterCode, arg.ExternalConfigID)
	var i DeviceConfigSnapshot
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.ExternalConfigID,
		&i.Version,
		&i.DataJson,
		&i.ImageJson,
		&i.ControlJson,
		&i.SourceCreatedAt,
		&i.SourceUpdatedAt,
		&i.SyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceSourceRefByDevice = `-- name: GetDeviceSourceRefByDevice :one
SELECT id, device_id, data_source_id, adapter_code, external_device_id, external_sn, external_uuid, external_device_type, status, synced_at, created_at, updated_at
FROM device_source_refs
WHERE device_id = $1
  AND status = 'active'
ORDER BY synced_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetDeviceSourceRefByDevice(ctx context.Context, deviceID uuid.UUID) (DeviceSourceRef, error) {
	row := q.db.QueryRow(ctx, getDeviceSourceRefByDevice, deviceID)
	var i DeviceSourceRef
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.ExternalSn,
		&i.ExternalUuid,
		&i.ExternalDeviceType,
		&i.Status,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceSourceRefByExternal = `-- name: GetDeviceSourceRefByExternal :one
SELECT id, device_id, data_source_id, adapter_code, external_device_id, external_sn, external_uuid, external_device_type, status, synced_at, created_at, updated_at
FROM device_source_refs
WHERE data_source_id = $1
  AND adapter_code = $2
  AND external_device_id = $3
`

type GetDeviceSourceRefByExternalParams struct {
	DataSourceID     uuid.UUID `json:"data_source_id"`
	AdapterCode      string    `json:"adapter_code"`
	ExternalDeviceID int64     `json:"external_device_id"`
}

func (q *Queries) GetDeviceSourceRefByExternal(ctx context.Context, arg GetDeviceSourceRefByExternalParams) (DeviceSourceRef, error) {
	row := q.db.QueryRow(ctx, getDeviceSourceRefByExternal, arg.DataSourceID, arg.AdapterCode, arg.ExternalDeviceID)
	var i DeviceSourceRef
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.ExternalSn,
		&i.ExternalUuid,
		&i.ExternalDeviceType,
		&i.Status,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceConfigSnapshotsByDevice = `-- name: ListDeviceConfigSnapshotsByDevice :many
SELECT id, device_id, data_source_id, adapter_code, external_device_id, external_config_id, version, data_json, image_json, control_json, source_created_at, source_updated_at, synced_at, created_at
FROM device_config_snapshots
WHERE device_id = $1
ORDER BY synced_at DESC, external_config_id DESC
`

func (q *Queries) ListDeviceConfigSnapshotsByDevice(ctx context.Context, deviceID uuid.UUID) ([]DeviceConfigSnapshot, error) {
	rows, err := q.db.Query(ctx, listDeviceConfigSnapshotsByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceConfigSnapshot{}
	for rows.Next() {
		var i DeviceConfigSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.DataSourceID,
			&i.AdapterCode,
			&i.ExternalDeviceID,
			&i.ExternalConfigID,
			&i.Version,
			&i.DataJson,
			&i.ImageJson,
			&i.ControlJson,
			&i.SourceCreatedAt,
			&i.SourceUpdatedAt,
			&i.SyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceConfigSnapshot = `-- name: UpsertDeviceConfigSnapshot :one
INSERT INTO device_config_snapshots (
    device_id,
    data_source_id,
    adapter_code,
    external_device_id,
    external_config_id,
    version,
    data_json,
    image_json,
    control_json,
    source_created_at,
    source_updated_at,
    synced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
ON CONFLICT (data_source_id, adapter_code, external_config_id)
DO UPDATE SET
    device_id = EXCLUDED.device_id,
    external_device_id = EXCLUDED.external_device_id,
    version = EXCLUDED.version,
    data_json = EXCLUDED.data_json,
    image_json = EXCLUDED.image_json,
    control_json = EXCLUDED.control_json,
    source_created_at = EXCLUDED.source_created_at,
    source_updated_at = EXCLUDED.source_updated_at,
    synced_at = now()
RETURNING id, device_id, data_source_id, adapter_code, external_device_id, external_config_id, version, data_json, image_json, control_json, source_created_at, source_updated_at, synced_at, created_at
`

type UpsertDeviceConfigSnapshotParams struct {
	DeviceID         uuid.UUID          `json:"device_id"`
	DataSourceID     uuid.UUID          `json:"data_source_id"`
	AdapterCode      string             `json:"adapter_code"`
	ExternalDeviceID int64              `json:"external_device_id"`
	ExternalConfigID int64              `json:"external_config_id"`
	Version          *string            `json:"version"`
	DataJson         []byte             `json:"data_json"`
	ImageJson        []byte             `json:"image_json"`
	ControlJson      []byte             `json:"control_json"`
	SourceCreatedAt  pgtype.Timestamptz `json:"source_created_at"`
	SourceUpdatedAt  pgtype.Timestamptz `json:"source_updated_at"`
}

func (q *Queries) UpsertDeviceConfigSnapshot(ctx context.Context, arg UpsertDeviceConfigSnapshotParams) (DeviceConfigSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertDeviceConfigSnapshot,
		arg.DeviceID,
		arg.DataSourceID,
		arg.AdapterCode,
		arg.ExternalDeviceID,
		arg.ExternalConfigID,
		arg.Version,
		arg.DataJson,
		arg.ImageJson,
		arg.ControlJson,
		arg.SourceCreatedAt,
		arg.SourceUpdatedAt,
	)
	var i DeviceConfigSnapshot
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.ExternalConfigID,
		&i.Version,
		&i.DataJson,
		&i.ImageJson,
		&i.ControlJson,
		&i.SourceCreatedAt,
		&i.SourceUpdatedAt,
		&i.SyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDeviceSourceRef = `-- name: UpsertDeviceSourceRef :one
INSERT INTO device_source_refs (
    device_id,
    data_source_id,
    adapter_code,
    external_device_id,
    external_sn,
    external_uuid,
    external_device_type,
    status,
    synced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'active', now())
ON CONFLICT (data_source_id, adapter_code, external_device_id)
DO UPDATE SET
    device_id = EXCLUDED.device_id,
    external_sn = EXCLUDED.external_sn,
    external_uuid = EXCLUDED.external_uuid,
    external_device_type = EXCLUDED.external_device_type,
    status = 'active',
    synced_at = now(),
    updated_at = now()
RETURNING id, device_id, data_source_id, adapter_code, external_device_id, external_sn, external_uuid, external_device_type, status, synced_at, created_at, updated_at
`

type UpsertDeviceSourceRefParams struct {
	DeviceID           uuid.UUID `json:"device_id"`
	DataSourceID       uuid.UUID `json:"data_source_id"`
	AdapterCode        string    `json:"adapter_code"`
	ExternalDeviceID   int64     `json:"external_device_id"`
	ExternalSn         *string   `json:"external_sn"`
	ExternalUuid       *string   `json:"external_uuid"`
	ExternalDeviceType *string   `json:"external_device_type"`
}

func (q *Queries) UpsertDeviceSourceRef(ctx context.Context, arg UpsertDeviceSourceRefParams) (DeviceSourceRef, error) {
	row := q.db.QueryRow(ctx, upsertDeviceSourceRef,
		arg.DeviceID,
		arg.DataSourceID,
		arg.AdapterCode,
		arg.ExternalDeviceID,
		arg.ExternalSn,
		arg.ExternalUuid,
		arg.ExternalDeviceType,
	)
	var i DeviceSourceRef
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DataSourceID,
		&i.AdapterCode,
		&i.ExternalDeviceID,
		&i.ExternalSn,
		&i.ExternalUuid,
		&i.ExternalDeviceType,
		&i.Status,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
