// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_profile.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearDeviceProfileImageCover = `-- name: ClearDeviceProfileImageCover :exec
UPDATE device_profile_images
SET is_cover = false,
    updated_at = now()
WHERE device_id = $1 AND is_cover = true
`

func (q *Queries) ClearDeviceProfileImageCover(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDeviceProfileImageCover, deviceID)
	return err
}

const countDeviceProfileImages = `-- name: CountDeviceProfileImages :one
SELECT count(*)
FROM device_profile_images
WHERE device_id = $1
`

func (q *Queries) CountDeviceProfileImages(ctx context.Context, deviceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDeviceProfileImages, deviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeviceProfileImage = `-- name: CreateDeviceProfileImage :one
INSERT INTO device_profile_images (
    device_id, object_key, original_filename, content_type, size_bytes,
    width, height, caption, sort_order, is_cover, uploaded_by, source_url
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, device_id, object_key, original_filename, content_type, size_bytes, width, height, caption, sort_order, is_cover, uploaded_by, created_at, updated_at, source_url
`

type CreateDeviceProfileImageParams struct {
	DeviceID         uuid.UUID   `json:"device_id"`
	ObjectKey        string      `json:"object_key"`
	OriginalFilename string      `json:"original_filename"`
	ContentType      string      `json:"content_type"`
	SizeBytes        int64       `json:"size_bytes"`
	Width            pgtype.Int4 `json:"width"`
	Height           pgtype.Int4 `json:"height"`
	Caption          *string     `json:"caption"`
	SortOrder        int32       `json:"sort_order"`
	IsCover          bool        `json:"is_cover"`
	UploadedBy       *uuid.UUID  `json:"uploaded_by"`
	SourceUrl        *string     `json:"source_url"`
}

func (q *Queries) CreateDeviceProfileImage(ctx context.Context, arg CreateDeviceProfileImageParams) (DeviceProfileImage, error) {
	row := q.db.QueryRow(ctx, createDeviceProfileImage,
		arg.DeviceID,
		arg.ObjectKey,
		arg.OriginalFilename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.Caption,
		arg.SortOrder,
		arg.IsCover,
		arg.UploadedBy,
		arg.SourceUrl,
	)
	var i DeviceProfileImage
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Caption,
		&i.SortOrder,
		&i.IsCover,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
	)
	return i, err
}

const deleteDeviceProfileImage = `-- name: DeleteDeviceProfileImage :one
DELETE FROM device_profile_images
WHERE id = $1 AND device_id = $2
RETURNING id, device_id, object_key, original_filename, content_type, size_bytes, width, height, caption, sort_order, is_cover, uploaded_by, created_at, updated_at, source_url
`

type DeleteDeviceProfileImageParams struct {
	ID       uuid.UUID `json:"id"`
	DeviceID uuid.UUID `json:"device_id"`
}

func (q *Queries) DeleteDeviceProfileImage(ctx context.Context, arg DeleteDeviceProfileImageParams) (DeviceProfileImage, error) {
	row := q.db.QueryRow(ctx, deleteDeviceProfileImage, arg.ID, arg.DeviceID)
	var i DeviceProfileImage
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Caption,
		&i.SortOrder,
		&i.IsCover,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
	)
	return i, err
}

const getDeviceProfile = `-- name: GetDeviceProfile :one
SELECT device_id, description, location_text, updated_by, created_at, updated_at
FROM device_profiles
WHERE device_id = $1
`

func (q *Queries) GetDeviceProfile(ctx context.Context, deviceID uuid.UUID) (DeviceProfile, error) {
	row := q.db.QueryRow(ctx, getDeviceProfile, deviceID)
	var i DeviceProfile
	err := row.Scan(
		&i.DeviceID,
		&i.Description,
		&i.LocationText,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceProfileImage = `-- name: GetDeviceProfileImage :one
SELECT id, device_id, object_key, original_filename, content_type, size_bytes, width, height, caption, sort_order, is_cover, uploaded_by, created_at, updated_at, source_url
FROM device_profile_images
WHERE id = $1 AND device_id = $2
`

type GetDeviceProfileImageParams struct {
	ID       uuid.UUID `json:"id"`
	DeviceID uuid.UUID `json:"device_id"`
}

func (q *Queries) GetDeviceProfileImage(ctx context.Context, arg GetDeviceProfileImageParams) (DeviceProfileImage, error) {
	row := q.db.QueryRow(ctx, getDeviceProfileImage, arg.ID, arg.DeviceID)
	var i DeviceProfileImage
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Caption,
		&i.SortOrder,
		&i.IsCover,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
	)
	return i, err
}

const getDeviceProfileSite = `-- name: GetDeviceProfileSite :one
SELECT s.id, s.name, s.location_text, s.latitude, s.longitude
FROM device_assignments da
JOIN sites s ON s.id = da.site_id
WHERE da.device_id = $1
  AND da.status = 'active'
`

type GetDeviceProfileSiteRow struct {
	ID           uuid.UUID     `json:"id"`
	Name         string        `json:"name"`
	LocationText *string       `json:"location_text"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
}

func (q *Queries) GetDeviceProfileSite(ctx context.Context, deviceID uuid.UUID) (GetDeviceProfileSiteRow, error) {
	row := q.db.QueryRow(ctx, getDeviceProfileSite, deviceID)
	var i GetDeviceProfileSiteRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationText,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const listDeviceProfileImages = `-- name: ListDeviceProfileImages :many
SELECT id, device_id, object_key, original_filename, content_type, size_bytes, width, height, caption, sort_order, is_cover, uploaded_by, created_at, updated_at, source_url
FROM device_profile_images
WHERE device_id = $1
ORDER BY sort_order, created_at, id
`

func (q *Queries) ListDeviceProfileImages(ctx context.Context, deviceID uuid.UUID) ([]DeviceProfileImage, error) {
	rows, err := q.db.Query(ctx, listDeviceProfileImages, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceProfileImage{}
	for rows.Next() {
		var i DeviceProfileImage
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.ObjectKey,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Caption,
			&i.SortOrder,
			&i.IsCover,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeviceProfileUploads = `-- name: LockDeviceProfileUploads :one
SELECT id
FROM devices
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockDeviceProfileUploads(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockDeviceProfileUploads, id)
	err := row.Scan(&id)
	return id, err
}

const promoteFirstDeviceProfileImageCover = `-- name: PromoteFirstDeviceProfileImageCover :exec
UPDATE device_profile_images
SET is_cover = true,
    updated_at = now()
WHERE id = (
    SELECT dpi.id
    FROM device_profile_images dpi
    WHERE dpi.device_id = $1
    ORDER BY dpi.sort_order, dpi.created_at, dpi.id
    LIMIT 1
)
`

func (q *Queries) PromoteFirstDeviceProfileImageCover(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, promoteFirstDeviceProfileImageCover, deviceID)
	return err
}

const setDeviceProfileImageOrder = `-- name: SetDeviceProfileImageOrder :exec
UPDATE device_profile_images
SET sort_order = $3,
    updated_at = now()
WHERE id = $1 AND device_id = $2
`

type SetDeviceProfileImageOrderParams struct {
	ID        uuid.UUID `json:"id"`
	DeviceID  uuid.UUID `json:"device_id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) SetDeviceProfileImageOrder(ctx context.Context, arg SetDeviceProfileImageOrderParams) error {
	_, err := q.db.Exec(ctx, setDeviceProfileImageOrder, arg.ID, arg.DeviceID, arg.SortOrder)
	return err
}

const updateDeviceProfileImage = `-- name: UpdateDeviceProfileImage :one
UPDATE device_profile_images
SET caption = $3,
    is_cover = $4,
    updated_at = now()
WHERE id = $1 AND device_id = $2
RETURNING id, device_id, object_key, original_filename, content_type, size_bytes, width, height, caption, sort_order, is_cover, uploaded_by, created_at, updated_at, source_url
`

type UpdateDeviceProfileImageParams struct {
	ID       uuid.UUID `json:"id"`
	DeviceID uuid.UUID `json:"device_id"`
	Caption  *string   `json:"caption"`
	IsCover  bool      `json:"is_cover"`
}

func (q *Queries) UpdateDeviceProfileImage(ctx context.Context, arg UpdateDeviceProfileImageParams) (DeviceProfileImage, error) {
	row := q.db.QueryRow(ctx, updateDeviceProfileImage,
		arg.ID,
		arg.DeviceID,
		arg.Caption,
		arg.IsCover,
	)
	var i DeviceProfileImage
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Caption,
		&i.SortOrder,
		&i.IsCover,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
	)
	return i, err
}

const upsertDeviceProfile = `-- name: UpsertDeviceProfile :one
INSERT INTO device_profiles (device_id, description, location_text, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (device_id) DO UPDATE
SET description = EXCLUDED.description,
    location_text = EXCLUDED.location_text,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING device_id, description, location_text, updated_by, created_at, updated_at
`

type UpsertDeviceProfileParams struct {
	DeviceID     uuid.UUID  `json:"device_id"`
	Description  *string    `json:"description"`
	LocationText *string    `json:"location_text"`
	UpdatedBy    *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpsertDeviceProfile(ctx context.Context, arg UpsertDeviceProfileParams) (DeviceProfile, error) {
	row := q.db.QueryRow(ctx, upsertDeviceProfile,
		arg.DeviceID,
		arg.Description,
		arg.LocationText,
		arg.UpdatedBy,
	)
	var i DeviceProfile
	err := row.Scan(
		&i.DeviceID,
		&i.Description,
		&i.LocationText,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
