// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_relation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveDeviceChildren = `-- name: ListActiveDeviceChildren :many
SELECT
    dr.id,
    dr.parent_device_id,
    dr.child_device_id,
    dr.relation_type,
    dr.data_source_id,
    dr.external_parent_device_id,
    dr.external_child_device_id,
    dr.status,
    dr.synced_at,
    dr.created_at,
    dr.updated_at,
    d.id AS device_id,
    d.product_id,
    d.serial_no,
    d.name,
    d.status AS device_status,
    d.activated_at,
    d.lifecycle_status,
    d.lifecycle_updated_at,
    d.device_type,
    d.created_at AS device_created_at,
    d.updated_at AS device_updated_at,
    da.id AS assignment_id,
    da.workspace_id,
    da.project_id,
    da.site_id,
    da.assigned_by,
    da.assigned_at
FROM device_relations AS dr
JOIN devices AS d ON d.id = dr.child_device_id
LEFT JOIN device_assignments AS da ON da.device_id = d.id AND da.status = 'active'
WHERE dr.parent_device_id = $1
  AND dr.relation_type = 'gateway_node'
  AND dr.status = 'active'
ORDER BY d.name ASC, d.serial_no ASC, dr.id ASC
`

type ListActiveDeviceChildrenRow struct {
	ID                     uuid.UUID          `json:"id"`
	ParentDeviceID         uuid.UUID          `json:"parent_device_id"`
	ChildDeviceID          uuid.UUID          `json:"child_device_id"`
	RelationType           string             `json:"relation_type"`
	DataSourceID           uuid.UUID          `json:"data_source_id"`
	ExternalParentDeviceID int64              `json:"external_parent_device_id"`
	ExternalChildDeviceID  int64              `json:"external_child_device_id"`
	Status                 string             `json:"status"`
	SyncedAt               pgtype.Timestamptz `json:"synced_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeviceID               uuid.UUID          `json:"device_id"`
	ProductID              *string            `json:"product_id"`
	SerialNo               string             `json:"serial_no"`
	Name                   string             `json:"name"`
	DeviceStatus           string             `json:"device_status"`
	ActivatedAt            pgtype.Timestamptz `json:"activated_at"`
	LifecycleStatus        string             `json:"lifecycle_status"`
	LifecycleUpdatedAt     pgtype.Timestamptz `json:"lifecycle_updated_at"`
	DeviceType             string             `json:"device_type"`
	DeviceCreatedAt        pgtype.Timestamptz `json:"device_created_at"`
	DeviceUpdatedAt        pgtype.Timestamptz `json:"device_updated_at"`
	AssignmentID           *uuid.UUID         `json:"assignment_id"`
	WorkspaceID            *uuid.UUID         `json:"workspace_id"`
	ProjectID              *uuid.UUID         `json:"project_id"`
	SiteID                 *uuid.UUID         `json:"site_id"`
	AssignedBy             *uuid.UUID         `json:"assigned_by"`
	AssignedAt             pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) ListActiveDeviceChildren(ctx context.Context, parentDeviceID uuid.UUID) ([]ListActiveDeviceChildrenRow, error) {
	rows, err := q.db.Query(ctx, listActiveDeviceChildren, parentDeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDeviceChildrenRow{}
	for rows.Next() {
		var i ListActiveDeviceChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentDeviceID,
			&i.ChildDeviceID,
			&i.RelationType,
			&i.DataSourceID,
			&i.ExternalParentDeviceID,
			&i.ExternalChildDeviceID,
			&i.Status,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceID,
			&i.ProductID,
			&i.SerialNo,
			&i.Name,
			&i.DeviceStatus,
			&i.ActivatedAt,
			&i.LifecycleStatus,
			&i.LifecycleUpdatedAt,
			&i.DeviceType,
			&i.DeviceCreatedAt,
			&i.DeviceUpdatedAt,
			&i.AssignmentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.SiteID,
			&i.AssignedBy,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceRelationsByChild = `-- name: ListDeviceRelationsByChild :many
SELECT id, parent_device_id, child_device_id, relation_type, data_source_id, external_parent_device_id, external_child_device_id, status, synced_at, created_at, updated_at
FROM device_relations
WHERE child_device_id = $1
  AND relation_type = $2
  AND status = 'active'
ORDER BY synced_at DESC, id DESC
`

type ListDeviceRelationsByChildParams struct {
	ChildDeviceID uuid.UUID `json:"child_device_id"`
	RelationType  string    `json:"relation_type"`
}

func (q *Queries) ListDeviceRelationsByChild(ctx context.Context, arg ListDeviceRelationsByChildParams) ([]DeviceRelation, error) {
	rows, err := q.db.Query(ctx, listDeviceRelationsByChild, arg.ChildDeviceID, arg.RelationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceRelation{}
	for rows.Next() {
		var i DeviceRelation
		if err := rows.Scan(
			&i.ID,
			&i.ParentDeviceID,
			&i.ChildDeviceID,
			&i.RelationType,
			&i.DataSourceID,
			&i.ExternalParentDeviceID,
			&i.ExternalChildDeviceID,
			&i.Status,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceRelationsByParent = `-- name: ListDeviceRelationsByParent :many
SELECT id, parent_device_id, child_device_id, relation_type, data_source_id, external_parent_device_id, external_child_device_id, status, synced_at, created_at, updated_at
FROM device_relations
WHERE parent_device_id = $1
  AND relation_type = $2
  AND status = 'active'
ORDER BY synced_at DESC, id DESC
`

type ListDeviceRelationsByParentParams struct {
	ParentDeviceID uuid.UUID `json:"parent_device_id"`
	RelationType   string    `json:"relation_type"`
}

func (q *Queries) ListDeviceRelationsByParent(ctx context.Context, arg ListDeviceRelationsByParentParams) ([]DeviceRelation, error) {
	rows, err := q.db.Query(ctx, listDeviceRelationsByParent, arg.ParentDeviceID, arg.RelationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceRelation{}
	for rows.Next() {
		var i DeviceRelation
		if err := rows.Scan(
			&i.ID,
			&i.ParentDeviceID,
			&i.ChildDeviceID,
			&i.RelationType,
			&i.DataSourceID,
			&i.ExternalParentDeviceID,
			&i.ExternalChildDeviceID,
			&i.Status,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleDeviceChildren = `-- name: ListVisibleDeviceChildren :many
SELECT
    dr.id,
    dr.parent_device_id,
    dr.child_device_id,
    dr.relation_type,
    dr.data_source_id,
    dr.external_parent_device_id,
    dr.external_child_device_id,
    dr.status,
    dr.synced_at,
    dr.created_at,
    dr.updated_at,
    d.id AS device_id,
    d.product_id,
    d.serial_no,
    d.name,
    d.status AS device_status,
    d.activated_at,
    d.lifecycle_status,
    d.lifecycle_updated_at,
    d.device_type,
    d.created_at AS device_created_at,
    d.updated_at AS device_updated_at,
    da.id AS assignment_id,
    da.workspace_id,
    da.project_id,
    da.site_id,
    da.assigned_by,
    da.assigned_at
FROM device_relations AS dr
JOIN devices AS d ON d.id = dr.child_device_id
JOIN device_assignments AS parent_da ON parent_da.device_id = dr.parent_device_id
    AND parent_da.status = 'active'
JOIN device_assignments AS da ON da.device_id = d.id
    AND da.status = 'active'
    AND da.workspace_id = parent_da.workspace_id
WHERE dr.parent_device_id = $1
  AND dr.relation_type = 'gateway_node'
  AND dr.status = 'active'
ORDER BY d.name ASC, d.serial_no ASC, dr.id ASC
`

type ListVisibleDeviceChildrenRow struct {
	ID                     uuid.UUID          `json:"id"`
	ParentDeviceID         uuid.UUID          `json:"parent_device_id"`
	ChildDeviceID          uuid.UUID          `json:"child_device_id"`
	RelationType           string             `json:"relation_type"`
	DataSourceID           uuid.UUID          `json:"data_source_id"`
	ExternalParentDeviceID int64              `json:"external_parent_device_id"`
	ExternalChildDeviceID  int64              `json:"external_child_device_id"`
	Status                 string             `json:"status"`
	SyncedAt               pgtype.Timestamptz `json:"synced_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeviceID               uuid.UUID          `json:"device_id"`
	ProductID              *string            `json:"product_id"`
	SerialNo               string             `json:"serial_no"`
	Name                   string             `json:"name"`
	DeviceStatus           string             `json:"device_status"`
	ActivatedAt            pgtype.Timestamptz `json:"activated_at"`
	LifecycleStatus        string             `json:"lifecycle_status"`
	LifecycleUpdatedAt     pgtype.Timestamptz `json:"lifecycle_updated_at"`
	DeviceType             string             `json:"device_type"`
	DeviceCreatedAt        pgtype.Timestamptz `json:"device_created_at"`
	DeviceUpdatedAt        pgtype.Timestamptz `json:"device_updated_at"`
	AssignmentID           uuid.UUID          `json:"assignment_id"`
	WorkspaceID            uuid.UUID          `json:"workspace_id"`
	ProjectID              *uuid.UUID         `json:"project_id"`
	SiteID                 *uuid.UUID         `json:"site_id"`
	AssignedBy             *uuid.UUID         `json:"assigned_by"`
	AssignedAt             pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) ListVisibleDeviceChildren(ctx context.Context, parentDeviceID uuid.UUID) ([]ListVisibleDeviceChildrenRow, error) {
	rows, err := q.db.Query(ctx, listVisibleDeviceChildren, parentDeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleDeviceChildrenRow{}
	for rows.Next() {
		var i ListVisibleDeviceChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentDeviceID,
			&i.ChildDeviceID,
			&i.RelationType,
			&i.DataSourceID,
			&i.ExternalParentDeviceID,
			&i.ExternalChildDeviceID,
			&i.Status,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceID,
			&i.ProductID,
			&i.SerialNo,
			&i.Name,
			&i.DeviceStatus,
			&i.ActivatedAt,
			&i.LifecycleStatus,
			&i.LifecycleUpdatedAt,
			&i.DeviceType,
			&i.DeviceCreatedAt,
			&i.DeviceUpdatedAt,
			&i.AssignmentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.SiteID,
			&i.AssignedBy,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceRelationRemovedByDevices = `-- name: MarkDeviceRelationRemovedByDevices :one
UPDATE device_relations
SET status = 'removed',
    updated_at = now()
WHERE parent_device_id = $1
  AND child_device_id = $2
  AND relation_type = 'gateway_node'
  AND status = 'active'
RETURNING id, parent_device_id, child_device_id, relation_type, data_source_id, external_parent_device_id, external_child_device_id, status, synced_at, created_at, updated_at
`

type MarkDeviceRelationRemovedByDevicesParams struct {
	ParentDeviceID uuid.UUID `json:"parent_device_id"`
	ChildDeviceID  uuid.UUID `json:"child_device_id"`
}

func (q *Queries) MarkDeviceRelationRemovedByDevices(ctx context.Context, arg MarkDeviceRelationRemovedByDevicesParams) (DeviceRelation, error) {
	row := q.db.QueryRow(ctx, markDeviceRelationRemovedByDevices, arg.ParentDeviceID, arg.ChildDeviceID)
	var i DeviceRelation
	err := row.Scan(
		&i.ID,
		&i.ParentDeviceID,
		&i.ChildDeviceID,
		&i.RelationType,
		&i.DataSourceID,
		&i.ExternalParentDeviceID,
		&i.ExternalChildDeviceID,
		&i.Status,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMissingDeviceRelationsRemoved = `-- name: MarkMissingDeviceRelationsRemoved :many
UPDATE device_relations
SET status = 'removed',
    updated_at = now()
WHERE data_source_id = $1
  AND relation_type = 'gateway_node'
  AND external_parent_device_id = $2
  AND status = 'active'
  AND NOT (external_child_device_id = ANY($3::bigint[]))
RETURNING id, parent_device_id, child_device_id, relation_type, data_source_id, external_parent_device_id, external_child_device_id, status, synced_at, created_at, updated_at
`

type MarkMissingDeviceRelationsRemovedParams struct {
	DataSourceID           uuid.UUID `json:"data_source_id"`
	ExternalParentDeviceID int64     `json:"external_parent_device_id"`
	ActiveChildIds         []int64   `json:"active_child_ids"`
}

func (q *Queries) MarkMissingDeviceRelationsRemoved(ctx context.Context, arg MarkMissingDeviceRelationsRemovedParams) ([]DeviceRelation, error) {
	rows, err := q.db.Query(ctx, markMissingDeviceRelationsRemoved, arg.DataSourceID, arg.ExternalParentDeviceID, arg.ActiveChildIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceRelation{}
	for rows.Next() {
		var i DeviceRelation
		if err := rows.Scan(
			&i.ID,
			&i.ParentDeviceID,
			&i.ChildDeviceID,
			&i.RelationType,
			&i.DataSourceID,
			&i.ExternalParentDeviceID,
			&i.ExternalChildDeviceID,
			&i.Status,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceRelation = `-- name: UpsertDeviceRelation :one
WITH updated_by_external AS (
    UPDATE device_relations AS dr
    SET parent_device_id = $1,
        child_device_id = $2,
        status = 'active',
        synced_at = now(),
        updated_at = now()
    WHERE dr.data_source_id = $4
      AND dr.relation_type = $3
      AND dr.external_parent_device_id = $5
      AND dr.external_child_device_id = $6
    RETURNING dr.id, dr.parent_device_id, dr.child_device_id, dr.relation_type, dr.data_source_id, dr.external_parent_device_id, dr.external_child_device_id, dr.status, dr.synced_at, dr.created_at, dr.updated_at
),
updated_by_devices AS (
    UPDATE device_relations AS dr
    SET data_source_id = $4,
        external_parent_device_id = $5,
        external_child_device_id = $6,
        status = 'active',
        synced_at = now(),
        updated_at = now()
    WHERE dr.parent_device_id = $1
      AND dr.child_device_id = $2
      AND dr.relation_type = $3
      AND NOT EXISTS (SELECT 1 FROM updated_by_external)
    RETURNING dr.id, dr.parent_device_id, dr.child_device_id, dr.relation_type, dr.data_source_id, dr.external_parent_device_id, dr.external_child_device_id, dr.status, dr.synced_at, dr.created_at, dr.updated_at
),
inserted AS (
    INSERT INTO device_relations (
        parent_device_id,
        child_device_id,
        relation_type,
        data_source_id,
        external_parent_device_id,
        external_child_device_id,
        status,
        synced_at
    )
    SELECT $1, $2, $3, $4, $5, $6, 'active', now()
    WHERE NOT EXISTS (SELECT 1 FROM updated_by_external)
      AND NOT EXISTS (SELECT 1 FROM updated_by_devices)
    RETURNING id, parent_device_id, child_device_id, relation_type, data_source_id, external_parent_device_id, external_child_device_id, status, synced_at, created_at, updated_at
)
SELECT id, parent_device_id, child_device_id, relation_type, data_source_id, external_parent_device_id, external_child_device_id, status, synced_at, created_at, updated_at
FROM updated_by_external
UNION ALL
SELECT id, parent_device_id, child_device_id, relation_type, data_source_id, external_parent_device_id, external_child_device_id, status, synced_at, created_at, updated_at
FROM updated_by_devices
UNION ALL
SELECT id, parent_device_id, child_device_id, relation_type, data_source_id, external_parent_device_id, external_child_device_id, status, synced_at, created_at, updated_at
FROM inserted
`

type UpsertDeviceRelationParams struct {
	ParentDeviceID         uuid.UUID `json:"parent_device_id"`
	ChildDeviceID          uuid.UUID `json:"child_device_id"`
	RelationType           string    `json:"relation_type"`
	DataSourceID           uuid.UUID `json:"data_source_id"`
	ExternalParentDeviceID int64     `json:"external_parent_device_id"`
	ExternalChildDeviceID  int64     `json:"external_child_device_id"`
}

type UpsertDeviceRelationRow struct {
	ID                     uuid.UUID          `json:"id"`
	ParentDeviceID         uuid.UUID          `json:"parent_device_id"`
	ChildDeviceID          uuid.UUID          `json:"child_device_id"`
	RelationType           string             `json:"relation_type"`
	DataSourceID           uuid.UUID          `json:"data_source_id"`
	ExternalParentDeviceID int64              `json:"external_parent_device_id"`
	ExternalChildDeviceID  int64              `json:"external_child_device_id"`
	Status                 string             `json:"status"`
	SyncedAt               pgtype.Timestamptz `json:"synced_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertDeviceRelation(ctx context.Context, arg UpsertDeviceRelationParams) (UpsertDeviceRelationRow, error) {
	row := q.db.QueryRow(ctx, upsertDeviceRelation,
		arg.ParentDeviceID,
		arg.ChildDeviceID,
		arg.RelationType,
		arg.DataSourceID,
		arg.ExternalParentDeviceID,
		arg.ExternalChildDeviceID,
	)
	var i UpsertDeviceRelationRow
	err := row.Scan(
		&i.ID,
		&i.ParentDeviceID,
		&i.ChildDeviceID,
		&i.RelationType,
		&i.DataSourceID,
		&i.ExternalParentDeviceID,
		&i.ExternalChildDeviceID,
		&i.Status,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
