// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: export.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingExportJob = `-- name: ClaimNextPendingExportJob :one
WITH next_job AS (
    SELECT id
    FROM export_jobs
    WHERE status = 'pending'
      AND expires_at > now()
    ORDER BY created_at ASC, id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE export_jobs
SET status = 'running',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id IN (SELECT id FROM next_job)
RETURNING id, workspace_id, requested_by, resource_type, resource_id, export_type, status, file_object_key, error_message, created_at, updated_at, started_at, finished_at, expires_at, request_config_json
`

func (q *Queries) ClaimNextPendingExportJob(ctx context.Context) (ExportJob, error) {
	row := q.db.QueryRow(ctx, claimNextPendingExportJob)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExportType,
		&i.Status,
		&i.FileObjectKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
		&i.RequestConfigJson,
	)
	return i, err
}

const createExportJob = `-- name: CreateExportJob :one
INSERT INTO export_jobs (
    workspace_id,
    requested_by,
    resource_type,
    resource_id,
    export_type,
    request_config_json,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, requested_by, resource_type, resource_id, export_type, status, file_object_key, error_message, created_at, updated_at, started_at, finished_at, expires_at, request_config_json
`

type CreateExportJobParams struct {
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	RequestedBy       uuid.UUID          `json:"requested_by"`
	ResourceType      string             `json:"resource_type"`
	ResourceID        uuid.UUID          `json:"resource_id"`
	ExportType        string             `json:"export_type"`
	RequestConfigJson []byte             `json:"request_config_json"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, createExportJob,
		arg.WorkspaceID,
		arg.RequestedBy,
		arg.ResourceType,
		arg.ResourceID,
		arg.ExportType,
		arg.RequestConfigJson,
		arg.ExpiresAt,
	)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExportType,
		&i.Status,
		&i.FileObjectKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
		&i.RequestConfigJson,
	)
	return i, err
}

const expireExportJobs = `-- name: ExpireExportJobs :execrows
UPDATE export_jobs
SET status = 'expired',
    updated_at = now(),
    finished_at = COALESCE(finished_at, now())
WHERE status IN ('pending', 'running')
  AND expires_at <= now()
`

func (q *Queries) ExpireExportJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireExportJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExportJob = `-- name: GetExportJob :one
SELECT id, workspace_id, requested_by, resource_type, resource_id, export_type, status, file_object_key, error_message, created_at, updated_at, started_at, finished_at, expires_at, request_config_json
FROM export_jobs
WHERE id = $1
`

func (q *Queries) GetExportJob(ctx context.Context, id uuid.UUID) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJob, id)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExportType,
		&i.Status,
		&i.FileObjectKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
		&i.RequestConfigJson,
	)
	return i, err
}

const listExportJobsByRequester = `-- name: ListExportJobsByRequester :many
SELECT id, workspace_id, requested_by, resource_type, resource_id, export_type, status, file_object_key, error_message, created_at, updated_at, started_at, finished_at, expires_at, request_config_json
FROM export_jobs
WHERE requested_by = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListExportJobsByRequesterParams struct {
	RequestedBy uuid.UUID `json:"requested_by"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) ListExportJobsByRequester(ctx context.Context, arg ListExportJobsByRequesterParams) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExportJobsByRequester, arg.RequestedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportJob{}
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RequestedBy,
			&i.ResourceType,
			&i.ResourceID,
			&i.ExportType,
			&i.Status,
			&i.FileObjectKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
			&i.RequestConfigJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportJobsByRequesterAndWorkspace = `-- name: ListExportJobsByRequesterAndWorkspace :many
SELECT id, workspace_id, requested_by, resource_type, resource_id, export_type, status, file_object_key, error_message, created_at, updated_at, started_at, finished_at, expires_at, request_config_json
FROM export_jobs
WHERE workspace_id = $1
  AND requested_by = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListExportJobsByRequesterAndWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	RequestedBy uuid.UUID `json:"requested_by"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) ListExportJobsByRequesterAndWorkspace(ctx context.Context, arg ListExportJobsByRequesterAndWorkspaceParams) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExportJobsByRequesterAndWorkspace, arg.WorkspaceID, arg.RequestedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportJob{}
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RequestedBy,
			&i.ResourceType,
			&i.ResourceID,
			&i.ExportType,
			&i.Status,
			&i.FileObjectKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
			&i.RequestConfigJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportJobsByWorkspace = `-- name: ListExportJobsByWorkspace :many
SELECT id, workspace_id, requested_by, resource_type, resource_id, export_type, status, file_object_key, error_message, created_at, updated_at, started_at, finished_at, expires_at, request_config_json
FROM export_jobs
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListExportJobsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) ListExportJobsByWorkspace(ctx context.Context, arg ListExportJobsByWorkspaceParams) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExportJobsByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportJob{}
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RequestedBy,
			&i.ResourceType,
			&i.ResourceID,
			&i.ExportType,
			&i.Status,
			&i.FileObjectKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
			&i.RequestConfigJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExportJobFailed = `-- name: MarkExportJobFailed :one
UPDATE export_jobs
SET status = 'failed',
    error_message = $2,
    finished_at = now(),
    updated_at = now()
WHERE id = $1
  AND status IN ('pending', 'running')
RETURNING id, workspace_id, requested_by, resource_type, resource_id, export_type, status, file_object_key, error_message, created_at, updated_at, started_at, finished_at, expires_at, request_config_json
`

type MarkExportJobFailedParams struct {
	ID           uuid.UUID `json:"id"`
	ErrorMessage *string   `json:"error_message"`
}

func (q *Queries) MarkExportJobFailed(ctx context.Context, arg MarkExportJobFailedParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, markExportJobFailed, arg.ID, arg.ErrorMessage)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExportType,
		&i.Status,
		&i.FileObjectKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
		&i.RequestConfigJson,
	)
	return i, err
}

const markExportJobRunning = `-- name: MarkExportJobRunning :one
UPDATE export_jobs
SET status = 'running',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, workspace_id, requested_by, resource_type, resource_id, export_type, status, file_object_key, error_message, created_at, updated_at, started_at, finished_at, expires_at, request_config_json
`

func (q *Queries) MarkExportJobRunning(ctx context.Context, id uuid.UUID) (ExportJob, error) {
	row := q.db.QueryRow(ctx, markExportJobRunning, id)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExportType,
		&i.Status,
		&i.FileObjectKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
		&i.RequestConfigJson,
	)
	return i, err
}

const markExportJobSuccess = `-- name: MarkExportJobSuccess :one
UPDATE export_jobs
SET status = 'success',
    file_object_key = $2,
    error_message = NULL,
    finished_at = now(),
    updated_at = now()
WHERE id = $1
  AND status IN ('pending', 'running')
RETURNING id, workspace_id, requested_by, resource_type, resource_id, export_type, status, file_object_key, error_message, created_at, updated_at, started_at, finished_at, expires_at, request_config_json
`

type MarkExportJobSuccessParams struct {
	ID            uuid.UUID `json:"id"`
	FileObjectKey *string   `json:"file_object_key"`
}

func (q *Queries) MarkExportJobSuccess(ctx context.Context, arg MarkExportJobSuccessParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, markExportJobSuccess, arg.ID, arg.FileObjectKey)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExportType,
		&i.Status,
		&i.FileObjectKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
		&i.RequestConfigJson,
	)
	return i, err
}
