// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: lorawan_v2.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const upsertLoRaWANV2Metadata = `-- name: UpsertLoRaWANV2Metadata :exec
INSERT INTO device_metadata (device_id, key, name, value_type, value_json, unit, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5::jsonb, $6, $7, $7)
ON CONFLICT (device_id, key) DO UPDATE SET
    name = EXCLUDED.name,
    value_type = EXCLUDED.value_type,
    value_json = EXCLUDED.value_json,
    unit = EXCLUDED.unit,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
`

type UpsertLoRaWANV2MetadataParams struct {
	DeviceID  uuid.UUID `json:"device_id"`
	Key       string    `json:"key"`
	Name      string    `json:"name"`
	ValueType string    `json:"value_type"`
	Column5   []byte    `json:"column_5"`
	Unit      *string   `json:"unit"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) UpsertLoRaWANV2Metadata(ctx context.Context, arg UpsertLoRaWANV2MetadataParams) error {
	_, err := q.db.Exec(ctx, upsertLoRaWANV2Metadata,
		arg.DeviceID,
		arg.Key,
		arg.Name,
		arg.ValueType,
		arg.Column5,
		arg.Unit,
		arg.CreatedBy,
	)
	return err
}
