// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: member.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveWorkspaceOwners = `-- name: CountActiveWorkspaceOwners :one
SELECT count(*)::bigint
FROM workspace_members wm
JOIN roles r ON r.id = wm.role_id
WHERE wm.workspace_id = $1
  AND wm.status = 'active'
  AND r.code = 'owner'
  AND r.workspace_id IS NULL
`

func (q *Queries) CountActiveWorkspaceOwners(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWorkspaceOwners, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getWorkspaceMemberDetail = `-- name: GetWorkspaceMemberDetail :one
SELECT
    wm.id,
    wm.workspace_id,
    wm.user_id,
    wm.role_id,
    wm.status,
    wm.joined_at,
    wm.created_at,
    wm.updated_at,
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email,
    u.status AS user_status,
    r.code AS role_code,
    r.name AS role_name
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
JOIN roles r ON r.id = wm.role_id
WHERE wm.workspace_id = $1
  AND wm.id = $2
`

type GetWorkspaceMemberDetailParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

type GetWorkspaceMemberDetailRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	RoleID      uuid.UUID          `json:"role_id"`
	Status      string             `json:"status"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserName    string             `json:"user_name"`
	UserPhone   *string            `json:"user_phone"`
	UserEmail   *string            `json:"user_email"`
	UserStatus  string             `json:"user_status"`
	RoleCode    string             `json:"role_code"`
	RoleName    string             `json:"role_name"`
}

func (q *Queries) GetWorkspaceMemberDetail(ctx context.Context, arg GetWorkspaceMemberDetailParams) (GetWorkspaceMemberDetailRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberDetail, arg.WorkspaceID, arg.ID)
	var i GetWorkspaceMemberDetailRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserPhone,
		&i.UserEmail,
		&i.UserStatus,
		&i.RoleCode,
		&i.RoleName,
	)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT
    wm.id,
    wm.workspace_id,
    wm.user_id,
    wm.role_id,
    wm.status,
    wm.joined_at,
    wm.created_at,
    wm.updated_at,
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email,
    u.status AS user_status,
    r.code AS role_code,
    r.name AS role_name
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
JOIN roles r ON r.id = wm.role_id
WHERE wm.workspace_id = $1
  AND wm.status != 'removed'
ORDER BY wm.joined_at ASC
`

type ListWorkspaceMembersRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	RoleID      uuid.UUID          `json:"role_id"`
	Status      string             `json:"status"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserName    string             `json:"user_name"`
	UserPhone   *string            `json:"user_phone"`
	UserEmail   *string            `json:"user_email"`
	UserStatus  string             `json:"user_status"`
	RoleCode    string             `json:"role_code"`
	RoleName    string             `json:"role_name"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.RoleID,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserPhone,
			&i.UserEmail,
			&i.UserStatus,
			&i.RoleCode,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :one
UPDATE workspace_members
SET status = 'removed',
    updated_at = now()
WHERE workspace_id = $1
  AND id = $2
RETURNING id, workspace_id, user_id, role_id, status, joined_at, created_at, updated_at
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.ID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :one
UPDATE workspace_members
SET role_id = $3,
    updated_at = now()
WHERE workspace_id = $1
  AND id = $2
RETURNING id, workspace_id, user_id, role_id, status, joined_at, created_at, updated_at
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
	RoleID      uuid.UUID `json:"role_id"`
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.ID, arg.RoleID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceMemberRoleStatusByUser = `-- name: UpdateWorkspaceMemberRoleStatusByUser :one
UPDATE workspace_members
SET role_id = $3,
    status = $4,
    joined_at = CASE
        WHEN status != 'active' AND $4 = 'active' THEN now()
        ELSE joined_at
    END,
    updated_at = now()
WHERE workspace_id = $1
  AND user_id = $2
RETURNING id, workspace_id, user_id, role_id, status, joined_at, created_at, updated_at
`

type UpdateWorkspaceMemberRoleStatusByUserParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	RoleID      uuid.UUID `json:"role_id"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateWorkspaceMemberRoleStatusByUser(ctx context.Context, arg UpdateWorkspaceMemberRoleStatusByUserParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceMemberRoleStatusByUser,
		arg.WorkspaceID,
		arg.UserID,
		arg.RoleID,
		arg.Status,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
