// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppMetadatum struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID           uuid.UUID `json:"id"`
	Code         string    `json:"code"`
	Name         string    `json:"name"`
	ResourceType string    `json:"resource_type"`
	Action       string    `json:"action"`
}

type Role struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  *uuid.UUID         `json:"workspace_id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	IsSystemRole bool               `json:"is_system_role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Phone     *string            `json:"phone"`
	Email     *string            `json:"email"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID               uuid.UUID          `json:"id"`
	Type             string             `json:"type"`
	OrganizationType *string            `json:"organization_type"`
	Name             string             `json:"name"`
	OwnerUserID      uuid.UUID          `json:"owner_user_id"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceMember struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	RoleID      uuid.UUID          `json:"role_id"`
	Status      string             `json:"status"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
