// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessGrant struct {
	ID             uuid.UUID          `json:"id"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	SubjectType    string             `json:"subject_type"`
	SubjectID      uuid.UUID          `json:"subject_id"`
	RoleID         uuid.UUID          `json:"role_id"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        uuid.UUID          `json:"scope_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	AllowReshare   bool               `json:"allow_reshare"`
	AllowApiAccess bool               `json:"allow_api_access"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AppMetadatum struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  *uuid.UUID         `json:"workspace_id"`
	ActorType    string             `json:"actor_type"`
	ActorID      *uuid.UUID         `json:"actor_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   *uuid.UUID         `json:"resource_id"`
	Result       string             `json:"result"`
	Reason       *string            `json:"reason"`
	Ip           *string            `json:"ip"`
	UserAgent    *string            `json:"user_agent"`
	RequestID    *string            `json:"request_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuthAccessTokenBlacklist struct {
	TokenHash string             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthRefreshSession struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        *string            `json:"user_agent"`
	ClientIp         *string            `json:"client_ip"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type DataSource struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Type         string             `json:"type"`
	DsnSecretRef string             `json:"dsn_secret_ref"`
	Status       string             `json:"status"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DataStream struct {
	ID        uuid.UUID          `json:"id"`
	DeviceID  uuid.UUID          `json:"device_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Unit      *string            `json:"unit"`
	Status    string             `json:"status"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DataStreamBinding struct {
	ID                uuid.UUID          `json:"id"`
	DataStreamID      uuid.UUID          `json:"data_stream_id"`
	DataSourceID      uuid.UUID          `json:"data_source_id"`
	DatabaseName      *string            `json:"database_name"`
	SchemaName        *string            `json:"schema_name"`
	TableName         *string            `json:"table_name"`
	DeviceKeyField    *string            `json:"device_key_field"`
	DeviceKeyValue    *string            `json:"device_key_value"`
	TimeField         *string            `json:"time_field"`
	ValueField        *string            `json:"value_field"`
	PayloadType       string             `json:"payload_type"`
	AdapterConfigJson []byte             `json:"adapter_config_json"`
	Status            string             `json:"status"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AdapterCode       string             `json:"adapter_code"`
}

type Dataset struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	ProjectID   *uuid.UUID         `json:"project_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	DataType    string             `json:"data_type"`
	TimeStart   pgtype.Timestamptz `json:"time_start"`
	TimeEnd     pgtype.Timestamptz `json:"time_end"`
	Status      string             `json:"status"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DatasetSource struct {
	ID         uuid.UUID          `json:"id"`
	DatasetID  uuid.UUID          `json:"dataset_id"`
	SourceType string             `json:"source_type"`
	SourceID   uuid.UUID          `json:"source_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID          uuid.UUID          `json:"id"`
	ProductID   *string            `json:"product_id"`
	SerialNo    string             `json:"serial_no"`
	Name        string             `json:"name"`
	Status      string             `json:"status"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DeviceAssignment struct {
	ID           uuid.UUID          `json:"id"`
	DeviceID     uuid.UUID          `json:"device_id"`
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	ProjectID    *uuid.UUID         `json:"project_id"`
	SiteID       *uuid.UUID         `json:"site_id"`
	Status       string             `json:"status"`
	AssignedBy   *uuid.UUID         `json:"assigned_by"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	UnassignedAt pgtype.Timestamptz `json:"unassigned_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DeviceCapability struct {
	ID             uuid.UUID          `json:"id"`
	DeviceID       uuid.UUID          `json:"device_id"`
	CapabilityCode string             `json:"capability_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DeviceConfigSnapshot struct {
	ID               uuid.UUID          `json:"id"`
	DeviceID         uuid.UUID          `json:"device_id"`
	DataSourceID     uuid.UUID          `json:"data_source_id"`
	AdapterCode      string             `json:"adapter_code"`
	ExternalDeviceID int64              `json:"external_device_id"`
	ExternalConfigID int64              `json:"external_config_id"`
	Version          *string            `json:"version"`
	DataJson         []byte             `json:"data_json"`
	ImageJson        []byte             `json:"image_json"`
	ControlJson      []byte             `json:"control_json"`
	SourceCreatedAt  pgtype.Timestamptz `json:"source_created_at"`
	SourceUpdatedAt  pgtype.Timestamptz `json:"source_updated_at"`
	SyncedAt         pgtype.Timestamptz `json:"synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type DeviceOperation struct {
	ID            uuid.UUID          `json:"id"`
	WorkspaceID   uuid.UUID          `json:"workspace_id"`
	DeviceID      uuid.UUID          `json:"device_id"`
	OperationType string             `json:"operation_type"`
	Status        string             `json:"status"`
	RequestJson   []byte             `json:"request_json"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DeviceRelation struct {
	ID                     uuid.UUID          `json:"id"`
	ParentDeviceID         uuid.UUID          `json:"parent_device_id"`
	ChildDeviceID          uuid.UUID          `json:"child_device_id"`
	RelationType           string             `json:"relation_type"`
	DataSourceID           uuid.UUID          `json:"data_source_id"`
	ExternalParentDeviceID int64              `json:"external_parent_device_id"`
	ExternalChildDeviceID  int64              `json:"external_child_device_id"`
	Status                 string             `json:"status"`
	SyncedAt               pgtype.Timestamptz `json:"synced_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type DeviceSourceRef struct {
	ID                 uuid.UUID          `json:"id"`
	DeviceID           uuid.UUID          `json:"device_id"`
	DataSourceID       uuid.UUID          `json:"data_source_id"`
	AdapterCode        string             `json:"adapter_code"`
	ExternalDeviceID   int64              `json:"external_device_id"`
	ExternalSn         *string            `json:"external_sn"`
	ExternalUuid       *string            `json:"external_uuid"`
	ExternalDeviceType *string            `json:"external_device_type"`
	Status             string             `json:"status"`
	SyncedAt           pgtype.Timestamptz `json:"synced_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ExportJob struct {
	ID                uuid.UUID          `json:"id"`
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	RequestedBy       uuid.UUID          `json:"requested_by"`
	ResourceType      string             `json:"resource_type"`
	ResourceID        uuid.UUID          `json:"resource_id"`
	ExportType        string             `json:"export_type"`
	Status            string             `json:"status"`
	FileObjectKey     *string            `json:"file_object_key"`
	ErrorMessage      *string            `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	RequestConfigJson []byte             `json:"request_config_json"`
}

type Invitation struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	InviteeEmail *string            `json:"invitee_email"`
	InviteePhone *string            `json:"invitee_phone"`
	RoleID       uuid.UUID          `json:"role_id"`
	ScopeType    string             `json:"scope_type"`
	ScopeID      uuid.UUID          `json:"scope_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	InvitedBy    uuid.UUID          `json:"invited_by"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID           uuid.UUID `json:"id"`
	Code         string    `json:"code"`
	Name         string    `json:"name"`
	ResourceType string    `json:"resource_type"`
	Action       string    `json:"action"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  *uuid.UUID         `json:"workspace_id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	IsSystemRole bool               `json:"is_system_role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type Site struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	LocationText *string            `json:"location_text"`
	Latitude     pgtype.Float8      `json:"latitude"`
	Longitude    pgtype.Float8      `json:"longitude"`
	Status       string             `json:"status"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Phone           *string            `json:"phone"`
	Email           *string            `json:"email"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PhoneVerifiedAt pgtype.Timestamptz `json:"phone_verified_at"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	IsSystemAdmin   bool               `json:"is_system_admin"`
}

type UserCredential struct {
	UserID            uuid.UUID          `json:"user_id"`
	PasswordHash      string             `json:"password_hash"`
	PasswordUpdatedAt pgtype.Timestamptz `json:"password_updated_at"`
	FailedAttempts    int32              `json:"failed_attempts"`
	LockedUntil       pgtype.Timestamptz `json:"locked_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserMfaTotp struct {
	UserID           uuid.UUID          `json:"user_id"`
	SecretCiphertext []byte             `json:"secret_ciphertext"`
	SecretNonce      []byte             `json:"secret_nonce"`
	EnabledAt        pgtype.Timestamptz `json:"enabled_at"`
	LastUsedStep     pgtype.Int8        `json:"last_used_step"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID               uuid.UUID          `json:"id"`
	Type             string             `json:"type"`
	OrganizationType *string            `json:"organization_type"`
	Name             string             `json:"name"`
	OwnerUserID      uuid.UUID          `json:"owner_user_id"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceMember struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	RoleID      uuid.UUID          `json:"role_id"`
	Status      string             `json:"status"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
