// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permission.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const hasWorkspacePermission = `-- name: HasWorkspacePermission :one
SELECT EXISTS (
    SELECT 1
    FROM workspace_members wm
    JOIN roles r ON r.id = wm.role_id
    JOIN role_permissions rp ON rp.role_id = r.id
    JOIN permissions p ON p.id = rp.permission_id
    WHERE wm.user_id = $1
      AND wm.workspace_id = $2
      AND wm.status = 'active'
      AND p.code = $3
      AND (r.workspace_id IS NULL OR r.workspace_id = wm.workspace_id)
) AS allowed
`

type HasWorkspacePermissionParams struct {
	UserID      uuid.UUID `json:"user_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Code        string    `json:"code"`
}

func (q *Queries) HasWorkspacePermission(ctx context.Context, arg HasWorkspacePermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasWorkspacePermission, arg.UserID, arg.WorkspaceID, arg.Code)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}
