// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountActiveWorkspaceOwners(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	CreateOrganizationWorkspace(ctx context.Context, arg CreateOrganizationWorkspaceParams) (Workspace, error)
	CreatePersonalWorkspace(ctx context.Context, arg CreatePersonalWorkspaceParams) (Workspace, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) (UserCredential, error)
	CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error)
	FindActiveUserByEmail(ctx context.Context, email *string) (User, error)
	FindActiveUserByIdentifier(ctx context.Context, identifier *string) (User, error)
	FindActiveUserByPhone(ctx context.Context, phone *string) (User, error)
	FindActiveUserByPhoneForAuth(ctx context.Context, phone *string) (User, error)
	GetActiveUser(ctx context.Context, id uuid.UUID) (User, error)
	GetAppMetadata(ctx context.Context, key string) (AppMetadatum, error)
	GetSystemRoleByCode(ctx context.Context, code string) (Role, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserCredential(ctx context.Context, userID uuid.UUID) (UserCredential, error)
	GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error)
	GetWorkspaceMemberDetail(ctx context.Context, arg GetWorkspaceMemberDetailParams) (GetWorkspaceMemberDetailRow, error)
	HasWorkspacePermission(ctx context.Context, arg HasWorkspacePermissionParams) (bool, error)
	ListAppMetadata(ctx context.Context) ([]AppMetadatum, error)
	ListSystemRoles(ctx context.Context) ([]Role, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error)
	ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error)
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (WorkspaceMember, error)
	ResetUserCredentialFailure(ctx context.Context, userID uuid.UUID) (UserCredential, error)
	UpdateUserCredentialFailure(ctx context.Context, arg UpdateUserCredentialFailureParams) (UserCredential, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) (User, error)
	UpdateUserPhoneVerifiedAndLogin(ctx context.Context, id uuid.UUID) (User, error)
	UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (WorkspaceMember, error)
	UpdateWorkspaceMemberRoleStatusByUser(ctx context.Context, arg UpdateWorkspaceMemberRoleStatusByUserParams) (WorkspaceMember, error)
	UpsertAppMetadata(ctx context.Context, arg UpsertAppMetadataParams) (AppMetadatum, error)
}

var _ Querier = (*Queries)(nil)
