// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrganizationWorkspace(ctx context.Context, arg CreateOrganizationWorkspaceParams) (Workspace, error)
	CreatePersonalWorkspace(ctx context.Context, arg CreatePersonalWorkspaceParams) (Workspace, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error)
	GetActiveUser(ctx context.Context, id uuid.UUID) (User, error)
	GetAppMetadata(ctx context.Context, key string) (AppMetadatum, error)
	GetSystemRoleByCode(ctx context.Context, code string) (Role, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error)
	HasWorkspacePermission(ctx context.Context, arg HasWorkspacePermissionParams) (bool, error)
	ListAppMetadata(ctx context.Context) ([]AppMetadatum, error)
	ListSystemRoles(ctx context.Context) ([]Role, error)
	ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error)
	UpsertAppMetadata(ctx context.Context, arg UpsertAppMetadataParams) (AppMetadatum, error)
}

var _ Querier = (*Queries)(nil)
