// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role.sql

package sqlc

import (
	"context"
)

const getSystemRoleByCode = `-- name: GetSystemRoleByCode :one
SELECT id, workspace_id, code, name, is_system_role, created_at, updated_at
FROM roles
WHERE workspace_id IS NULL AND code = $1 AND is_system_role = true
`

func (q *Queries) GetSystemRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRow(ctx, getSystemRoleByCode, code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.Name,
		&i.IsSystemRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemRoles = `-- name: ListSystemRoles :many
SELECT id, workspace_id, code, name, is_system_role, created_at, updated_at
FROM roles
WHERE workspace_id IS NULL AND is_system_role = true
ORDER BY code
`

func (q *Queries) ListSystemRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listSystemRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Code,
			&i.Name,
			&i.IsSystemRole,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
