// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: site.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (
    workspace_id,
    project_id,
    name,
    description,
    location_text,
    latitude,
    longitude,
    created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, project_id, name, description, location_text, latitude, longitude, status, created_by, created_at, updated_at
`

type CreateSiteParams struct {
	WorkspaceID  uuid.UUID     `json:"workspace_id"`
	ProjectID    uuid.UUID     `json:"project_id"`
	Name         string        `json:"name"`
	Description  *string       `json:"description"`
	LocationText *string       `json:"location_text"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
	CreatedBy    uuid.UUID     `json:"created_by"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.LocationText,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedBy,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.LocationText,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT id, workspace_id, project_id, name, description, location_text, latitude, longitude, status, created_by, created_at, updated_at
FROM sites
WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id uuid.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.LocationText,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSitesByProject = `-- name: ListSitesByProject :many
SELECT id, workspace_id, project_id, name, description, location_text, latitude, longitude, status, created_by, created_at, updated_at
FROM sites
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListSitesByProject(ctx context.Context, projectID uuid.UUID) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSitesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.LocationText,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesByWorkspace = `-- name: ListSitesByWorkspace :many
SELECT id, workspace_id, project_id, name, description, location_text, latitude, longitude, status, created_by, created_at, updated_at
FROM sites
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListSitesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSitesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.LocationText,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSite = `-- name: UpdateSite :one
UPDATE sites
SET name = $2,
    description = $3,
    location_text = $4,
    latitude = $5,
    longitude = $6,
    status = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, project_id, name, description, location_text, latitude, longitude, status, created_by, created_at, updated_at
`

type UpdateSiteParams struct {
	ID           uuid.UUID     `json:"id"`
	Name         string        `json:"name"`
	Description  *string       `json:"description"`
	LocationText *string       `json:"location_text"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
	Status       string        `json:"status"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSite,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LocationText,
		arg.Latitude,
		arg.Longitude,
		arg.Status,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.LocationText,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
