// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, phone, email)
VALUES ($1, $2, $3)
RETURNING id, name, phone, email, status, created_at, updated_at, phone_verified_at, email_verified_at, last_login_at, auth_version, is_demo
`

type CreateUserParams struct {
	Name  string  `json:"name"`
	Phone *string `json:"phone"`
	Email *string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Phone, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneVerifiedAt,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.AuthVersion,
		&i.IsDemo,
	)
	return i, err
}

const findActiveUserByEmail = `-- name: FindActiveUserByEmail :one
SELECT id, name, phone, email, status, created_at, updated_at, phone_verified_at, email_verified_at, last_login_at, auth_version, is_demo
FROM users
WHERE email = $1 AND status = 'active'
`

func (q *Queries) FindActiveUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, findActiveUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneVerifiedAt,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.AuthVersion,
		&i.IsDemo,
	)
	return i, err
}

const findActiveUserByPhone = `-- name: FindActiveUserByPhone :one
SELECT id, name, phone, email, status, created_at, updated_at, phone_verified_at, email_verified_at, last_login_at, auth_version, is_demo
FROM users
WHERE phone = $1 AND status = 'active'
`

func (q *Queries) FindActiveUserByPhone(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, findActiveUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneVerifiedAt,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.AuthVersion,
		&i.IsDemo,
	)
	return i, err
}

const getActiveUser = `-- name: GetActiveUser :one
SELECT id, name, phone, email, status, created_at, updated_at, phone_verified_at, email_verified_at, last_login_at, auth_version, is_demo
FROM users
WHERE id = $1 AND status = 'active'
`

func (q *Queries) GetActiveUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneVerifiedAt,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.AuthVersion,
		&i.IsDemo,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, phone, email, status, created_at, updated_at, phone_verified_at, email_verified_at, last_login_at, auth_version, is_demo
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneVerifiedAt,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.AuthVersion,
		&i.IsDemo,
	)
	return i, err
}
