// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspace.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizationWorkspace = `-- name: CreateOrganizationWorkspace :one
INSERT INTO workspaces (type, organization_type, name, owner_user_id)
VALUES ('organization', $1, $2, $3)
RETURNING id, type, organization_type, name, owner_user_id, status, created_at, updated_at
`

type CreateOrganizationWorkspaceParams struct {
	OrganizationType *string   `json:"organization_type"`
	Name             string    `json:"name"`
	OwnerUserID      uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) CreateOrganizationWorkspace(ctx context.Context, arg CreateOrganizationWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createOrganizationWorkspace, arg.OrganizationType, arg.Name, arg.OwnerUserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OrganizationType,
		&i.Name,
		&i.OwnerUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPersonalWorkspace = `-- name: CreatePersonalWorkspace :one
INSERT INTO workspaces (type, name, owner_user_id)
VALUES ('personal', $1, $2)
RETURNING id, type, organization_type, name, owner_user_id, status, created_at, updated_at
`

type CreatePersonalWorkspaceParams struct {
	Name        string    `json:"name"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) CreatePersonalWorkspace(ctx context.Context, arg CreatePersonalWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createPersonalWorkspace, arg.Name, arg.OwnerUserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OrganizationType,
		&i.Name,
		&i.OwnerUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_id, role_id, scope_type, scope_id, template_code)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, user_id, role_id, status, joined_at, created_at, updated_at, scope_type, scope_id, template_code
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	UserID       uuid.UUID `json:"user_id"`
	RoleID       uuid.UUID `json:"role_id"`
	ScopeType    string    `json:"scope_type"`
	ScopeID      uuid.UUID `json:"scope_id"`
	TemplateCode string    `json:"template_code"`
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, createWorkspaceMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.RoleID,
		arg.ScopeType,
		arg.ScopeID,
		arg.TemplateCode,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScopeType,
		&i.ScopeID,
		&i.TemplateCode,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, type, organization_type, name, owner_user_id, status, created_at, updated_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OrganizationType,
		&i.Name,
		&i.OwnerUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT id, workspace_id, user_id, role_id, status, joined_at, created_at, updated_at, scope_type, scope_id, template_code
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScopeType,
		&i.ScopeID,
		&i.TemplateCode,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, type, organization_type, name, owner_user_id, status, created_at, updated_at
FROM workspaces
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OrganizationType,
			&i.Name,
			&i.OwnerUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT
    w.id,
    w.type,
    w.organization_type,
    w.name,
    w.owner_user_id,
    w.status,
    w.created_at,
    w.updated_at,
    wm.id AS membership_id,
    wm.status AS membership_status,
    wm.joined_at AS membership_joined_at,
    wm.scope_type AS membership_scope_type,
    wm.scope_id AS membership_scope_id,
    tr.id AS role_id,
    wm.template_code AS role_code,
    COALESCE(tr.name, '自定义权限') AS role_name
FROM workspace_members wm
JOIN workspaces w ON w.id = wm.workspace_id
LEFT JOIN roles tr ON tr.workspace_id IS NULL AND tr.code = wm.template_code
WHERE wm.user_id = $1
  AND wm.status = 'active'
  AND w.status = 'active'
ORDER BY w.created_at ASC
`

type ListWorkspacesForUserRow struct {
	ID                  uuid.UUID          `json:"id"`
	Type                string             `json:"type"`
	OrganizationType    *string            `json:"organization_type"`
	Name                string             `json:"name"`
	OwnerUserID         uuid.UUID          `json:"owner_user_id"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	MembershipID        uuid.UUID          `json:"membership_id"`
	MembershipStatus    string             `json:"membership_status"`
	MembershipJoinedAt  pgtype.Timestamptz `json:"membership_joined_at"`
	MembershipScopeType string             `json:"membership_scope_type"`
	MembershipScopeID   uuid.UUID          `json:"membership_scope_id"`
	RoleID              *uuid.UUID         `json:"role_id"`
	RoleCode            string             `json:"role_code"`
	RoleName            string             `json:"role_name"`
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OrganizationType,
			&i.Name,
			&i.OwnerUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MembershipID,
			&i.MembershipStatus,
			&i.MembershipJoinedAt,
			&i.MembershipScopeType,
			&i.MembershipScopeID,
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
