ALTER TABLE sensor_templates
  ADD COLUMN metrics jsonb NOT NULL DEFAULT '[]'::jsonb;

UPDATE sensor_templates
SET metrics = CASE
  WHEN jsonb_typeof(params->'contents') = 'array' THEN params->'contents'
  ELSE '[]'::jsonb
END;

CREATE TABLE sensor_template_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id bigint NOT NULL REFERENCES sensor_templates(id) ON DELETE CASCADE,
  source_family text NOT NULL CHECK (source_family IN ('thcpn','lorawan_v2')),
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(template_id, source_family)
);

INSERT INTO sensor_template_variants(template_id, source_family, config)
SELECT id, 'thcpn', jsonb_build_object(
  'port', port, 'port_num', port_num, 'port_nums', port_nums,
  'driver', driver, 'params', params
) FROM sensor_templates;

CREATE INDEX sensor_template_variants_family_idx
  ON sensor_template_variants(source_family, status, template_id);

CREATE TABLE lorawan_v2_node_config_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  node_index integer NOT NULL CHECK (node_index BETWEEN 1 AND 254),
  upstream_config_id bigint,
  content_hash text NOT NULL,
  wait_time integer NOT NULL CHECK (wait_time BETWEEN 0 AND 65535),
  content_json jsonb NOT NULL,
  template_instances jsonb NOT NULL DEFAULT '[]'::jsonb,
  metrics_json jsonb NOT NULL,
  management_status text NOT NULL CHECK (management_status IN ('managed','matched','unmanaged')),
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX lorawan_v2_node_config_snapshots_lookup_idx
  ON lorawan_v2_node_config_snapshots(device_id, node_index, upstream_config_id, created_at DESC);

COMMENT ON COLUMN sensor_templates.metrics IS 'Canonical metric semantics shared by protocol variants.';
COMMENT ON TABLE sensor_template_variants IS 'Protocol-specific configuration for a shared sensor template.';
COMMENT ON TABLE lorawan_v2_node_config_snapshots IS 'Platform semantic snapshot for an upstream LoRaWAN V2 node sensor configuration.';
