import { useMemo, useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useSearchParams } from "react-router-dom";
import { AlertTriangle, Check, Plus, Trash2 } from "lucide-react";
import { api, formatApiError, type AlertEvent, type AlertRule, type Device, type JsonRecord } from "@thcpn/api";
import { useWorkspace, workspaceQueryKey } from "@thcpn/workspace";
import { Badge, Button, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, PageHeader, Panel, SelectInput, StateView, Switch, Tabs, TabsContent, TabsList, TabsTrigger, TextInput } from "./platform-ui";

const duration = (from:string) => { const seconds=Math.max(0,Math.floor((Date.now()-new Date(from).getTime())/1000));return seconds<3600?`${Math.floor(seconds/60)} 分钟`:seconds<86400?`${Math.floor(seconds/3600)} 小时`:`${Math.floor(seconds/86400)} 天`; };

export function AlertsPage(){
  const {currentId}=useWorkspace();const client=useQueryClient();const [params]=useSearchParams();const [createOpen,setCreateOpen]=useState(params.get("new")==="1");const [message,setMessage]=useState("");
  const rules=useQuery({queryKey:workspaceQueryKey(currentId,"alert-rules"),queryFn:()=>api.alerts.rules(currentId!),enabled:Boolean(currentId)});
  const active=useQuery({queryKey:workspaceQueryKey(currentId,"alert-events","active"),queryFn:()=>api.alerts.events(currentId!,{status:"active"}),enabled:Boolean(currentId),refetchInterval:60_000});
  const history=useQuery({queryKey:workspaceQueryKey(currentId,"alert-events","history"),queryFn:()=>api.alerts.events(currentId!),enabled:Boolean(currentId)});
  const refresh=()=>client.invalidateQueries({queryKey:["workspace",currentId]});
  const acknowledge=useMutation({mutationFn:(id:string)=>api.alerts.acknowledge(currentId!,id),onSuccess:refresh,onError:e=>setMessage(formatApiError(e).message)});
  const toggle=async(rule:AlertRule)=>{try{await api.alerts.updateRule(currentId!,rule.id,rulePayload(rule,!rule.enabled));await refresh()}catch(e){setMessage(formatApiError(e).message)}};
  const archive=async(rule:AlertRule)=>{if(!confirm(`确认归档“${rule.name}”？`))return;try{await api.alerts.archiveRule(currentId!,rule.id);await refresh()}catch(e){setMessage(formatApiError(e).message)}};
  if(!currentId)return <StateView type="empty" title="请先选择组织" description="预警规则属于组织。"/>;
  return <div className="alerts-page"><PageHeader eyebrow="运行" title="预警中心" description="持续监测设备指标与在线状态，只在触发和恢复时通知。" actions={<Button onClick={()=>setCreateOpen(true)}><Plus size={15}/>新建预警</Button>}/>{message&&<div className="form-message error">{message}</div>}
    <Tabs defaultValue="active"><TabsList><TabsTrigger value="active">当前预警 {active.data?.items.length?`(${active.data.items.length})`:""}</TabsTrigger><TabsTrigger value="history">历史记录</TabsTrigger><TabsTrigger value="rules">预警规则</TabsTrigger></TabsList>
      <TabsContent value="active"><EventList loading={active.isLoading} error={active.error} items={active.data?.items??[]} active onAcknowledge={id=>acknowledge.mutate(id)}/></TabsContent>
      <TabsContent value="history"><EventList loading={history.isLoading} error={history.error} items={history.data?.items??[]} onAcknowledge={id=>acknowledge.mutate(id)}/></TabsContent>
      <TabsContent value="rules">{rules.isLoading?<StateView type="loading" title="正在加载规则" description=""/>:rules.isError?<StateView type="error" title="规则加载失败" description={formatApiError(rules.error).message}/>:<div className="alert-rule-list">{rules.data?.items.map(rule=><Panel key={rule.id} className="alert-rule-card"><div><div className="alert-card-title"><Badge tone={rule.severity==="critical"?"danger":"warning"}>{rule.severity==="critical"?"严重":"普通"}</Badge><strong>{rule.name}</strong>{rule.effective_status==="paused_plan"&&<Badge tone="neutral">套餐已暂停</Badge>}</div><p>{ruleSummary(rule)}</p><small>{rule.device_name} · 最近状态：{rule.evaluation_state}{rule.last_error?` · ${rule.last_error}`:""}</small></div><div className="alert-card-actions"><Switch checked={rule.enabled} onCheckedChange={()=>void toggle(rule)} aria-label="启停规则"/><Button variant="ghost" onClick={()=>void archive(rule)}><Trash2 size={15}/>归档</Button></div></Panel>)}{!rules.data?.items.length&&<StateView type="empty" title="还没有预警规则" description="创建阈值或设备离线规则，异常时通知指定成员。"/>}</div>}</TabsContent>
    </Tabs><CreateRuleDialog open={createOpen} workspaceId={currentId} initialDeviceId={params.get("device")??""} onClose={()=>setCreateOpen(false)} onSaved={async()=>{setCreateOpen(false);await refresh()}}/></div>;
}

function EventList({items,loading,error,active,onAcknowledge}:{items:AlertEvent[];loading:boolean;error:unknown;active?:boolean;onAcknowledge:(id:string)=>void}){if(loading)return <StateView type="loading" title="正在加载预警" description=""/>;if(error)return <StateView type="error" title="预警加载失败" description={formatApiError(error).message}/>;if(!items.length)return <StateView type="empty" title={active?"当前没有预警":"暂无历史记录"} description={active?"设备运行正常。":"触发和恢复记录会保留在这里."}/>;return <div className="alert-event-list">{items.map(item=><Panel key={item.id} className="alert-event-card"><AlertTriangle size={20}/><div><div className="alert-card-title"><Badge tone={item.severity==="critical"?"danger":"warning"}>{item.severity==="critical"?"严重":"普通"}</Badge><strong>{item.title}</strong>{item.resolved_at&&<Badge tone="success">已恢复</Badge>}</div><p>{item.content}</p><small>{item.device_name} · {new Date(item.triggered_at).toLocaleString()} · 持续 {duration(item.triggered_at)}</small></div><div className="alert-card-actions"><Link className="alert-device-link" to={`/devices/${item.device_id}`}>查看设备</Link>{!item.acknowledged_at&&<Button onClick={()=>onAcknowledge(item.id)}><Check size={15}/>确认</Button>}</div></Panel>)}</div>}

function CreateRuleDialog({open,workspaceId,initialDeviceId,onClose,onSaved}:{open:boolean;workspaceId:string;initialDeviceId:string;onClose:()=>void;onSaved:()=>void}){
  const [step,setStep]=useState(initialDeviceId?2:1),[type,setType]=useState("telemetry_threshold"),[deviceId,setDeviceId]=useState(initialDeviceId),[streamId,setStreamId]=useState(""),[mode,setMode]=useState("above"),[threshold,setThreshold]=useState(""),[durationMinutes,setDuration]=useState("5"),[offlineMinutes,setOffline]=useState("30"),[severity,setSeverity]=useState("warning"),[recipients,setRecipients]=useState<string[]>([]),[email,setEmail]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const devices=useQuery({queryKey:workspaceQueryKey(workspaceId,"devices","alerts"),queryFn:()=>api.devices.list(workspaceId),enabled:open});
  const streams=useQuery({queryKey:["alert-streams",deviceId],queryFn:()=>api.dataStreams.list(deviceId),enabled:open&&Boolean(deviceId)&&type==="telemetry_threshold"});
  const members=useQuery({queryKey:workspaceQueryKey(workspaceId,"members","alerts"),queryFn:()=>api.members.list(workspaceId),enabled:open});
  const selectedDevice=devices.data?.items.find(d=>d.id===deviceId);const selectedStream=streams.data?.items.find(s=>s.id===streamId);
  const memberItems=(members.data?.items??[]) as Array<JsonRecord>;const summary=useMemo(()=>type==="device_offline"?`${selectedDevice?.name??"设备"} 超过 ${offlineMinutes} 分钟无数据时触发`: `${selectedDevice?.name??"设备"}的${selectedStream?.name??"指标"}${mode==="above"?"高于":mode==="below"?"低于":"超出区间"} ${threshold||"阈值"}${selectedStream?.unit??""} 持续 ${durationMinutes} 分钟时触发`,[type,selectedDevice,selectedStream,mode,threshold,durationMinutes,offlineMinutes]);
  const submit=async()=>{setBusy(true);setError("");try{const value=Number(threshold);const condition:any={mode,duration_seconds:Number(durationMinutes)*60,recovery_delta:Math.abs(value)*.02};if(mode==="above")condition.upper=value;else if(mode==="below")condition.lower=value;else{const [lower,upper]=threshold.split(",").map(Number);condition.lower=lower;condition.upper=upper;condition.recovery_delta=Math.abs(upper-lower)*.02}await api.alerts.createRule(workspaceId,{name:summary,type,severity,device_id:deviceId,data_stream_id:type==="telemetry_threshold"?streamId:undefined,condition,offline_after_seconds:type==="device_offline"?Number(offlineMinutes)*60:undefined,recipient_user_ids:recipients,channels:email?["in_app","email"]:["in_app"],enabled:true});onSaved()}catch(e){setError(formatApiError(e).message)}finally{setBusy(false)}};
  return <Dialog open={open} onOpenChange={value=>!value&&onClose()}><DialogContent className="alert-rule-dialog"><DialogHeader><DialogTitle>新建预警规则</DialogTitle><DialogDescription>第 {step} / 4 步 · {summary}</DialogDescription></DialogHeader>{error&&<div className="form-message error">{error}</div>}
    {step===1&&<Field label="选择设备"><SelectInput value={deviceId} onChange={e=>setDeviceId(e.target.value)}><option value="">请选择</option>{devices.data?.items.map((d:Device)=><option key={d.id} value={d.id}>{d.name}</option>)}</SelectInput></Field>}
    {step===2&&<><Field label="预警类型"><SelectInput value={type} onChange={e=>setType(e.target.value)}><option value="telemetry_threshold">指标阈值</option><option value="device_offline">设备离线</option></SelectInput></Field>{type==="telemetry_threshold"&&<Field label="指标"><SelectInput value={streamId} onChange={e=>setStreamId(e.target.value)}><option value="">请选择</option>{streams.data?.items.filter(s=>s.type==="telemetry").map(s=><option key={s.id} value={s.id}>{s.name} {s.unit&&`(${s.unit})`}</option>)}</SelectInput></Field>}</>}
    {step===3&&(type==="device_offline"?<Field label="无数据时长（分钟）"><TextInput type="number" min="1" value={offlineMinutes} onChange={e=>setOffline(e.target.value)}/></Field>:<div className="alert-form-grid"><Field label="条件"><SelectInput value={mode} onChange={e=>setMode(e.target.value)}><option value="above">高于</option><option value="below">低于</option><option value="outside">超出区间</option></SelectInput></Field><Field label={mode==="outside"?"下限,上限":"阈值"}><TextInput value={threshold} placeholder={mode==="outside"?"10,30":"30"} onChange={e=>setThreshold(e.target.value)}/></Field><Field label="持续时间（分钟）"><TextInput type="number" min="1" value={durationMinutes} onChange={e=>setDuration(e.target.value)}/></Field><Field label="严重级别"><SelectInput value={severity} onChange={e=>setSeverity(e.target.value)}><option value="warning">普通</option><option value="critical">严重</option></SelectInput></Field></div>)}
    {step===4&&<><Field label="接收成员"><div className="alert-recipient-list">{memberItems.map(m=>{const id=String(m.user_id??m.id??"");const label=String(m.user_name??m.name??m.email??id);return <label key={id}><input type="checkbox" checked={recipients.includes(id)} onChange={e=>setRecipients(current=>e.target.checked?[...current,id]:current.filter(x=>x!==id))}/>{label}</label>})}</div></Field><label className="alert-email-toggle"><Switch checked={email} onCheckedChange={setEmail}/>同时发送邮件（仅已验证邮箱）</label></>}
    <DialogFooter><Button variant="secondary" onClick={()=>step===1?onClose():setStep(step-1)}>{step===1?"取消":"上一步"}</Button>{step<4?<Button disabled={(step===1&&!deviceId)||(step===2&&type==="telemetry_threshold"&&!streamId)} onClick={()=>setStep(step+1)}>下一步</Button>:<Button disabled={busy||!recipients.length} onClick={()=>void submit()}>{busy?"正在创建…":"创建规则"}</Button>}</DialogFooter></DialogContent></Dialog>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="alert-field"><span>{label}</span>{children}</label>}
function ruleSummary(rule:AlertRule){if(rule.type==="device_offline")return `超过 ${Math.floor((rule.offline_after_seconds??0)/60)} 分钟无数据`;const condition=rule.condition_mode==="above"?`高于 ${rule.upper}`:rule.condition_mode==="below"?`低于 ${rule.lower}`:`超出 ${rule.lower}–${rule.upper}`;return `${rule.data_stream_name??"指标"} ${condition}${rule.unit??""}，持续 ${Math.floor(rule.duration_seconds/60)} 分钟`}
function rulePayload(rule:AlertRule,enabled:boolean):JsonRecord{return {name:rule.name,type:rule.type,severity:rule.severity,device_id:rule.device_id,data_stream_id:rule.data_stream_id,condition:{mode:rule.condition_mode,lower:rule.lower,upper:rule.upper,duration_seconds:rule.duration_seconds,recovery_delta:rule.recovery_delta},offline_after_seconds:rule.offline_after_seconds,recipient_user_ids:rule.recipient_user_ids,channels:rule.channels,enabled}}
