import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { QRCodeSVG } from "qrcode.react";
import { Check, Copy, KeyRound, Laptop, MailCheck, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import { api, authStorage, formatApiError, type AuthSession, type TotpSetup } from "@thcpn/api";
import { useAuth } from "@thcpn/auth";
import { Badge, Button, Panel, StateView } from "@thcpn/ui";

const formatTime = (input?: string) => input ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "medium" }).format(new Date(input)) : "—";
export const validSixDigitCode = (code: string) => /^\d{6}$/.test(code);

export function SecurityTab() {
  const { user, refreshUser } = useAuth();
  const sessions = useQuery({ queryKey: ["auth", "sessions"], queryFn: api.auth.sessions });
  const mfa = useQuery({ queryKey: ["auth", "mfa"], queryFn: api.auth.mfaStatus });
  const [feedback, setFeedback] = useState("");
  const [busy, setBusy] = useState("");
  const run = async (key: string, action: () => Promise<unknown>, success: string, after?: () => Promise<unknown>) => { setBusy(key); setFeedback(""); try { await action(); setFeedback(success); await after?.(); return true; } catch (error) { const item = formatApiError(error); setFeedback(`${item.message}${item.requestId ? ` · request id ${item.requestId}` : ""}`); return false; } finally { setBusy(""); } };
  const refreshToken = async () => { const tokens = authStorage.read(); if (!tokens) throw new Error("当前没有可用 refresh token"); const response = await api.auth.refresh(tokens.refreshToken); authStorage.write({ accessToken: response.access_token, refreshToken: response.refresh_token }); };
  return <><div className="security-summary"><div><ShieldCheck size={18} /><strong>{mfa.data?.totp_enabled ? "已启用" : "未启用"}</strong><span>双重验证</span></div><div><MailCheck size={18} /><strong>{user?.email_verified_at ? "已验证" : "未验证"}</strong><span>邮箱状态</span></div><div><Laptop size={18} /><strong>{sessions.data?.items.length ?? "—"}</strong><span>活动会话</span></div></div>{feedback && <div className="command-note section-gap">{feedback}</div>}<div className="grid grid-2 section-gap"><EmailSecurity userEmail={user?.email} verifiedAt={user?.email_verified_at} busy={busy} run={run} refreshUser={refreshUser} /><MfaSecurity status={mfa.data} loading={mfa.isLoading} error={mfa.error} busy={busy} run={run} refresh={() => mfa.refetch()} /></div><Panel className="section-gap"><div className="panel-header"><div><h2 className="panel-title">登录会话</h2><div className="panel-kicker">撤销不再使用或不认识的设备会话</div></div><div className="header-actions"><Button variant="secondary" disabled={busy === "token"} onClick={() => void run("token", refreshToken, "Token 已安全轮换")}><KeyRound size={13} />刷新 Token</Button><Button variant="secondary" onClick={() => void sessions.refetch()}><RefreshCw size={13} />刷新</Button></div></div>{sessions.isLoading ? <StateView type="loading" title="正在加载会话" description="正在读取活动 refresh sessions。" /> : sessions.error ? <StateView type="error" title="会话加载失败" description={formatApiError(sessions.error).message} requestId={formatApiError(sessions.error).requestId} /> : sessions.data?.items.length ? <div className="session-list">{sessions.data.items.map((item) => <SessionRow key={item.id} session={item} busy={busy === item.id} revoke={() => window.confirm("确认撤销该登录会话？对应设备将需要重新登录。") && void run(item.id, () => api.auth.revokeSession(item.id), "会话已撤销", () => sessions.refetch())} />)}</div> : <StateView type="empty" title="暂无活动会话" description="服务端当前没有返回 refresh session。" />}</Panel></>;
}

function EmailSecurity({ userEmail, verifiedAt, busy, run, refreshUser }: { userEmail?: string; verifiedAt?: string; busy: string; run: (key: string, action: () => Promise<unknown>, success: string, after?: () => Promise<unknown>) => Promise<boolean>; refreshUser: () => Promise<void> }) {
  const [code, setCode] = useState(""); const [cooldown, setCooldown] = useState(0);
  useEffect(() => { if (cooldown <= 0) return; const timer = window.setInterval(() => setCooldown((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [cooldown > 0]);
  const send = async () => { let wait = 60; const ok = await run("email-send", async () => { const result = await api.auth.sendEmailCode(userEmail!); wait = result.cooldown_seconds; }, "邮箱验证码已发送"); if (ok) setCooldown(wait); };
  return <Panel><div className="panel-header"><div><h2 className="panel-title">邮箱验证</h2><div className="panel-kicker">用于账号恢复和安全通知</div></div><Badge tone={verifiedAt ? "success" : userEmail ? "warning" : "neutral"}>{verifiedAt ? "已验证" : userEmail ? "待验证" : "未设置"}</Badge></div><div className="security-form">{!userEmail ? <StateView type="empty" title="账号未设置邮箱" description="当前 API 不支持在此修改身份邮箱，请使用已绑定邮箱的账号完成验证。" /> : <><label className="field"><span className="field-label">账号邮箱</span><input type="email" disabled value={userEmail} /></label>{verifiedAt ? <div className="verified-line"><Check size={15} />验证于 {formatTime(verifiedAt)}</div> : <><div className="security-code-row"><label className="field"><span className="field-label">6 位验证码</span><input inputMode="numeric" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} /></label><Button variant="secondary" type="button" disabled={cooldown > 0 || busy === "email-send"} onClick={() => void send()}>{cooldown > 0 ? `${cooldown}s` : "发送验证码"}</Button></div><Button disabled={!validSixDigitCode(code) || busy === "email-verify"} onClick={() => void run("email-verify", () => api.auth.verifyEmailCode(userEmail, code), "邮箱验证成功", refreshUser)}>验证邮箱</Button></>}</>}</div></Panel>;
}

function MfaSecurity({ status, loading, error, busy, run, refresh }: { status?: { totp_enabled: boolean; totp_enabled_at?: string }; loading: boolean; error: unknown; busy: string; run: (key: string, action: () => Promise<unknown>, success: string, after?: () => Promise<unknown>) => Promise<boolean>; refresh: () => Promise<unknown> }) {
  const [setup, setSetup] = useState<TotpSetup | null>(null); const [code, setCode] = useState("");
  if (loading) return <Panel><StateView type="loading" title="正在读取 MFA 状态" description="正在检查双重验证配置。" /></Panel>;
  if (error) return <Panel><StateView type="error" title="MFA 状态加载失败" description={formatApiError(error).message} requestId={formatApiError(error).requestId} /></Panel>;
  const beginSetup = () => run("mfa-setup", async () => setSetup(await api.auth.mfaSetup()), "MFA 密钥已生成，请完成绑定");
  const enable = () => run("mfa-enable", () => api.auth.mfaEnable(code), "MFA 已启用", async () => { setSetup(null); setCode(""); await refresh(); });
  const disable = () => run("mfa-disable", () => api.auth.mfaDisable(code), "MFA 已禁用", async () => { setCode(""); await refresh(); });
  return <Panel><div className="panel-header"><div><h2 className="panel-title">TOTP 双重验证</h2><div className="panel-kicker">使用身份验证器生成动态验证码</div></div><Badge tone={status?.totp_enabled ? "success" : "neutral"}>{status?.totp_enabled ? "已启用" : "未启用"}</Badge></div><div className="security-form">{status?.totp_enabled ? <><div className="verified-line"><ShieldCheck size={15} />启用于 {formatTime(status.totp_enabled_at)}</div><label className="field"><span className="field-label">当前 TOTP 验证码</span><input inputMode="numeric" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} /></label><Button variant="danger" disabled={!validSixDigitCode(code) || busy === "mfa-disable"} onClick={() => window.confirm("确认禁用 MFA？账号将只依赖主登录凭据。") && void disable()}>禁用 MFA</Button></> : setup ? <><div className="mfa-setup"><QRCodeSVG value={setup.otpauth_uri} size={152} level="M" /><div><div className="field-label">手动输入密钥</div><strong className="mono">{setup.secret}</strong><Button variant="secondary" onClick={() => void navigator.clipboard.writeText(setup.secret)}><Copy size={13} />复制密钥</Button></div></div><label className="field"><span className="field-label">身份验证器中的 6 位验证码</span><input inputMode="numeric" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} /></label><Button disabled={!validSixDigitCode(code) || busy === "mfa-enable"} onClick={() => void enable()}>验证并启用</Button></> : <><div className="security-note">启用后，密码或短信登录还需要输入身份验证器中的 6 位动态验证码。</div><Button disabled={busy === "mfa-setup"} onClick={() => void beginSetup()}>开始设置 MFA</Button></>}</div></Panel>;
}

function SessionRow({ session, busy, revoke }: { session: AuthSession; busy: boolean; revoke: () => void }) { return <div><div className="session-icon"><Laptop size={16} /></div><div><div className="cell-title">{session.user_agent || "未知客户端"}</div><div className="cell-sub">IP：{session.client_ip || "未知"} · 最近使用：{formatTime(session.last_used_at)}</div><div className="cell-sub">创建：{formatTime(session.created_at)} · 过期：{formatTime(session.expires_at)}</div><div className="cell-sub mono">{session.id}</div></div><Button variant="danger" disabled={busy} onClick={revoke}><Trash2 size={13} />撤销</Button></div>; }
