// @ts-nocheck
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { App, Alert, Button, Drawer, Form, Input, Modal, Space, Table, Tag } from "@thcpn/admin-ui";
import { api, formatApiError } from "@thcpn/api";
import { PageHeader, Panel, StateView } from "@thcpn/ui";
import { KeyRound, Plus, Settings2, Trash2 } from "lucide-react";

export function AdminDemoAccountsPage() {
  const { message } = App.useApp(); const client = useQueryClient();
  const [createOpen,setCreateOpen]=useState(false); const [selected,setSelected]=useState(null); const [passwordFor,setPasswordFor]=useState(null);
  const [createForm]=Form.useForm(); const [passwordForm]=Form.useForm();
  const accounts=useQuery({queryKey:["admin","demo-accounts"],queryFn:api.admin.demoAccounts.list});
  const create=async()=>{try{const v=await createForm.validateFields();await api.admin.demoAccounts.create(v);setCreateOpen(false);createForm.resetFields();await client.invalidateQueries({queryKey:["admin","demo-accounts"]});message.success("演示账号已创建")}catch(e){if(!e?.errorFields)message.error(formatApiError(e).message)}};
  const status=async(row)=>{try{await api.admin.demoAccounts.update(row.user_id,{status:row.status==="active"?"disabled":"active"});await client.invalidateQueries({queryKey:["admin","demo-accounts"]})}catch(e){message.error(formatApiError(e).message)}};
  const reset=async()=>{try{const v=await passwordForm.validateFields();await api.admin.demoAccounts.resetPassword(passwordFor.user_id,v.password);setPasswordFor(null);passwordForm.resetFields();message.success("密码已重置，旧会话已失效")}catch(e){if(!e?.errorFields)message.error(formatApiError(e).message)}};
  return <><PageHeader eyebrow="SYSTEM / DEMO ACCOUNTS" title="演示账号" description="独立管理展会和客户演示账号；每个账号拥有自己的演示空间与完整业务功能。" actions={<Button type="primary" icon={<Plus size={15}/>} onClick={()=>setCreateOpen(true)}>创建演示账号</Button>}/><Panel>{accounts.isError?<StateView type="error" title="加载失败" description={formatApiError(accounts.error).message}/>:<Table rowKey="user_id" loading={accounts.isLoading} dataSource={accounts.data?.items??[]} columns={[{title:"账号",render:(_,r)=><div><strong>{r.name}</strong><div className="cell-sub mono">{r.username}</div></div>},{title:"演示空间",dataIndex:"workspace_name"},{title:"设备",render:(_,r)=>`${r.device_count} 台`},{title:"状态",render:(_,r)=><Tag color={r.status==="active"?"green":"default"}>{r.status==="active"?"启用":"停用"}</Tag>},{title:"操作",render:(_,r)=><Space><Button icon={<Settings2 size={14}/>} onClick={()=>setSelected(r)}>设备清单</Button><Button onClick={()=>status(r)}>{r.status==="active"?"停用":"启用"}</Button><Button icon={<KeyRound size={14}/>} onClick={()=>setPasswordFor(r)}>重置密码</Button></Space>}]} pagination={false}/>}</Panel><Modal title="创建演示账号" open={createOpen} onCancel={()=>setCreateOpen(false)} onOk={create}><Form form={createForm} layout="vertical"><Form.Item name="username" label="登录用户名" rules={[{required:true,min:3}]}><Input autoComplete="off"/></Form.Item><Form.Item name="name" label="显示名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="password" label="密码" rules={[{required:true,min:8}]}><Input.Password autoComplete="new-password"/></Form.Item></Form></Modal><Modal title={`重置 ${passwordFor?.username??""} 的密码`} open={!!passwordFor} onCancel={()=>setPasswordFor(null)} onOk={reset}><Alert type="warning" showIcon message="保存后该账号的所有旧会话立即失效。"/><Form form={passwordForm} layout="vertical" style={{marginTop:16}}><Form.Item name="password" label="新密码" rules={[{required:true,min:8}]}><Input.Password/></Form.Item></Form></Modal><Drawer size="large" title={`${selected?.name??""} · 设备清单`} open={!!selected} onClose={()=>setSelected(null)} destroyOnClose>{selected&&<DemoDeviceList account={selected}/>}</Drawer></>;
}
function DemoDeviceList({account}){const {message}=App.useApp();const client=useQueryClient();const [q,setQ]=useState("");const [page,setPage]=useState(1);const data=useQuery({queryKey:["admin","demo-accounts",account.user_id,"devices",q,page],queryFn:()=>api.admin.demoAccounts.devices(account.user_id,q,20,(page-1)*20)});const change=async(row)=>{try{if(row.selected)await api.admin.demoAccounts.removeDevice(account.user_id,row.id);else await api.admin.demoAccounts.addDevice(account.user_id,row.id);await Promise.all([client.invalidateQueries({queryKey:["admin","demo-accounts"]}),client.invalidateQueries({queryKey:["admin","demo-accounts",account.user_id,"devices"]})])}catch(e){message.error(formatApiError(e).message)}};return <><Alert type="info" showIcon message="设备保持原组织归属；同一真实设备可以加入多个演示空间。移出只删除当前空间的引用。"/><Input.Search style={{margin:"16px 0",maxWidth:480}} placeholder="搜索设备名称或 SN" allowClear onSearch={v=>{setQ(v);setPage(1)}}/><Table rowKey="id" loading={data.isLoading} dataSource={data.data?.items??[]} columns={[{title:"设备",render:(_,r)=><div><strong>{r.name}</strong><div className="cell-sub mono">{r.serial_no}</div></div>},{title:"类型",dataIndex:"device_type"},{title:"原组织",render:(_,r)=>r.source_workspace_name||"未分配"},{title:"操作",render:(_,r)=>r.selected?<Button danger icon={<Trash2 size={14}/>} onClick={()=>change(r)}>移出</Button>:<Button type="primary" onClick={()=>change(r)}>加入</Button>}]} pagination={{current:page,pageSize:20,total:data.data?.total??0,onChange:setPage,showSizeChanger:false}}/></>}
