import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { MonitorUp, RefreshCw } from "lucide-react";
import { api, formatApiError, type WallboardTemplate } from "@thcpn/api";
import { Badge, Button, PageHeader, Panel, SelectInput, StateView, TextInput } from "@thcpn/ui";

export function AdminWallboardTemplatesPage() {
  const client = useQueryClient(); const [editing,setEditing]=useState<WallboardTemplate|null>(null); const [message,setMessage]=useState("");
  const query=useQuery({queryKey:["admin","wallboard-templates"],queryFn:api.admin.wallboardTemplates.list});
  const sync=async()=>{setMessage("");try{await api.admin.wallboardTemplates.sync();await client.invalidateQueries({queryKey:["admin","wallboard-templates"]});setMessage("模板目录已同步")}catch(error){setMessage(formatApiError(error).message)}};
  return <><PageHeader eyebrow="平台管理" title="大屏模板" description="同步代码内置模板，并控制上下架、模板等级和开通文案。" actions={<Button onClick={()=>void sync()}><RefreshCw size={15}/>同步模板</Button>}/>{message&&<div className="command-note">{message}</div>}<Panel>{query.isLoading?<StateView type="loading" title="正在加载模板" description=""/>:query.isError?<StateView type="error" title="模板加载失败" description={formatApiError(query.error).message}/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>模板</th><th>组件 / 版本</th><th>状态</th><th>等级</th><th>价格</th><th>操作</th></tr></thead><tbody>{query.data?.items.map(item=><tr key={item.code}><td><div className="cell-title">{item.name}</div><div className="cell-sub">{item.description}</div></td><td><code>{item.component_key}</code><div className="cell-sub">v{item.version}</div></td><td><Badge tone={item.status==="published"?"success":"neutral"}>{item.status==="published"?"已上架":"已下架"}</Badge></td><td><Badge tone={item.tier==="free"?"info":"warning"}>{item.tier==="free"?"免费":"高级"}</Badge></td><td>{item.display_price||"—"}</td><td><Button variant="secondary" onClick={()=>setEditing(item)}>设置</Button></td></tr>)}</tbody></table></div>}</Panel>{editing&&<TemplateEditor item={editing} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await client.invalidateQueries({queryKey:["admin","wallboard-templates"]})}}/>}</>;
}
function TemplateEditor({item,onClose,onSaved}:{item:WallboardTemplate;onClose:()=>void;onSaved:()=>void}){const[status,setStatus]=useState(item.status);const[tier,setTier]=useState(item.tier);const[price,setPrice]=useState(item.display_price);const[copy,setCopy]=useState(item.contact_copy);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const save=async()=>{setBusy(true);setError("");try{await api.admin.wallboardTemplates.update(item.code,{status,tier,display_price:price,contact_copy:copy});await onSaved()}catch(e){setError(formatApiError(e).message)}finally{setBusy(false)}};return <div className="modal-layer"><div className="modal-card"><div className="panel-header"><div><div className="panel-kicker">模板设置</div><h2>{item.name}</h2></div><MonitorUp size={20}/></div><div className="form-grid"><label><span>上架状态</span><SelectInput value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="published">已上架</option><option value="unpublished">已下架</option></SelectInput></label><label><span>模板等级</span><SelectInput value={tier} onChange={e=>setTier(e.target.value as typeof tier)}><option value="free">免费模板</option><option value="premium">高级模板</option></SelectInput></label><label><span>展示价格</span><TextInput value={price} onChange={e=>setPrice(e.target.value)} placeholder="例如 ¥9,800 / 年"/></label><label><span>联系开通文案</span><TextInput value={copy} onChange={e=>setCopy(e.target.value)}/></label></div>{error&&<div className="command-note">{error}</div>}<div className="modal-actions"><Button variant="secondary" onClick={onClose}>取消</Button><Button disabled={busy} onClick={()=>void save()}>{busy?"正在保存…":"保存"}</Button></div></div></div>}
